language: "en-US"
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: false
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "wip"
  tools:
    golangci-lint:
      enabled: true
chat:
  auto_reply: true