package store

import (
	"fmt"
	raftcmdpb "github.com/feichai0017/NoKV/pb/raft"
	"sync"
	"time"

	myraft "github.com/feichai0017/NoKV/raft"
	"github.com/feichai0017/NoKV/raftstore/command"
)

type commandRuntime struct {
	apply   func(*raftcmdpb.RaftCmdRequest) (*raftcmdpb.RaftCmdResponse, error)
	pipe    *commandPipeline
	timeout time.Duration
}

type commandProposal struct {
	ch chan proposalResult
}

type proposalResult struct {
	resp *raftcmdpb.RaftCmdResponse
	err  error
}

type commandProposalKey struct {
	regionID  uint64
	peerID    uint64
	requestID uint64
}

func proposalKeyFromHeader(header *raftcmdpb.CmdHeader) commandProposalKey {
	if header == nil {
		return commandProposalKey{}
	}
	return commandProposalKey{
		regionID:  header.GetRegionId(),
		peerID:    header.GetPeerId(),
		requestID: header.GetRequestId(),
	}
}

func (k commandProposalKey) valid() bool {
	return k.regionID != 0 && k.peerID != 0 && k.requestID != 0
}

type commandPipeline struct {
	mu        sync.Mutex
	seq       uint64
	proposals map[commandProposalKey]*commandProposal
	applier   func(*raftcmdpb.RaftCmdRequest) (*raftcmdpb.RaftCmdResponse, error)
}

type applyEventEmitter func(myraft.Entry, *raftcmdpb.RaftCmdRequest, *raftcmdpb.RaftCmdResponse)

func newCommandPipeline(applier func(*raftcmdpb.RaftCmdRequest) (*raftcmdpb.RaftCmdResponse, error)) *commandPipeline {
	return &commandPipeline{
		proposals: make(map[commandProposalKey]*commandProposal),
		applier:   applier,
	}
}

func (cp *commandPipeline) nextProposalID() uint64 {
	if cp == nil {
		return 0
	}
	cp.mu.Lock()
	defer cp.mu.Unlock()
	cp.seq++
	return cp.seq
}

func (cp *commandPipeline) registerProposal(key commandProposalKey) (*commandProposal, error) {
	if cp == nil || !key.valid() {
		return nil, nil
	}
	cp.mu.Lock()
	defer cp.mu.Unlock()
	if _, exists := cp.proposals[key]; exists {
		return nil, fmt.Errorf("commandPipeline: duplicate proposal id region=%d peer=%d request=%d", key.regionID, key.peerID, key.requestID)
	}
	prop := &commandProposal{ch: make(chan proposalResult, 1)}
	cp.proposals[key] = prop
	return prop, nil
}

func (cp *commandPipeline) removeProposal(key commandProposalKey) {
	if cp == nil || !key.valid() {
		return
	}
	cp.mu.Lock()
	delete(cp.proposals, key)
	cp.mu.Unlock()
}

func (cp *commandPipeline) completeProposal(key commandProposalKey, resp *raftcmdpb.RaftCmdResponse, err error) {
	if cp == nil || !key.valid() {
		return
	}
	cp.mu.Lock()
	prop := cp.proposals[key]
	delete(cp.proposals, key)
	cp.mu.Unlock()
	if prop == nil {
		return
	}
	prop.ch <- proposalResult{resp: resp, err: err}
	close(prop.ch)
}

func (cp *commandPipeline) applyEntries(entries []myraft.Entry, emitters ...applyEventEmitter) error {
	if cp == nil {
		return fmt.Errorf("commandPipeline: pipeline is nil")
	}
	var emit applyEventEmitter
	if len(emitters) > 0 {
		emit = emitters[0]
	}
	for _, entry := range entries {
		if entry.Type != myraft.EntryNormal {
			continue
		}
		if len(entry.Data) == 0 {
			continue
		}
		req, isCmd, err := command.Decode(entry.Data)
		if err != nil {
			return err
		}
		if !isCmd {
			return fmt.Errorf("commandPipeline: unsupported unframed raft payload")
		}
		if cp.applier == nil {
			return fmt.Errorf("commandPipeline: apply without handler")
		}
		resp, applyErr := cp.applier(req)
		if applyErr != nil {
			key := proposalKeyFromHeader(req.GetHeader())
			cp.completeProposal(key, nil, applyErr)
			return fmt.Errorf("commandPipeline: apply request %d failed: %w", key.requestID, applyErr)
		}
		if emit != nil {
			emit(entry, req, resp)
		}
		// Request IDs are generated by each store, not by the raft group. A
		// follower can therefore apply a foreign leader's entry with the same
		// request ID as a local in-flight proposal. The region/peer fence keeps
		// foreign raft entries from completing the wrong client waiter.
		cp.completeProposal(proposalKeyFromHeader(req.GetHeader()), resp, nil)
	}
	return nil
}

func (s *Store) applyEntries(entries []myraft.Entry) error {
	if s == nil {
		return errNilStore
	}
	if s.cmds == nil || s.cmds.pipe == nil {
		return errCommandApplyWithoutHandler
	}
	return s.cmds.pipe.applyEntries(entries, s.emitApplyEvents)
}
