// Copyright 2024-2026 The NoKV Authors.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/feichai0017/NoKV/fsmeta/exec/compile/specdsl"
	"github.com/feichai0017/NoKV/fsmeta/exec/compile/specs"
)

func main() {
	outDir := flag.String("out", ".", "directory for generated files")
	flag.Parse()

	groups := make(map[string][]specdsl.OpSpec)
	var files []string
	for _, spec := range specs.All() {
		fileName := generatedFileName(spec)
		if _, ok := groups[fileName]; !ok {
			files = append(files, fileName)
		}
		groups[fileName] = append(groups[fileName], spec)
	}

	for _, fileName := range files {
		source, err := emitFile(groups[fileName])
		if err != nil {
			fmt.Fprintf(os.Stderr, "fsmeta-opgen: %v\n", err)
			os.Exit(1)
		}
		formatted, err := format.Source(source)
		if err != nil {
			fmt.Fprintf(os.Stderr, "fsmeta-opgen: format %s: %v\n%s", fileName, err, source)
			os.Exit(1)
		}
		path := filepath.Join(*outDir, fileName)
		if err := os.WriteFile(path, formatted, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "fsmeta-opgen: write %s: %v\n", path, err)
			os.Exit(1)
		}
	}

	source, err := emitDispatch(specs.All())
	if err != nil {
		fmt.Fprintf(os.Stderr, "fsmeta-opgen: %v\n", err)
		os.Exit(1)
	}
	formatted, err := format.Source(source)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fsmeta-opgen: format dispatch.program.go: %v\n%s", err, source)
		os.Exit(1)
	}
	path := filepath.Join(*outDir, "dispatch.program.go")
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "fsmeta-opgen: write %s: %v\n", path, err)
		os.Exit(1)
	}

	source, err = emitReadPrograms(specs.ReadAll())
	if err != nil {
		fmt.Fprintf(os.Stderr, "fsmeta-opgen: %v\n", err)
		os.Exit(1)
	}
	formatted, err = format.Source(source)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fsmeta-opgen: format read.program.go: %v\n%s", err, source)
		os.Exit(1)
	}
	path = filepath.Join(*outDir, "read.program.go")
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "fsmeta-opgen: write %s: %v\n", path, err)
		os.Exit(1)
	}
}

func generatedFileName(spec specdsl.OpSpec) string {
	if spec.FileName != "" {
		return spec.FileName
	}
	return strings.ToLower(spec.Name) + ".program.go"
}

func emitReadPrograms(readSpecs []specdsl.ReadSpec) ([]byte, error) {
	required := map[string]specdsl.ReadSpec{
		"Lookup":           {OperationKind: "fsmeta.OperationLookup", KeyShape: "dentry", Authority: "parent", Source: "point"},
		"GetAttr":          {OperationKind: "fsmeta.OperationGetAttr", KeyShape: "inode", Authority: "inode", Source: "point"},
		"ReadSession":      {OperationKind: "fsmeta.OperationReadSession", KeyShape: "session", Authority: "inode", Source: "point"},
		"ReadSessionOwner": {OperationKind: "fsmeta.OperationReadSession", KeyShape: "session_owner", Authority: "inode", Source: "point"},
		"ReadSessionKey":   {OperationKind: "fsmeta.OperationReadSession", KeyShape: "session_key", Authority: "session_key", Source: "point"},
		"ReadDir":          {OperationKind: "fsmeta.OperationReadDir", KeyShape: "dentry_prefix", Authority: "parent", Source: "directory"},
	}
	for _, spec := range readSpecs {
		expected, ok := required[spec.Name]
		if !ok {
			return nil, fmt.Errorf("unsupported read spec %q", spec.Name)
		}
		if spec.OperationKind != expected.OperationKind || spec.KeyShape != expected.KeyShape ||
			spec.Authority != expected.Authority || spec.Source != expected.Source {
			return nil, fmt.Errorf("read spec %q does not match generated binding", spec.Name)
		}
		delete(required, spec.Name)
	}
	if len(required) != 0 {
		missing := make([]string, 0, len(required))
		for name := range required {
			missing = append(missing, name)
		}
		slices.Sort(missing)
		return nil, fmt.Errorf("missing read specs %s", strings.Join(missing, ", "))
	}
	var b bytes.Buffer
	b.WriteString("// Copyright 2024-2026 The NoKV Authors.\n")
	b.WriteString("// SPDX-License-Identifier: Apache-2.0\n\n")
	b.WriteString("// Code generated by fsmeta-opgen; DO NOT EDIT.\n\n")
	b.WriteString("package compile\n\n")
	b.WriteString("import \"github.com/feichai0017/NoKV/fsmeta\"\n\n")
	b.WriteString("func CompileLookupReadProgram(req fsmeta.LookupRequest, mount fsmeta.MountIdentity) (ReadProgram, error) {\n")
	b.WriteString("\tplan, err := fsmeta.PlanLookup(req, mount)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn ReadProgram{}, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tref := keyRef(KeyAccessRead, plan.PrimaryKey)\n")
	b.WriteString("\treturn ReadProgram{Kind: ReadProgramLookup, Plan: plan, Authority: AuthorityPlan{Scope: scopeFor(mount, []fsmeta.InodeID{req.Parent}, nil), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(plan.PrimaryKey))}, Key: cloneBytes(plan.PrimaryKey)}, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func CompileGetAttrReadProgram(mount fsmeta.MountIdentity, inode fsmeta.InodeID) (ReadProgram, error) {\n")
	b.WriteString("\tkey, err := fsmeta.EncodeInodeKey(mount, inode)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn ReadProgram{}, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tref := keyRef(KeyAccessRead, key)\n")
	b.WriteString("\treturn ReadProgram{Kind: ReadProgramGetAttr, Plan: fsmeta.OperationPlan{Kind: fsmeta.OperationGetAttr, Mount: mount.MountID, PrimaryKey: cloneBytes(key), ReadKeys: [][]byte{cloneBytes(key)}, ReadPrefixes: emptyKeySet, MutateKeys: emptyKeySet}, Authority: AuthorityPlan{Scope: scopeFor(mount, nil, []fsmeta.InodeID{inode}), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(key))}, Key: cloneBytes(key)}, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func CompileReadDirPlusInodeKeys(mount fsmeta.MountIdentity, dentries []fsmeta.DentryRecord) ([][]byte, error) {\n")
	b.WriteString("\tkeys := make([][]byte, len(dentries))\n")
	b.WriteString("\tfor i, dentry := range dentries {\n")
	b.WriteString("\t\tkey, err := fsmeta.EncodeInodeKey(mount, dentry.Inode)\n")
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\treturn nil, err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tkeys[i] = key\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn keys, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func CompileReadSessionProgram(mount fsmeta.MountIdentity, inode fsmeta.InodeID, session fsmeta.SessionID) (ReadProgram, error) {\n")
	b.WriteString("\tkey, err := fsmeta.EncodeSessionKey(mount, inode, session)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn ReadProgram{}, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tref := keyRef(KeyAccessRead, key)\n")
	b.WriteString("\treturn ReadProgram{Kind: ReadProgramReadSession, Plan: fsmeta.OperationPlan{Kind: fsmeta.OperationReadSession, Mount: mount.MountID, PrimaryKey: cloneBytes(key), ReadKeys: [][]byte{cloneBytes(key)}, ReadPrefixes: emptyKeySet, MutateKeys: emptyKeySet}, Authority: AuthorityPlan{Scope: scopeFor(mount, nil, []fsmeta.InodeID{inode}), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(key))}, Key: cloneBytes(key)}, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func CompileReadSessionOwnerProgram(mount fsmeta.MountIdentity, inode fsmeta.InodeID) (ReadProgram, error) {\n")
	b.WriteString("\tkey, err := fsmeta.EncodeInodeSessionKey(mount, inode)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn ReadProgram{}, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tref := keyRef(KeyAccessRead, key)\n")
	b.WriteString("\treturn ReadProgram{Kind: ReadProgramReadSession, Plan: fsmeta.OperationPlan{Kind: fsmeta.OperationReadSession, Mount: mount.MountID, PrimaryKey: cloneBytes(key), ReadKeys: [][]byte{cloneBytes(key)}, ReadPrefixes: emptyKeySet, MutateKeys: emptyKeySet}, Authority: AuthorityPlan{Scope: scopeFor(mount, nil, []fsmeta.InodeID{inode}), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(key))}, Key: cloneBytes(key)}, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func CompileReadSessionKeyProgram(mount fsmeta.MountIdentity, key []byte) (ReadProgram, error) {\n")
	b.WriteString("\tparts, ok := fsmeta.InspectKey(key)\n")
	b.WriteString("\tif !ok || parts.Kind != fsmeta.KeyKindSession || parts.MountKeyID != mount.MountKeyID || parts.Inode == 0 {\n")
	b.WriteString("\t\treturn ReadProgram{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\tref := keyRef(KeyAccessRead, key)\n")
	b.WriteString("\treturn ReadProgram{Kind: ReadProgramReadSession, Plan: fsmeta.OperationPlan{Kind: fsmeta.OperationReadSession, Mount: mount.MountID, PrimaryKey: cloneBytes(key), ReadKeys: [][]byte{cloneBytes(key)}, ReadPrefixes: emptyKeySet, MutateKeys: emptyKeySet}, Authority: AuthorityPlan{Scope: scopeFor(mount, nil, []fsmeta.InodeID{parts.Inode}), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(key))}, Key: cloneBytes(key)}, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func CompileDirectoryReadPlan(req fsmeta.ReadDirRequest, mount fsmeta.MountIdentity, includeOverlay, overlayOnly bool) (DirectoryReadPlan, error) {\n")
	b.WriteString("\tplan, err := fsmeta.PlanReadDir(req, mount)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn DirectoryReadPlan{}, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif len(plan.ReadPrefixes) != 1 {\n")
	b.WriteString("\t\treturn DirectoryReadPlan{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif overlayOnly {\n")
	b.WriteString("\t\tincludeOverlay = true\n")
	b.WriteString("\t}\n")
	b.WriteString("\tref := keyRef(KeyAccessReadPrefix, plan.ReadPrefixes[0])\n")
	b.WriteString("\tsource := DirectoryReadSourceBase\n")
	b.WriteString("\tif overlayOnly {\n")
	b.WriteString("\t\tsource = DirectoryReadSourceOverlayOnly\n")
	b.WriteString("\t} else if includeOverlay {\n")
	b.WriteString("\t\tsource = DirectoryReadSourceOverlay\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn DirectoryReadPlan{Plan: plan, Authority: AuthorityPlan{Scope: scopeFor(mount, []fsmeta.InodeID{req.Parent}, nil), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, HasPrefixRead: true, EstimatedBytes: uint64(len(plan.ReadPrefixes[0]))}, Prefix: cloneBytes(plan.ReadPrefixes[0]), StartKey: cloneBytes(plan.StartKey), Limit: plan.Limit, IncludeOverlay: includeOverlay, OverlayOnly: overlayOnly, Source: source}, nil\n")
	b.WriteString("}\n")
	return b.Bytes(), nil
}

func emitFile(specs []specdsl.OpSpec) ([]byte, error) {
	if len(specs) == 0 {
		return nil, fmt.Errorf("empty spec file")
	}
	if len(specs) == 1 && specs[0].Emitter == "create" {
		return emitCreate(specs[0])
	}
	for _, spec := range specs {
		if spec.Emitter != "operation" {
			return nil, fmt.Errorf("unsupported op spec %q emitter %q", spec.Name, spec.Emitter)
		}
	}
	return emitOperationFile(specs)
}

func emitDispatch(specs []specdsl.OpSpec) ([]byte, error) {
	var b bytes.Buffer
	writeGeneratedHeader(&b)
	b.WriteString("package compile\n\n")
	b.WriteString("import \"github.com/feichai0017/NoKV/fsmeta\"\n\n")
	b.WriteString("func compileAOTDelta(delta SemanticDelta) (CompiledOp, error) {\n")
	b.WriteString("\tswitch delta.Kind {\n")
	for _, spec := range specs {
		if spec.OperationKind == "" {
			return nil, fmt.Errorf("%s missing OperationKind", spec.Name)
		}
		fmt.Fprintf(&b, "\tcase %s:\n", spec.OperationKind)
		fmt.Fprintf(&b, "\t\treturn %s(delta)\n", compiledOpFuncName(spec))
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn CompiledOp{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.Bytes(), nil
}

func emitCreate(spec specdsl.OpSpec) ([]byte, error) {
	if len(spec.Effects) != 3 ||
		spec.Effects[0].ValueName != "ParentInodeValue" ||
		spec.Effects[1].ValueName != "DentryValue" ||
		spec.Effects[2].ValueName != "InodeValue" {
		return nil, fmt.Errorf("create spec must have parent inode, dentry, and inode effects")
	}
	var b bytes.Buffer
	writeGeneratedHeader(&b)
	b.WriteString("package compile\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"crypto/sha256\"\n\n")
	b.WriteString("\t\"github.com/feichai0017/NoKV/fsmeta\"\n")
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "type %s struct {\n\tCompiled CompiledOp\n}\n\n", spec.ProgramType)
	fmt.Fprintf(&b, "type %s struct {\n\tParentInodeValue []byte\n\tDentryValue []byte\n\tInodeValue []byte\n}\n\n", spec.ValuesType)
	fmt.Fprintf(&b, "func %s(req %s, mount fsmeta.MountIdentity, inodeID fsmeta.InodeID, opts ...Option) (%s, error) {\n", spec.CompileName, spec.RequestType, spec.ProgramType)
	b.WriteString("\tif req.Mount != \"\" && req.Mount != mount.MountID {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, fsmeta.ErrInvalidMountID\n", spec.ProgramType)
	b.WriteString("\t}\n")
	b.WriteString("\tparentInodeKey, err := fsmeta.EncodeInodeKey(mount, req.Parent)\n")
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, err\n", spec.ProgramType)
	b.WriteString("\t}\n")
	b.WriteString("\tdentryKey, err := fsmeta.EncodeDentryKey(mount, req.Parent, req.Name)\n")
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, err\n", spec.ProgramType)
	b.WriteString("\t}\n")
	b.WriteString("\tinodeKey, err := fsmeta.EncodeInodeKey(mount, inodeID)\n")
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, err\n", spec.ProgramType)
	b.WriteString("\t}\n")
	b.WriteString("\tplanKeys := [][]byte{parentInodeKey, dentryKey, inodeKey}\n")
	b.WriteString("\tplan := fsmeta.OperationPlan{\n")
	b.WriteString("\t\tKind:       fsmeta.OperationCreate,\n")
	b.WriteString("\t\tMount:      req.Mount,\n")
	b.WriteString("\t\tPrimaryKey: dentryKey,\n")
	b.WriteString("\t\tReadKeys:   planKeys[:3:3],\n")
	b.WriteString("\t\tReadPrefixes: [][]byte{},\n")
	b.WriteString("\t\tMutateKeys: planKeys[:3:3],\n")
	b.WriteString("\t}\n")
	b.WriteString("\tinode := req.Attrs.InodeRecord(inodeID)\n")
	b.WriteString("\tdentry := fsmeta.DentryRecord{Parent: req.Parent, Name: req.Name, Inode: inodeID, Type: inode.Type}\n")
	b.WriteString("\tdentryValue, err := fsmeta.EncodeDentryValue(dentry)\n")
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, err\n", spec.ProgramType)
	b.WriteString("\t}\n")
	b.WriteString("\tinodeValue, err := fsmeta.EncodeInodeValue(inode)\n")
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, err\n", spec.ProgramType)
	b.WriteString("\t}\n")
	b.WriteString("\tparentBucket := fsmeta.BucketForInodeID(req.Parent)\n")
	b.WriteString("\tinodeBucket := fsmeta.BucketForInodeID(inodeID)\n")
	b.WriteString("\tbuckets := []fsmeta.AffinityBucket{parentBucket}\n")
	b.WriteString("\tif inodeBucket != parentBucket {\n")
	b.WriteString("\t\tif inodeBucket < parentBucket {\n")
	b.WriteString("\t\t\tbuckets = []fsmeta.AffinityBucket{inodeBucket, parentBucket}\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tbuckets = []fsmeta.AffinityBucket{parentBucket, inodeBucket}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdelta := SemanticDelta{\n")
	b.WriteString("\t\tKind:      plan.Kind,\n")
	b.WriteString("\t\tPlan:      plan,\n")
	b.WriteString("\t\tAuthority: AuthorityScope{Mount: mount.MountID, MountKeyID: mount.MountKeyID, Buckets: buckets, Parents: []fsmeta.InodeID{req.Parent}, Inodes: []fsmeta.InodeID{inodeID}},\n")
	b.WriteString("\t\tReadPredicates: []Predicate{\n")
	b.WriteString("\t\t\t{Kind: PredicateObservedValue, Key: plan.ReadKeys[0]},\n")
	b.WriteString("\t\t\t{Kind: PredicateNotExists, Key: plan.MutateKeys[1]},\n")
	b.WriteString("\t\t\t{Kind: PredicateNotExists, Key: plan.MutateKeys[2]},\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t\tWriteEffects: []WriteEffect{\n")
	b.WriteString("\t\t\t{Kind: EffectDerivedPut, Key: plan.MutateKeys[0]},\n")
	b.WriteString("\t\t\t{Kind: EffectPut, Key: plan.MutateKeys[1], Value: dentryValue},\n")
	b.WriteString("\t\t\t{Kind: EffectPut, Key: plan.MutateKeys[2], Value: inodeValue},\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t\tEligibility: EligibilityVisibleCommit,\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdelta = applyQuotaPolicy(delta, collectOptions(opts...), GuardQuotaCredit)\n")
	b.WriteString("\tif !validateCreateSemanticDelta(delta) {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, fsmeta.ErrInvalidRequest\n", spec.ProgramType)
	b.WriteString("\t}\n")
	b.WriteString("\tcompiled, err := compileCreateCompiledOp(delta)\n")
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn %s{}, err\n", spec.ProgramType)
	b.WriteString("\t}\n")
	fmt.Fprintf(&b, "\treturn %s{Compiled: compiled}, nil\n", spec.ProgramType)
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "func %s(program %s, values %s) (MaterializedOp, error) {\n", spec.Materialize, spec.ProgramType, spec.ValuesType)
	b.WriteString("\tcompiled := program.Compiled\n")
	b.WriteString("\tif compiled.Delta.Kind != fsmeta.OperationCreate || len(compiled.Delta.ReadPredicates) != 3 || len(compiled.Delta.WriteEffects) != 3 {\n")
	b.WriteString("\t\treturn MaterializedOp{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdelta := compiled.Delta\n")
	b.WriteString("\tif values.ParentInodeValue != nil || values.DentryValue != nil || values.InodeValue != nil {\n")
	b.WriteString("\t\tif values.ParentInodeValue == nil || values.DentryValue == nil || values.InodeValue == nil {\n")
	b.WriteString("\t\t\treturn MaterializedOp{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tdelta.WriteEffects = []WriteEffect{\n")
	b.WriteString("\t\t\t{Kind: EffectPut, Key: delta.WriteEffects[0].Key, Value: values.ParentInodeValue},\n")
	b.WriteString("\t\t\t{Kind: EffectPut, Key: delta.WriteEffects[1].Key, Value: values.DentryValue},\n")
	b.WriteString("\t\t\t{Kind: EffectPut, Key: delta.WriteEffects[2].Key, Value: values.InodeValue},\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdelta.Authority = authorityScopeWithDeltaKeys(delta.Authority, delta)\n")
	b.WriteString("\tmaterialized, err := compileCreateCompiledOp(delta)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn MaterializedOp{}, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tmaterialized.IntentDigest = compiled.IntentDigest\n")
	b.WriteString("\tmaterialized.ReplayDigest = materialized.DescriptorDigest\n")
	b.WriteString("\treturn MaterializedOp{CompiledOp: materialized}, nil\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	if err := emitSemanticDeltaValidator(&b, spec); err != nil {
		return nil, err
	}
	b.WriteString("func compileCreateCompiledOp(delta SemanticDelta) (CompiledOp, error) {\n")
	b.WriteString("\tif delta.Kind != fsmeta.OperationCreate || len(delta.ReadPredicates) != 3 || len(delta.WriteEffects) != 3 {\n")
	b.WriteString("\t\treturn CompiledOp{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdigest := descriptorDigest(delta)\n")
	b.WriteString("\tdurability := DurabilityVisibleOnly\n")
	b.WriteString("\tplacement, dentryParts, inodeParts, err := compileCreatePlacementPlan(delta, durability)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn CompiledOp{}, err\n")
	b.WriteString("\t}\n")
	b.WriteString("\trefs := []KeyRef{\n")
	b.WriteString("\t\tkeyRef(KeyAccessRead, delta.ReadPredicates[0].Key),\n")
	b.WriteString("\t\tkeyRef(KeyAccessRead, delta.ReadPredicates[1].Key),\n")
	b.WriteString("\t\tkeyRef(KeyAccessRead, delta.ReadPredicates[2].Key),\n")
	b.WriteString("\t\tkeyRef(KeyAccessWrite, delta.WriteEffects[0].Key),\n")
	b.WriteString("\t\tkeyRef(KeyAccessWrite, delta.WriteEffects[1].Key),\n")
	b.WriteString("\t\tkeyRef(KeyAccessWrite, delta.WriteEffects[2].Key),\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfootprint := KeyFootprint{\n")
	b.WriteString("\t\tReads:          refs[:3:3],\n")
	b.WriteString("\t\tWrites:         refs[3:6:6],\n")
	b.WriteString("\t\tConflictKeys:   refs[:6:6],\n")
	b.WriteString("\t\tEstimatedBytes: uint64(len(delta.ReadPredicates[0].Key) + len(delta.ReadPredicates[1].Key) + len(delta.ReadPredicates[2].Key) + len(delta.WriteEffects[0].Key) + len(delta.WriteEffects[0].Value) + len(delta.WriteEffects[1].Key) + len(delta.WriteEffects[1].Value) + len(delta.WriteEffects[2].Key) + len(delta.WriteEffects[2].Value)),\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfootprint.HasOpaqueKeys = refs[0].Opaque || refs[1].Opaque || refs[2].Opaque || refs[3].Opaque || refs[4].Opaque || refs[5].Opaque\n")
	b.WriteString("\tparentPredicate := PredicateObligation{Kind: PredicateObservedValue, Key: delta.ReadPredicates[0].Key, NeedValue: true, HasExpectedValue: delta.ReadPredicates[0].HasExpectedValue}\n")
	b.WriteString("\tif delta.ReadPredicates[0].HasExpectedValue {\n")
	b.WriteString("\t\tparentPredicate.ExpectHash = sha256.Sum256(delta.ReadPredicates[0].ExpectedValue)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tpredicates := []PredicateObligation{\n")
	b.WriteString("\t\tparentPredicate,\n")
	b.WriteString("\t\t{Kind: PredicateNotExists, Key: delta.ReadPredicates[1].Key, NeedAbsent: true},\n")
	b.WriteString("\t\t{Kind: PredicateNotExists, Key: delta.ReadPredicates[2].Key, NeedAbsent: true},\n")
	b.WriteString("\t}\n")
	b.WriteString("\tguards := compileCreateGuardObligations(delta.RuntimeGuards)\n")
	b.WriteString("\tparentParts, ok := fsmeta.InspectKey(delta.WriteEffects[0].Key)\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\treturn CompiledOp{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\tparentEffect := EffectPlan{ID: 0, Kind: delta.WriteEffects[0].Kind, Key: delta.WriteEffects[0].Key, Value: delta.WriteEffects[0].Value, Concrete: len(delta.WriteEffects[0].Value) > 0, MountKeyID: parentParts.MountKeyID, Bucket: parentParts.Bucket, RecordKind: parentParts.Kind}\n")
	b.WriteString("\tif len(delta.WriteEffects[0].Value) > 0 {\n")
	b.WriteString("\t\tparentEffect.ValueHash = sha256.Sum256(delta.WriteEffects[0].Value)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif delta.WriteEffects[0].Kind == EffectDerivedPut {\n")
	b.WriteString("\t\tparentEffect.Derivation = DerivationRuntimeValue\n")
	b.WriteString("\t}\n")
	b.WriteString("\teffects := []EffectPlan{\n")
	b.WriteString("\t\tparentEffect,\n")
	b.WriteString("\t\t{ID: 1, Kind: EffectPut, Key: delta.WriteEffects[1].Key, Value: delta.WriteEffects[1].Value, Concrete: true, MountKeyID: dentryParts.MountKeyID, Bucket: dentryParts.Bucket, RecordKind: dentryParts.Kind, ValueHash: sha256.Sum256(delta.WriteEffects[1].Value)},\n")
	b.WriteString("\t\t{ID: 2, Kind: EffectPut, Key: delta.WriteEffects[2].Key, Value: delta.WriteEffects[2].Value, Concrete: true, MountKeyID: inodeParts.MountKeyID, Bucket: inodeParts.Bucket, RecordKind: inodeParts.Kind, ValueHash: sha256.Sum256(delta.WriteEffects[2].Value)},\n")
	b.WriteString("\t}\n")
	b.WriteString("\tatomicity := AtomicityGroup{Members: []MutationID{0, 1, 2}, Recovery: RecoveryReplayAllOrNothing, Digest: digest}\n")
	b.WriteString("\tsegment := compileCreateSegmentPlan(placement, footprint)\n")
	b.WriteString("\treturn CompiledOp{\n")
	b.WriteString("\t\tDelta:            delta,\n")
	b.WriteString("\t\tDescriptorDigest: digest,\n")
	b.WriteString("\t\tIntentDigest:     digest,\n")
	b.WriteString("\t\tReplayDigest:     digest,\n")
	b.WriteString("\t\tAuthority: AuthorityPlan{\n")
	b.WriteString("\t\t\tScope:    delta.Authority,\n")
	b.WriteString("\t\t\tRequired: delta.Eligibility == EligibilityVisibleCommit,\n")
	b.WriteString("\t\t\tFence:    fenceMode(delta),\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t\tPlacement:  placement,\n")
	b.WriteString("\t\tFootprint:  footprint,\n")
	b.WriteString("\t\tPredicates: predicates,\n")
	b.WriteString("\t\tGuards:     guards,\n")
	b.WriteString("\t\tEffects:    effects,\n")
	b.WriteString("\t\tAtomicity:  atomicity,\n")
	b.WriteString("\t\tDurability: durability,\n")
	b.WriteString("\t\tWatch:      compileCreateWatchProjections(delta, dentryParts, inodeParts),\n")
	b.WriteString("\t\tCompletion: compileCreateCompletionPlan(delta, digest),\n")
	b.WriteString("\t\tSegment:    segment,\n")
	b.WriteString("\t}, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func compileCreatePlacementPlan(delta SemanticDelta, durability DurabilityClass) (PlacementPlan, fsmeta.KeyParts, fsmeta.KeyParts, error) {\n")
	b.WriteString("\tplacement := PlacementPlan{MountKeyID: delta.Authority.MountKeyID, Buckets: delta.Authority.Buckets, SlowReason: delta.SlowReason}\n")
	b.WriteString("\tplacement.SingleBucket = len(placement.Buckets) == 1\n")
	b.WriteString("\tif (delta.WriteEffects[0].Kind != EffectPut && delta.WriteEffects[0].Kind != EffectDerivedPut) || delta.WriteEffects[1].Kind != EffectPut || delta.WriteEffects[2].Kind != EffectPut || delta.WriteEffects[1].Value == nil || delta.WriteEffects[2].Value == nil {\n")
	b.WriteString("\t\treturn PlacementPlan{}, fsmeta.KeyParts{}, fsmeta.KeyParts{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdentryParts, ok := fsmeta.InspectKey(delta.WriteEffects[1].Key)\n")
	b.WriteString("\tif !ok || dentryParts.Kind != fsmeta.KeyKindDentry {\n")
	b.WriteString("\t\treturn PlacementPlan{}, fsmeta.KeyParts{}, fsmeta.KeyParts{}, fsmeta.ErrInvalidKey\n")
	b.WriteString("\t}\n")
	b.WriteString("\tinodeParts, ok := fsmeta.InspectKey(delta.WriteEffects[2].Key)\n")
	b.WriteString("\tif !ok || inodeParts.Kind != fsmeta.KeyKindInode {\n")
	b.WriteString("\t\treturn PlacementPlan{}, fsmeta.KeyParts{}, fsmeta.KeyParts{}, fsmeta.ErrInvalidKey\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif dentryParts.MountKeyID != inodeParts.MountKeyID {\n")
	b.WriteString("\t\treturn PlacementPlan{}, fsmeta.KeyParts{}, fsmeta.KeyParts{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif delta.Eligibility != EligibilityVisibleCommit || delta.DurabilityBarrier {\n")
	b.WriteString("\t\treturn placement, dentryParts, inodeParts, nil\n")
	b.WriteString("\t}\n")
	b.WriteString("\tplacement.MountKeyID = dentryParts.MountKeyID\n")
	b.WriteString("\tplacement.SingleBucket = len(placement.Buckets) == 1\n")
	b.WriteString("\tplacement.CanSegment = true\n")
	b.WriteString("\tplacement.Install = SegmentInstallCatalog\n")
	b.WriteString("\tplacement.MergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, Install: SegmentInstallCatalog, Durability: durability, FormatVersion: segmentFormatVersion}\n")
	b.WriteString("\treturn placement, dentryParts, inodeParts, nil\n")
	b.WriteString("}\n\n")
	b.WriteString("func compileCreateGuardObligations(guards []RuntimeGuard) []GuardObligation {\n")
	b.WriteString("\tout := make([]GuardObligation, 0, len(guards))\n")
	b.WriteString("\tfor _, guard := range guards {\n")
	b.WriteString("\t\tout = append(out, GuardObligation{Guard: guard, Digest: GuardObligationDigest(guard)})\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn out\n")
	b.WriteString("}\n\n")
	b.WriteString("func compileCreateSegmentPlan(placement PlacementPlan, footprint KeyFootprint) SegmentPlan {\n")
	b.WriteString("\tsegment := SegmentPlan{MergeKey: placement.MergeKey, Install: placement.Install, CanAppend: placement.CanSegment, RequiresMaterialize: placement.RequiresMaterialize, EstimatedPayloadBytes: footprint.EstimatedBytes, OperationCount: 1, MutationCount: 3}\n")
	b.WriteString("\tswitch {\n")
	b.WriteString("\tcase placement.Install == SegmentInstallCatalog && placement.SingleBucket && len(placement.Buckets) == 1:\n")
	b.WriteString("\t\tsegment.CanMaterialize = placement.CanSegment\n")
	b.WriteString("\t\tsegment.MaterializeInstall = SegmentInstallSingleBucket\n")
	b.WriteString("\t\tsegment.MaterializeMergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, HasPrimaryBucket: true, PrimaryBucket: placement.Buckets[0], Install: SegmentInstallSingleBucket, Durability: placement.MergeKey.Durability, FormatVersion: placement.MergeKey.FormatVersion}\n")
	b.WriteString("\tcase placement.Install == SegmentInstallCatalog && placement.CanSegment:\n")
	b.WriteString("\t\t// Multi-bucket catalog op (dentry + inode in different buckets is the\n")
	b.WriteString("\t\t// common case). Materialize is safe because installer writes each\n")
	b.WriteString("\t\t// entry as a direct MVCC mutation. Local fsmeta consumes this path\n")
	b.WriteString("\t\t// when its installer materializes segments; distributed installers do not.\n")
	b.WriteString("\t\tsegment.CanMaterialize = placement.CanSegment\n")
	b.WriteString("\t\tsegment.MaterializeInstall = SegmentInstallSingleBucket\n")
	b.WriteString("\t\tsegment.MaterializeMergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, Install: SegmentInstallSingleBucket, Durability: placement.MergeKey.Durability, FormatVersion: placement.MergeKey.FormatVersion}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn segment\n")
	b.WriteString("}\n\n")
	b.WriteString("func compileCreateCompletionPlan(delta SemanticDelta, digest [32]byte) CompletionPlan {\n")
	b.WriteString("\tif delta.Eligibility != EligibilityVisibleCommit {\n")
	b.WriteString("\t\treturn CompletionPlan{}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn CompletionPlan{RetainCompletion: true, Kind: CompletionVisible, MutationCount: 3, DescriptorDigest: digest}\n")
	b.WriteString("}\n\n")
	b.WriteString("func compileCreateWatchProjections(delta SemanticDelta, dentryParts fsmeta.KeyParts, inodeParts fsmeta.KeyParts) []WatchProjection {\n")
	b.WriteString("\treturn []WatchProjection{{EventKind: WatchEventCreate, Key: delta.WriteEffects[1].Key, Parent: dentryParts.Parent, Name: dentryName(delta.WriteEffects[1].Key), Inode: inodeParts.Inode, EmitAt: WatchEmitVisible}}\n")
	b.WriteString("}\n")
	return b.Bytes(), nil
}

func emitOperationFile(specs []specdsl.OpSpec) ([]byte, error) {
	var b bytes.Buffer
	writeGeneratedHeader(&b)
	b.WriteString("package compile\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"crypto/sha256\"\n\n")
	b.WriteString("\t\"github.com/feichai0017/NoKV/fsmeta\"\n")
	if operationFileNeedsProof(specs) {
		b.WriteString("\t\"github.com/feichai0017/NoKV/fsmeta/proof\"\n")
	}
	b.WriteString(")\n\n")
	for _, spec := range specs {
		if spec.ProgramType == "" {
			return nil, fmt.Errorf("%s missing ProgramType", spec.Name)
		}
		fmt.Fprintf(&b, "type %s struct {\n\tCompiled CompiledOp\n}\n\n", spec.ProgramType)
	}
	for _, spec := range specs {
		if err := emitValuesType(&b, spec); err != nil {
			return nil, err
		}
	}
	for _, spec := range specs {
		if err := emitCompileEntry(&b, spec); err != nil {
			return nil, err
		}
	}
	for _, spec := range specs {
		if err := emitSemanticDeltaValidator(&b, spec); err != nil {
			return nil, err
		}
	}
	for _, spec := range specs {
		if err := emitCompiledOpFunction(&b, spec); err != nil {
			return nil, err
		}
	}
	for _, spec := range specs {
		if err := emitMaterializer(&b, spec); err != nil {
			return nil, err
		}
	}
	return b.Bytes(), nil
}

func writeGeneratedHeader(b *bytes.Buffer) {
	b.WriteString("// Copyright 2024-2026 The NoKV Authors.\n")
	b.WriteString("// SPDX-License-Identifier: Apache-2.0\n\n")
	b.WriteString("// Code generated by fsmeta-opgen; DO NOT EDIT.\n\n")
}

func emitValuesType(b *bytes.Buffer, spec specdsl.OpSpec) error {
	switch spec.Materializer {
	case "":
		return nil
	case "session_put":
		fmt.Fprintf(b, "type %s struct {\n\tSessionValue []byte\n\tPredicateProofs []proof.PredicateProof\n}\n\n", spec.ValuesType)
	case "session_close":
		fmt.Fprintf(b, "type %s struct {\n\tDeleteOwner bool\n\tPredicateProofs []proof.PredicateProof\n}\n\n", spec.ValuesType)
	default:
		return fmt.Errorf("unsupported materializer %q for %s", spec.Materializer, spec.Name)
	}
	return nil
}

func operationFileNeedsProof(specs []specdsl.OpSpec) bool {
	for _, spec := range specs {
		switch spec.Materializer {
		case "session_put", "session_close":
			return true
		}
	}
	return false
}

func emitCompileEntry(b *bytes.Buffer, spec specdsl.OpSpec) error {
	if spec.CompileName == "" || spec.RequestType == "" || spec.PlanName == "" {
		return fmt.Errorf("%s missing compile entry fields", spec.Name)
	}
	if spec.HasOptions {
		fmt.Fprintf(b, "func %s(req %s, mount fsmeta.MountIdentity, opts ...Option) (%s, error) {\n", spec.CompileName, spec.RequestType, spec.ProgramType)
		b.WriteString("\toptions := collectOptions(opts...)\n")
	} else {
		fmt.Fprintf(b, "func %s(req %s, mount fsmeta.MountIdentity) (%s, error) {\n", spec.CompileName, spec.RequestType, spec.ProgramType)
	}
	for _, check := range spec.RequestChecks {
		if err := emitRequestCheck(b, spec, check); err != nil {
			return err
		}
	}
	fmt.Fprintf(b, "\tplan, err := %s(req, mount)\n", spec.PlanName)
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(b, "\t\treturn %s{}, err\n", spec.ProgramType)
	b.WriteString("\t}\n")
	b.WriteString("\tplan = canonicalPlan(plan)\n")
	if specUsesKeyBinding(spec, "owner") {
		b.WriteString("\townerKey, err := fsmeta.EncodeInodeSessionKey(mount, req.Inode)\n")
		b.WriteString("\tif err != nil {\n")
		fmt.Fprintf(b, "\t\treturn %s{}, err\n", spec.ProgramType)
		b.WriteString("\t}\n")
	}
	if err := emitPredicatePlan(b, spec); err != nil {
		return err
	}
	if err := emitEffectPlan(b, spec); err != nil {
		return err
	}
	parents := requestInodeExprs(spec.Authority.Parents)
	inodes := requestInodeExprs(spec.Authority.Inodes)
	fmt.Fprintf(b, "\tdelta := SemanticDelta{Kind: plan.Kind, Plan: plan, Authority: scopeFor(mount, %s, %s), ReadPredicates: predicates, WriteEffects: effects, Eligibility: %s", inodeSliceExpr(parents), inodeSliceExpr(inodes), spec.Eligibility)
	if spec.SlowReason != "" {
		fmt.Fprintf(b, ", SlowReason: %s", spec.SlowReason)
	}
	if spec.DurabilityBarrier {
		b.WriteString(", DurabilityBarrier: true")
	}
	if spec.WatchAtSeal {
		b.WriteString(", WatchAtSeal: true")
	}
	b.WriteString("}\n")
	if len(spec.Guards) > 0 {
		b.WriteString("\tdelta.RuntimeGuards = append(delta.RuntimeGuards")
		for _, guard := range spec.Guards {
			fmt.Fprintf(b, ", %s", guard.Guard)
		}
		b.WriteString(")\n")
	}
	if spec.HasOptions {
		for _, guard := range spec.OptionalGuards {
			if guard.Condition == "quota_escrow" {
				fmt.Fprintf(b, "\tdelta = applyQuotaPolicy(delta, options, %s)\n", guard.Guard)
			}
		}
	}
	if hasSlowFallback(spec, "SlowReasonCrossBucket") {
		b.WriteString("\tif len(delta.Authority.Buckets) > 1 {\n")
		b.WriteString("\t\tdelta.Eligibility = EligibilitySlowPath\n")
		b.WriteString("\t\tdelta.SlowReason = SlowReasonCrossBucket\n")
		b.WriteString("\t}\n")
	}
	fmt.Fprintf(b, "\tif !%s(delta) {\n", semanticDeltaValidatorName(spec))
	fmt.Fprintf(b, "\t\treturn %s{}, fsmeta.ErrInvalidRequest\n", spec.ProgramType)
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\tcompiled, err := %s(delta)\n", compiledOpFuncName(spec))
	b.WriteString("\tif err != nil {\n")
	fmt.Fprintf(b, "\t\treturn %s{}, err\n", spec.ProgramType)
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\treturn %s{Compiled: compiled}, nil\n", spec.ProgramType)
	b.WriteString("}\n\n")
	return nil
}

func emitRequestCheck(b *bytes.Buffer, spec specdsl.OpSpec, check string) error {
	switch check {
	case "inode_update_has_mutation":
		b.WriteString("\tif !req.SetSize && !req.SetMode && !req.SetUpdatedUnixNs && !req.SetOpaqueAttrs {\n")
		fmt.Fprintf(b, "\t\treturn %s{}, fsmeta.ErrInvalidRequest\n", spec.ProgramType)
		b.WriteString("\t}\n")
	case "positive_ttl":
		b.WriteString("\tif req.TTL <= 0 {\n")
		fmt.Fprintf(b, "\t\treturn %s{}, fsmeta.ErrInvalidRequest\n", spec.ProgramType)
		b.WriteString("\t}\n")
	default:
		return fmt.Errorf("%s unknown request check %q", spec.Name, check)
	}
	return nil
}

func emitPredicatePlan(b *bytes.Buffer, spec specdsl.OpSpec) error {
	repeatable := -1
	for i, predicate := range spec.Predicates {
		if predicate.Repeatable {
			repeatable = i
		}
	}
	if repeatable >= 0 {
		if len(spec.Predicates) != 1 {
			return fmt.Errorf("%s repeatable predicate specs must be the only predicate", spec.Name)
		}
		predicate := spec.Predicates[repeatable]
		family := repeatableBindingFamily(predicate.Key)
		switch family {
		case "read_prefix":
			b.WriteString("\tpredicates := make([]Predicate, 0, len(plan.ReadPrefixes))\n")
			b.WriteString("\tfor _, key := range plan.ReadPrefixes {\n")
		case "read":
			b.WriteString("\tpredicates := make([]Predicate, 0, len(plan.ReadKeys))\n")
			b.WriteString("\tfor _, key := range plan.ReadKeys {\n")
		default:
			return fmt.Errorf("%s unsupported repeatable predicate binding %q", spec.Name, predicate.Key)
		}
		fmt.Fprintf(b, "\t\tpredicates = append(predicates, Predicate{Kind: %s, Key: key})\n", predicate.Kind)
		b.WriteString("\t}\n")
		return nil
	}
	if len(spec.Predicates) == 0 {
		b.WriteString("\tpredicates := []Predicate(nil)\n")
		return nil
	}
	b.WriteString("\tpredicates := []Predicate{\n")
	for _, predicate := range spec.Predicates {
		key, err := keyBindingExpr(predicate.Key)
		if err != nil {
			return fmt.Errorf("%s predicate %s: %w", spec.Name, predicate.Name, err)
		}
		fmt.Fprintf(b, "\t\t{Kind: %s", predicate.Kind)
		if key != "" {
			fmt.Fprintf(b, ", Key: %s", key)
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n")
	return nil
}

func emitEffectPlan(b *bytes.Buffer, spec specdsl.OpSpec) error {
	if len(spec.Effects) == 0 {
		b.WriteString("\teffects := []WriteEffect(nil)\n")
		return nil
	}
	b.WriteString("\teffects := []WriteEffect{\n")
	for _, effect := range spec.Effects {
		key, err := keyBindingExpr(effect.Key)
		if err != nil {
			return fmt.Errorf("%s effect %s: %w", spec.Name, effect.Name, err)
		}
		fmt.Fprintf(b, "\t\t{Kind: %s", effect.Kind)
		if key != "" {
			fmt.Fprintf(b, ", Key: %s", key)
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n")
	return nil
}

func keyBindingExpr(binding string) (string, error) {
	switch binding {
	case "", "runtime":
		return "", nil
	case "primary":
		return "plan.PrimaryKey", nil
	case "owner":
		return "ownerKey", nil
	}
	if prefix, ok := strings.CutSuffix(binding, "]"); ok {
		name, indexText, ok := strings.Cut(prefix, "[")
		if !ok {
			return "", fmt.Errorf("invalid key binding %q", binding)
		}
		switch name {
		case "read":
			return "plan.ReadKeys[" + indexText + "]", nil
		case "read_prefix":
			return "plan.ReadPrefixes[" + indexText + "]", nil
		case "mutate":
			return "plan.MutateKeys[" + indexText + "]", nil
		case "predicate":
			return "predicates[" + indexText + "].Key", nil
		default:
			return "", fmt.Errorf("invalid key binding %q", binding)
		}
	}
	return "", fmt.Errorf("invalid key binding %q", binding)
}

func requestInodeExprs(names []string) []string {
	out := make([]string, 0, len(names))
	for _, name := range names {
		switch name {
		case "parent":
			out = append(out, "req.Parent")
		case "from_parent":
			out = append(out, "req.FromParent")
		case "to_parent":
			out = append(out, "req.ToParent")
		case "root":
			out = append(out, "req.RootInode")
		case "inode":
			out = append(out, "req.Inode")
		}
	}
	return out
}

func inodeSliceExpr(exprs []string) string {
	if len(exprs) == 0 {
		return "nil"
	}
	return "[]fsmeta.InodeID{" + strings.Join(exprs, ", ") + "}"
}

func specUsesKeyBinding(spec specdsl.OpSpec, binding string) bool {
	for _, predicate := range spec.Predicates {
		if predicate.Key == binding {
			return true
		}
	}
	for _, effect := range spec.Effects {
		if effect.Key == binding {
			return true
		}
	}
	return false
}

func hasSlowFallback(spec specdsl.OpSpec, reason string) bool {
	return slices.Contains(spec.SlowFallbacks, reason)
}

func emitSemanticDeltaValidator(b *bytes.Buffer, spec specdsl.OpSpec) error {
	if spec.OperationKind == "" || spec.Eligibility == "" {
		return fmt.Errorf("%s missing semantic validator fields", spec.Name)
	}
	repeatablePredicate := -1
	for i, predicate := range spec.Predicates {
		if predicate.Repeatable {
			repeatablePredicate = i
		}
	}
	if repeatablePredicate >= 0 && len(spec.Predicates) != 1 {
		return fmt.Errorf("%s repeatable predicate specs must be the only predicate", spec.Name)
	}

	fmt.Fprintf(b, "func %s(delta SemanticDelta) bool {\n", semanticDeltaValidatorName(spec))
	fmt.Fprintf(b, "\tif delta.Kind != %s {\n", spec.OperationKind)
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	emitEligibilityValidator(b, spec)
	emitBoolValidator(b, "delta.DurabilityBarrier", spec.DurabilityBarrier)
	emitBoolValidator(b, "delta.WatchAtSeal", spec.WatchAtSeal)
	emitAuthorityCountValidator(b, "Parents", len(spec.Authority.Parents))
	emitAuthorityCountValidator(b, "Inodes", len(spec.Authority.Inodes))
	emitBoolValidator(b, "delta.Authority.Broad", spec.Authority.Broad)
	emitBoolValidator(b, "delta.Authority.AllowOpaqueKeys", spec.Authority.AllowOpaqueKeys)

	if repeatablePredicate >= 0 {
		predicate := spec.Predicates[repeatablePredicate]
		fmt.Fprintf(b, "\tif len(delta.ReadPredicates) == 0 {\n")
		b.WriteString("\t\treturn false\n")
		b.WriteString("\t}\n")
		b.WriteString("\tfor i, predicate := range delta.ReadPredicates {\n")
		fmt.Fprintf(b, "\t\tif predicate.Kind != %s {\n", predicate.Kind)
		b.WriteString("\t\t\treturn false\n")
		b.WriteString("\t\t}\n")
		if predicate.Key != "" {
			fmt.Fprintf(b, "\t\tif !semanticIndexedKeyBindingMatches(delta, predicate.Key, %q, i) {\n", repeatableBindingFamily(predicate.Key))
			b.WriteString("\t\t\treturn false\n")
			b.WriteString("\t\t}\n")
		}
		b.WriteString("\t}\n")
	} else {
		if spec.PredicateCount >= 0 {
			fmt.Fprintf(b, "\tif len(delta.ReadPredicates) != %d {\n", len(spec.Predicates))
			b.WriteString("\t\treturn false\n")
			b.WriteString("\t}\n")
		} else {
			fmt.Fprintf(b, "\tif len(delta.ReadPredicates) < %d {\n", len(spec.Predicates))
			b.WriteString("\t\treturn false\n")
			b.WriteString("\t}\n")
		}
		for i, predicate := range spec.Predicates {
			fmt.Fprintf(b, "\tif delta.ReadPredicates[%d].Kind != %s {\n", i, predicate.Kind)
			b.WriteString("\t\treturn false\n")
			b.WriteString("\t}\n")
			if predicate.Key != "" {
				fmt.Fprintf(b, "\tif !semanticKeyBindingMatches(delta, delta.ReadPredicates[%d].Key, %q) {\n", i, predicate.Key)
				b.WriteString("\t\treturn false\n")
				b.WriteString("\t}\n")
			}
		}
	}

	fmt.Fprintf(b, "\tif len(delta.WriteEffects) != %d {\n", len(spec.Effects))
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	for i, effect := range spec.Effects {
		fmt.Fprintf(b, "\tif delta.WriteEffects[%d].Kind != %s {\n", i, effect.Kind)
		b.WriteString("\t\treturn false\n")
		b.WriteString("\t}\n")
		if effect.Key != "" {
			fmt.Fprintf(b, "\tif !semanticKeyBindingMatches(delta, delta.WriteEffects[%d].Key, %q) {\n", i, effect.Key)
			b.WriteString("\t\treturn false\n")
			b.WriteString("\t}\n")
		}
	}

	requiredGuards := len(spec.Guards)
	optionalGuards := len(spec.OptionalGuards)
	switch {
	case requiredGuards == 0 && optionalGuards == 0:
		b.WriteString("\tif len(delta.RuntimeGuards) != 0 {\n")
	case requiredGuards == 0:
		fmt.Fprintf(b, "\tif len(delta.RuntimeGuards) > %d {\n", optionalGuards)
	case optionalGuards == 0:
		fmt.Fprintf(b, "\tif len(delta.RuntimeGuards) != %d {\n", requiredGuards)
	default:
		fmt.Fprintf(b, "\tif len(delta.RuntimeGuards) < %d || len(delta.RuntimeGuards) > %d {\n", requiredGuards, requiredGuards+optionalGuards)
	}
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	for i, guard := range spec.Guards {
		fmt.Fprintf(b, "\tif delta.RuntimeGuards[%d] != %s {\n", i, guard.Guard)
		b.WriteString("\t\treturn false\n")
		b.WriteString("\t}\n")
	}
	if optionalGuards > 0 {
		if requiredGuards == 0 {
			b.WriteString("\tfor _, guard := range delta.RuntimeGuards {\n")
		} else {
			fmt.Fprintf(b, "\tfor _, guard := range delta.RuntimeGuards[%d:] {\n", requiredGuards)
		}
		b.WriteString("\t\tswitch guard {\n")
		for _, guard := range spec.OptionalGuards {
			fmt.Fprintf(b, "\t\tcase %s:\n", guard.Guard)
		}
		b.WriteString("\t\tdefault:\n")
		b.WriteString("\t\t\treturn false\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
	}

	b.WriteString("\treturn true\n")
	b.WriteString("}\n\n")
	return nil
}

func emitAuthorityCountValidator(b *bytes.Buffer, field string, declared int) {
	if declared == 0 {
		fmt.Fprintf(b, "\tif len(delta.Authority.%s) != 0 {\n", field)
	} else {
		fmt.Fprintf(b, "\tif len(delta.Authority.%s) == 0 || len(delta.Authority.%s) > %d {\n", field, field, declared)
	}
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
}

func emitBoolValidator(b *bytes.Buffer, expr string, want bool) {
	if want {
		fmt.Fprintf(b, "\tif !%s {\n", expr)
	} else {
		fmt.Fprintf(b, "\tif %s {\n", expr)
	}
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
}

func repeatableBindingFamily(binding string) string {
	if prefix, _, ok := strings.Cut(binding, "["); ok {
		return prefix
	}
	return binding
}

func emitEligibilityValidator(b *bytes.Buffer, spec specdsl.OpSpec) {
	slowReason := spec.SlowReason
	if slowReason == "" {
		slowReason = "SlowReasonNone"
	}
	b.WriteString("\tswitch {\n")
	fmt.Fprintf(b, "\tcase delta.Eligibility == %s && delta.SlowReason == %s:\n", spec.Eligibility, slowReason)
	for _, fallback := range spec.SlowFallbacks {
		fmt.Fprintf(b, "\tcase delta.Eligibility == EligibilitySlowPath && delta.SlowReason == %s:\n", fallback)
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
}

func semanticDeltaValidatorName(spec specdsl.OpSpec) string {
	if spec.Name == "" {
		return ""
	}
	return "validate" + spec.Name + "SemanticDelta"
}

func emitCompiledOpFunction(b *bytes.Buffer, spec specdsl.OpSpec) error {
	if spec.OperationKind == "" || spec.Durability == "" {
		return fmt.Errorf("%s missing AOT compile fields", spec.Name)
	}
	fmt.Fprintf(b, "func %s(delta SemanticDelta) (CompiledOp, error) {\n", compiledOpFuncName(spec))
	fmt.Fprintf(b, "\tif delta.Kind != %s", spec.OperationKind)
	if spec.PredicateCount >= 0 {
		fmt.Fprintf(b, " || len(delta.ReadPredicates) != %d", spec.PredicateCount)
	}
	if spec.EffectCount >= 0 {
		fmt.Fprintf(b, " || len(delta.WriteEffects) != %d", spec.EffectCount)
	}
	b.WriteString(" {\n")
	b.WriteString("\t\treturn CompiledOp{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdigest := descriptorDigest(delta)\n")
	fmt.Fprintf(b, "\tdurability := %s\n", spec.Durability)
	emitAOTCompiledOpBody(b)
	return nil
}

func emitAOTCompiledOpBody(b *bytes.Buffer) {
	b.WriteString("\tplacement := PlacementPlan{MountKeyID: delta.Authority.MountKeyID, Buckets: delta.Authority.Buckets, SlowReason: delta.SlowReason}\n")
	b.WriteString("\tplacement.SingleBucket = len(placement.Buckets) == 1\n")
	b.WriteString("\tif delta.Eligibility == EligibilityVisibleCommit && !delta.DurabilityBarrier && len(delta.WriteEffects) > 0 {\n")
	b.WriteString("\t\tvar mount fsmeta.MountKeyID\n")
	b.WriteString("\t\tvar fsmetaKeys bool\n")
	b.WriteString("\t\tvar opaqueKeys bool\n")
	b.WriteString("\t\tbuckets := make([]fsmeta.AffinityBucket, 0, len(delta.WriteEffects))\n")
	b.WriteString("\t\tfor _, effect := range delta.WriteEffects {\n")
	b.WriteString("\t\t\tswitch effect.Kind {\n")
	b.WriteString("\t\t\tcase EffectPut:\n")
	b.WriteString("\t\t\t\tif len(effect.Key) == 0 || effect.Value == nil {\n")
	b.WriteString("\t\t\t\t\tplacement.RequiresMaterialize = true\n")
	b.WriteString("\t\t\t\t\tgoto placementDone\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\tcase EffectDelete:\n")
	b.WriteString("\t\t\t\tif len(effect.Key) == 0 {\n")
	b.WriteString("\t\t\t\t\tplacement.RequiresMaterialize = true\n")
	b.WriteString("\t\t\t\t\tgoto placementDone\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\tcase EffectDerivedPut, EffectDerivedDelete:\n")
	b.WriteString("\t\t\t\tplacement.RequiresMaterialize = true\n")
	b.WriteString("\t\t\t\tgoto placementDone\n")
	b.WriteString("\t\t\tdefault:\n")
	b.WriteString("\t\t\t\tplacement.SlowReason = SlowReasonDynamicWriteSet\n")
	b.WriteString("\t\t\t\tgoto placementDone\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tparts, ok := fsmeta.InspectKey(effect.Key)\n")
	b.WriteString("\t\t\tif !ok {\n")
	b.WriteString("\t\t\t\tif fsmetaKeys {\n")
	b.WriteString("\t\t\t\t\tplacement.SlowReason = SlowReasonDynamicWriteSet\n")
	b.WriteString("\t\t\t\t\tgoto placementDone\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\topaqueKeys = true\n")
	b.WriteString("\t\t\t\tcontinue\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tif opaqueKeys {\n")
	b.WriteString("\t\t\t\tplacement.SlowReason = SlowReasonDynamicWriteSet\n")
	b.WriteString("\t\t\t\tgoto placementDone\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tif !fsmetaKeys {\n")
	b.WriteString("\t\t\t\tmount = parts.MountKeyID\n")
	b.WriteString("\t\t\t\tfsmetaKeys = true\n")
	b.WriteString("\t\t\t} else if mount != parts.MountKeyID {\n")
	b.WriteString("\t\t\t\tplacement.SlowReason = SlowReasonCrossBucket\n")
	b.WriteString("\t\t\t\tgoto placementDone\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tbuckets = append(buckets, parts.Bucket)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tif fsmetaKeys {\n")
	b.WriteString("\t\t\tplacement.MountKeyID = mount\n")
	b.WriteString("\t\t\tplacement.Buckets = uniqueBuckets(buckets)\n")
	b.WriteString("\t\t\tplacement.SingleBucket = len(placement.Buckets) == 1\n")
	b.WriteString("\t\t\tplacement.CanSegment = true\n")
	b.WriteString("\t\t\tplacement.Install = SegmentInstallCatalog\n")
	b.WriteString("\t\t\tplacement.MergeKey = SegmentMergeKey{MountKeyID: mount, Install: placement.Install, Durability: durability, FormatVersion: segmentFormatVersion}\n")
	b.WriteString("\t\t} else if opaqueKeys {\n")
	b.WriteString("\t\t\tplacement.CanSegment = true\n")
	b.WriteString("\t\t\tplacement.Install = SegmentInstallSingleBucket\n")
	b.WriteString("\t\t\tplacement.MergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, Install: placement.Install, Durability: durability, FormatVersion: segmentFormatVersion}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("placementDone:\n")
	b.WriteString("\tfootprint := KeyFootprint{Reads: make([]KeyRef, 0, len(delta.ReadPredicates)), Writes: make([]KeyRef, 0, len(delta.WriteEffects)), ConflictKeys: make([]KeyRef, 0, len(delta.ReadPredicates)+len(delta.WriteEffects))}\n")
	b.WriteString("\tfor _, predicate := range delta.ReadPredicates {\n")
	b.WriteString("\t\tmode := KeyAccessRead\n")
	b.WriteString("\t\tif predicate.Kind == PredicatePrefixScan {\n")
	b.WriteString("\t\t\tmode = KeyAccessReadPrefix\n")
	b.WriteString("\t\t\tfootprint.HasPrefixRead = true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tref := keyRef(mode, predicate.Key)\n")
	b.WriteString("\t\tfootprint.Reads = append(footprint.Reads, ref)\n")
	b.WriteString("\t\tfootprint.ConflictKeys = append(footprint.ConflictKeys, ref)\n")
	b.WriteString("\t\tfootprint.EstimatedBytes += uint64(len(predicate.Key) + len(predicate.ExpectedValue))\n")
	b.WriteString("\t\tif ref.Opaque {\n")
	b.WriteString("\t\t\tfootprint.HasOpaqueKeys = true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfor _, effect := range delta.WriteEffects {\n")
	b.WriteString("\t\tref := keyRef(KeyAccessWrite, effect.Key)\n")
	b.WriteString("\t\tfootprint.Writes = append(footprint.Writes, ref)\n")
	b.WriteString("\t\tfootprint.ConflictKeys = append(footprint.ConflictKeys, ref)\n")
	b.WriteString("\t\tfootprint.EstimatedBytes += uint64(len(effect.Key) + len(effect.Value))\n")
	b.WriteString("\t\tif ref.Opaque {\n")
	b.WriteString("\t\t\tfootprint.HasOpaqueKeys = true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tpredicates := make([]PredicateObligation, 0, len(delta.ReadPredicates))\n")
	b.WriteString("\tfor _, predicate := range delta.ReadPredicates {\n")
	b.WriteString("\t\tobligation := PredicateObligation{Kind: predicate.Kind, Key: predicate.Key, HasExpectedValue: predicate.HasExpectedValue}\n")
	b.WriteString("\t\tif predicate.HasExpectedValue {\n")
	b.WriteString("\t\t\tobligation.ExpectHash = sha256.Sum256(predicate.ExpectedValue)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tswitch predicate.Kind {\n")
	b.WriteString("\t\tcase PredicateExists:\n")
	b.WriteString("\t\t\tobligation.NeedValue = true\n")
	b.WriteString("\t\tcase PredicateNotExists:\n")
	b.WriteString("\t\t\tobligation.NeedAbsent = true\n")
	b.WriteString("\t\tcase PredicateObservedValue:\n")
	b.WriteString("\t\t\tobligation.NeedValue = true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tpredicates = append(predicates, obligation)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tguards := make([]GuardObligation, 0, len(delta.RuntimeGuards))\n")
	b.WriteString("\tfor _, guard := range delta.RuntimeGuards {\n")
	b.WriteString("\t\tguards = append(guards, GuardObligation{Guard: guard, Digest: GuardObligationDigest(guard)})\n")
	b.WriteString("\t}\n")
	b.WriteString("\teffects := make([]EffectPlan, 0, len(delta.WriteEffects))\n")
	b.WriteString("\tfor i, effect := range delta.WriteEffects {\n")
	b.WriteString("\t\tplan := EffectPlan{ID: MutationID(i), Kind: effect.Kind, Key: effect.Key, Value: effect.Value, Concrete: effect.Kind == EffectPut || effect.Kind == EffectDelete}\n")
	b.WriteString("\t\tif len(effect.Value) > 0 {\n")
	b.WriteString("\t\t\tplan.ValueHash = sha256.Sum256(effect.Value)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tif parts, ok := fsmeta.InspectKey(effect.Key); ok {\n")
	b.WriteString("\t\t\tplan.MountKeyID = parts.MountKeyID\n")
	b.WriteString("\t\t\tplan.Bucket = parts.Bucket\n")
	b.WriteString("\t\t\tplan.RecordKind = parts.Kind\n")
	b.WriteString("\t\t} else if len(effect.Key) > 0 {\n")
	b.WriteString("\t\t\tplan.Opaque = true\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tswitch effect.Kind {\n")
	b.WriteString("\t\tcase EffectDerivedPut, EffectDerivedDelete:\n")
	b.WriteString("\t\t\tplan.Derivation = DerivationRuntimeValue\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\teffects = append(effects, plan)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tatomicity := AtomicityGroup{Members: make([]MutationID, 0, len(delta.WriteEffects)), Recovery: RecoveryReplayAllOrNothing, Digest: digest}\n")
	b.WriteString("\tfor i := range delta.WriteEffects {\n")
	b.WriteString("\t\tatomicity.Members = append(atomicity.Members, MutationID(i))\n")
	b.WriteString("\t}\n")
	b.WriteString("\tatomicity.Splittable = len(atomicity.Members) <= 1\n")
	b.WriteString("\tsegment := SegmentPlan{MergeKey: placement.MergeKey, Install: placement.Install, CanAppend: placement.CanSegment, RequiresMaterialize: placement.RequiresMaterialize, EstimatedPayloadBytes: footprint.EstimatedBytes, OperationCount: 1, MutationCount: uint32(len(effects))}\n")
	b.WriteString("\tswitch {\n")
	b.WriteString("\tcase placement.Install == SegmentInstallSingleBucket:\n")
	b.WriteString("\t\tsegment.CanMaterialize = placement.CanSegment\n")
	b.WriteString("\t\tsegment.MaterializeInstall = SegmentInstallSingleBucket\n")
	b.WriteString("\t\tsegment.MaterializeMergeKey = placement.MergeKey\n")
	b.WriteString("\tcase placement.Install == SegmentInstallCatalog && placement.SingleBucket && len(placement.Buckets) == 1:\n")
	b.WriteString("\t\tsegment.CanMaterialize = placement.CanSegment\n")
	b.WriteString("\t\tsegment.MaterializeInstall = SegmentInstallSingleBucket\n")
	b.WriteString("\t\tsegment.MaterializeMergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, HasPrimaryBucket: true, PrimaryBucket: placement.Buckets[0], Install: SegmentInstallSingleBucket, Durability: placement.MergeKey.Durability, FormatVersion: placement.MergeKey.FormatVersion}\n")
	b.WriteString("\tcase placement.Install == SegmentInstallCatalog && placement.CanSegment:\n")
	b.WriteString("\t\t// Multi-bucket catalog op: materialize is still safe because the\n")
	b.WriteString("\t\t// installer writes each entry as a direct MVCC mutation regardless\n")
	b.WriteString("\t\t// of bucket. MergeKey carries no PrimaryBucket so all multi-bucket\n")
	b.WriteString("\t\t// materialize ops batch together in one install. Local fsmeta runtimes\n")
	b.WriteString("\t\t// consume this path when their installer materializes segments;\n")
	b.WriteString("\t\t// distributed runtimes keep catalog install and never enter materialize\n")
	b.WriteString("\t\t// in SegmentPlanForInstall.\n")
	b.WriteString("\t\tsegment.CanMaterialize = placement.CanSegment\n")
	b.WriteString("\t\tsegment.MaterializeInstall = SegmentInstallSingleBucket\n")
	b.WriteString("\t\tsegment.MaterializeMergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, Install: SegmentInstallSingleBucket, Durability: placement.MergeKey.Durability, FormatVersion: placement.MergeKey.FormatVersion}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tcompletion := CompletionPlan{}\n")
	b.WriteString("\tif delta.Eligibility == EligibilityVisibleCommit && len(effects) != 0 {\n")
	b.WriteString("\t\tkind := CompletionVisible\n")
	b.WriteString("\t\tif durability != DurabilityVisibleOnly {\n")
	b.WriteString("\t\t\tkind = CompletionDurable\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tcompletion = CompletionPlan{RetainCompletion: true, Kind: kind, MutationCount: uint32(len(effects)), DescriptorDigest: digest}\n")
	b.WriteString("\t}\n")
	b.WriteString("\twatch := []WatchProjection(nil)\n")
	b.WriteString("\tif len(delta.WriteEffects) > 0 {\n")
	b.WriteString("\t\temitAt := WatchEmitVisible\n")
	b.WriteString("\t\tif delta.WatchAtSeal || delta.DurabilityBarrier {\n")
	b.WriteString("\t\t\temitAt = WatchEmitSeal\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\twatch = make([]WatchProjection, 0, len(delta.WriteEffects))\n")
	b.WriteString("\t\tfor _, effect := range delta.WriteEffects {\n")
	b.WriteString("\t\t\tif len(effect.Key) == 0 {\n")
	b.WriteString("\t\t\t\tcontinue\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tparts, ok := fsmeta.InspectKey(effect.Key)\n")
	b.WriteString("\t\t\tif !ok || parts.Kind != fsmeta.KeyKindDentry {\n")
	b.WriteString("\t\t\t\tcontinue\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tprojection := WatchProjection{EventKind: watchEventKind(delta, effect), Key: effect.Key, Parent: parts.Parent, Name: dentryName(effect.Key), EmitAt: emitAt}\n")
	b.WriteString("\t\t\tif len(effect.Value) > 0 {\n")
	b.WriteString("\t\t\t\tif dentry, err := fsmeta.DecodeDentryValue(effect.Value); err == nil {\n")
	b.WriteString("\t\t\t\t\tprojection.Inode = dentry.Inode\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\twatch = append(watch, projection)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn CompiledOp{\n")
	b.WriteString("\t\tDelta: delta,\n")
	b.WriteString("\t\tDescriptorDigest: digest,\n")
	b.WriteString("\t\tIntentDigest: digest,\n")
	b.WriteString("\t\tReplayDigest: digest,\n")
	b.WriteString("\t\tAuthority: AuthorityPlan{Scope: delta.Authority, Required: delta.Eligibility == EligibilityVisibleCommit, Fence: fenceMode(delta)},\n")
	b.WriteString("\t\tPlacement: placement,\n")
	b.WriteString("\t\tFootprint: footprint,\n")
	b.WriteString("\t\tPredicates: predicates,\n")
	b.WriteString("\t\tGuards: guards,\n")
	b.WriteString("\t\tEffects: effects,\n")
	b.WriteString("\t\tAtomicity: atomicity,\n")
	b.WriteString("\t\tDurability: durability,\n")
	b.WriteString("\t\tWatch: watch,\n")
	b.WriteString("\t\tCompletion: completion,\n")
	b.WriteString("\t\tSegment: segment,\n")
	b.WriteString("\t}, nil\n")
	b.WriteString("}\n\n")
}

func compiledOpFuncName(spec specdsl.OpSpec) string {
	if spec.Name == "" {
		return ""
	}
	return "compile" + spec.Name + "CompiledOp"
}

func emitMaterializer(b *bytes.Buffer, spec specdsl.OpSpec) error {
	switch spec.Materializer {
	case "":
		return nil
	case "session_put":
		return emitSessionPutMaterializer(b, spec)
	case "session_close":
		return emitSessionCloseMaterializer(b, spec)
	default:
		return fmt.Errorf("unsupported materializer %q for %s", spec.Materializer, spec.Name)
	}
}

func emitSessionPutMaterializer(b *bytes.Buffer, spec specdsl.OpSpec) error {
	if spec.Materialize == "" || spec.ValuesType == "" || spec.OperationKind == "" {
		return fmt.Errorf("%s missing session materializer fields", spec.Name)
	}
	fmt.Fprintf(b, "func %s(program %s, values %s) (MaterializedOp, error) {\n", spec.Materialize, spec.ProgramType, spec.ValuesType)
	b.WriteString("\tcompiled := program.Compiled\n")
	fmt.Fprintf(b, "\tif compiled.Delta.Kind != %s || len(compiled.Delta.WriteEffects) != 2 || values.SessionValue == nil {\n", spec.OperationKind)
	b.WriteString("\t\treturn MaterializedOp{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\teffects := []WriteEffect{\n")
	b.WriteString("\t\t{Kind: EffectPut, Key: compiled.Delta.WriteEffects[0].Key, Value: values.SessionValue},\n")
	b.WriteString("\t\t{Kind: EffectPut, Key: compiled.Delta.WriteEffects[1].Key, Value: values.SessionValue},\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn MaterializeCompiledOpWithEvidence(compiled, effects, PredicateEvidence{\n")
	b.WriteString("\t\tProofs: values.PredicateProofs,\n")
	b.WriteString("\t}, nil)\n")
	b.WriteString("}\n\n")
	return nil
}

func emitSessionCloseMaterializer(b *bytes.Buffer, spec specdsl.OpSpec) error {
	if spec.Materialize == "" || spec.ValuesType == "" || spec.OperationKind == "" {
		return fmt.Errorf("%s missing session materializer fields", spec.Name)
	}
	fmt.Fprintf(b, "func %s(program %s, values %s) (MaterializedOp, error) {\n", spec.Materialize, spec.ProgramType, spec.ValuesType)
	b.WriteString("\tcompiled := program.Compiled\n")
	fmt.Fprintf(b, "\tif compiled.Delta.Kind != %s || len(compiled.Delta.WriteEffects) != 2 {\n", spec.OperationKind)
	b.WriteString("\t\treturn MaterializedOp{}, fsmeta.ErrInvalidRequest\n")
	b.WriteString("\t}\n")
	b.WriteString("\teffects := []WriteEffect{{Kind: EffectDelete, Key: compiled.Delta.WriteEffects[0].Key}}\n")
	b.WriteString("\tif values.DeleteOwner {\n")
	b.WriteString("\t\teffects = append(effects, WriteEffect{Kind: EffectDelete, Key: compiled.Delta.WriteEffects[1].Key})\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn MaterializeCompiledOpWithEvidence(compiled, effects, PredicateEvidence{\n")
	b.WriteString("\t\tProofs: values.PredicateProofs,\n")
	b.WriteString("\t}, nil)\n")
	b.WriteString("}\n\n")
	return nil
}
