// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: error/error.proto

package errorpb

import (
	legacy "github.com/feichai0017/NoKV/pb/legacy"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegionError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotLeader      *NotLeader             `protobuf:"bytes,1,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	EpochNotMatch  *EpochNotMatch         `protobuf:"bytes,2,opt,name=epoch_not_match,json=epochNotMatch,proto3" json:"epoch_not_match,omitempty"`
	StaleCommand   *StaleCommand          `protobuf:"bytes,3,opt,name=stale_command,json=staleCommand,proto3" json:"stale_command,omitempty"`
	EntryTooLarge  *RaftEntryTooLarge     `protobuf:"bytes,4,opt,name=entry_too_large,json=entryTooLarge,proto3" json:"entry_too_large,omitempty"`
	StoreNotMatch  *StoreNotMatch         `protobuf:"bytes,5,opt,name=store_not_match,json=storeNotMatch,proto3" json:"store_not_match,omitempty"`
	RegionNotFound *RegionNotFound        `protobuf:"bytes,6,opt,name=region_not_found,json=regionNotFound,proto3" json:"region_not_found,omitempty"`
	KeyNotInRegion *KeyNotInRegion        `protobuf:"bytes,7,opt,name=key_not_in_region,json=keyNotInRegion,proto3" json:"key_not_in_region,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegionError) Reset() {
	*x = RegionError{}
	mi := &file_error_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionError) ProtoMessage() {}

func (x *RegionError) ProtoReflect() protoreflect.Message {
	mi := &file_error_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionError.ProtoReflect.Descriptor instead.
func (*RegionError) Descriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{0}
}

func (x *RegionError) GetNotLeader() *NotLeader {
	if x != nil {
		return x.NotLeader
	}
	return nil
}

func (x *RegionError) GetEpochNotMatch() *EpochNotMatch {
	if x != nil {
		return x.EpochNotMatch
	}
	return nil
}

func (x *RegionError) GetStaleCommand() *StaleCommand {
	if x != nil {
		return x.StaleCommand
	}
	return nil
}

func (x *RegionError) GetEntryTooLarge() *RaftEntryTooLarge {
	if x != nil {
		return x.EntryTooLarge
	}
	return nil
}

func (x *RegionError) GetStoreNotMatch() *StoreNotMatch {
	if x != nil {
		return x.StoreNotMatch
	}
	return nil
}

func (x *RegionError) GetRegionNotFound() *RegionNotFound {
	if x != nil {
		return x.RegionNotFound
	}
	return nil
}

func (x *RegionError) GetKeyNotInRegion() *KeyNotInRegion {
	if x != nil {
		return x.KeyNotInRegion
	}
	return nil
}

type NotLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Leader        *legacy.RegionPeer     `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeader) Reset() {
	*x = NotLeader{}
	mi := &file_error_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeader) ProtoMessage() {}

func (x *NotLeader) ProtoReflect() protoreflect.Message {
	mi := &file_error_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeader.ProtoReflect.Descriptor instead.
func (*NotLeader) Descriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{1}
}

func (x *NotLeader) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *NotLeader) GetLeader() *legacy.RegionPeer {
	if x != nil {
		return x.Leader
	}
	return nil
}

type EpochNotMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentEpoch  *legacy.RegionEpoch    `protobuf:"bytes,1,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	Regions       []*legacy.RegionMeta   `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochNotMatch) Reset() {
	*x = EpochNotMatch{}
	mi := &file_error_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochNotMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochNotMatch) ProtoMessage() {}

func (x *EpochNotMatch) ProtoReflect() protoreflect.Message {
	mi := &file_error_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochNotMatch.ProtoReflect.Descriptor instead.
func (*EpochNotMatch) Descriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{2}
}

func (x *EpochNotMatch) GetCurrentEpoch() *legacy.RegionEpoch {
	if x != nil {
		return x.CurrentEpoch
	}
	return nil
}

func (x *EpochNotMatch) GetRegions() []*legacy.RegionMeta {
	if x != nil {
		return x.Regions
	}
	return nil
}

type StaleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaleCommand) Reset() {
	*x = StaleCommand{}
	mi := &file_error_error_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaleCommand) ProtoMessage() {}

func (x *StaleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_error_error_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaleCommand.ProtoReflect.Descriptor instead.
func (*StaleCommand) Descriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{3}
}

type RaftEntryTooLarge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftEntryTooLarge) Reset() {
	*x = RaftEntryTooLarge{}
	mi := &file_error_error_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftEntryTooLarge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftEntryTooLarge) ProtoMessage() {}

func (x *RaftEntryTooLarge) ProtoReflect() protoreflect.Message {
	mi := &file_error_error_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftEntryTooLarge.ProtoReflect.Descriptor instead.
func (*RaftEntryTooLarge) Descriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{4}
}

func (x *RaftEntryTooLarge) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type StoreNotMatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestStoreId uint64                 `protobuf:"varint,1,opt,name=request_store_id,json=requestStoreId,proto3" json:"request_store_id,omitempty"`
	ActualStoreId  uint64                 `protobuf:"varint,2,opt,name=actual_store_id,json=actualStoreId,proto3" json:"actual_store_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreNotMatch) Reset() {
	*x = StoreNotMatch{}
	mi := &file_error_error_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreNotMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreNotMatch) ProtoMessage() {}

func (x *StoreNotMatch) ProtoReflect() protoreflect.Message {
	mi := &file_error_error_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreNotMatch.ProtoReflect.Descriptor instead.
func (*StoreNotMatch) Descriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{5}
}

func (x *StoreNotMatch) GetRequestStoreId() uint64 {
	if x != nil {
		return x.RequestStoreId
	}
	return 0
}

func (x *StoreNotMatch) GetActualStoreId() uint64 {
	if x != nil {
		return x.ActualStoreId
	}
	return 0
}

type RegionNotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionNotFound) Reset() {
	*x = RegionNotFound{}
	mi := &file_error_error_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionNotFound) ProtoMessage() {}

func (x *RegionNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_error_error_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionNotFound.ProtoReflect.Descriptor instead.
func (*RegionNotFound) Descriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{6}
}

func (x *RegionNotFound) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type KeyNotInRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RegionId      uint64                 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,3,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,4,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyNotInRegion) Reset() {
	*x = KeyNotInRegion{}
	mi := &file_error_error_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyNotInRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyNotInRegion) ProtoMessage() {}

func (x *KeyNotInRegion) ProtoReflect() protoreflect.Message {
	mi := &file_error_error_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyNotInRegion.ProtoReflect.Descriptor instead.
func (*KeyNotInRegion) Descriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{7}
}

func (x *KeyNotInRegion) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyNotInRegion) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *KeyNotInRegion) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *KeyNotInRegion) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

var File_error_error_proto protoreflect.FileDescriptor

const file_error_error_proto_rawDesc = "" +
	"\n" +
	"\x11error/error.proto\x12\rnokv.error.v1\x1a\x11legacy/meta.proto\"\xf1\x03\n" +
	"\vRegionError\x127\n" +
	"\n" +
	"not_leader\x18\x01 \x01(\v2\x18.nokv.error.v1.NotLeaderR\tnotLeader\x12D\n" +
	"\x0fepoch_not_match\x18\x02 \x01(\v2\x1c.nokv.error.v1.EpochNotMatchR\repochNotMatch\x12@\n" +
	"\rstale_command\x18\x03 \x01(\v2\x1b.nokv.error.v1.StaleCommandR\fstaleCommand\x12H\n" +
	"\x0fentry_too_large\x18\x04 \x01(\v2 .nokv.error.v1.RaftEntryTooLargeR\rentryTooLarge\x12D\n" +
	"\x0fstore_not_match\x18\x05 \x01(\v2\x1c.nokv.error.v1.StoreNotMatchR\rstoreNotMatch\x12G\n" +
	"\x10region_not_found\x18\x06 \x01(\v2\x1d.nokv.error.v1.RegionNotFoundR\x0eregionNotFound\x12H\n" +
	"\x11key_not_in_region\x18\a \x01(\v2\x1d.nokv.error.v1.KeyNotInRegionR\x0ekeyNotInRegion\"a\n" +
	"\tNotLeader\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x127\n" +
	"\x06leader\x18\x02 \x01(\v2\x1f.nokv.meta.legacy.v1.RegionPeerR\x06leader\"\x91\x01\n" +
	"\rEpochNotMatch\x12E\n" +
	"\rcurrent_epoch\x18\x01 \x01(\v2 .nokv.meta.legacy.v1.RegionEpochR\fcurrentEpoch\x129\n" +
	"\aregions\x18\x02 \x03(\v2\x1f.nokv.meta.legacy.v1.RegionMetaR\aregions\"\x0e\n" +
	"\fStaleCommand\"0\n" +
	"\x11RaftEntryTooLarge\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"a\n" +
	"\rStoreNotMatch\x12(\n" +
	"\x10request_store_id\x18\x01 \x01(\x04R\x0erequestStoreId\x12&\n" +
	"\x0factual_store_id\x18\x02 \x01(\x04R\ractualStoreId\"-\n" +
	"\x0eRegionNotFound\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"u\n" +
	"\x0eKeyNotInRegion\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\x04R\bregionId\x12\x1b\n" +
	"\tstart_key\x18\x03 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x04 \x01(\fR\x06endKeyB.Z,github.com/feichai0017/NoKV/pb/error;errorpbb\x06proto3"

var (
	file_error_error_proto_rawDescOnce sync.Once
	file_error_error_proto_rawDescData []byte
)

func file_error_error_proto_rawDescGZIP() []byte {
	file_error_error_proto_rawDescOnce.Do(func() {
		file_error_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_error_proto_rawDesc), len(file_error_error_proto_rawDesc)))
	})
	return file_error_error_proto_rawDescData
}

var file_error_error_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_error_error_proto_goTypes = []any{
	(*RegionError)(nil),        // 0: nokv.error.v1.RegionError
	(*NotLeader)(nil),          // 1: nokv.error.v1.NotLeader
	(*EpochNotMatch)(nil),      // 2: nokv.error.v1.EpochNotMatch
	(*StaleCommand)(nil),       // 3: nokv.error.v1.StaleCommand
	(*RaftEntryTooLarge)(nil),  // 4: nokv.error.v1.RaftEntryTooLarge
	(*StoreNotMatch)(nil),      // 5: nokv.error.v1.StoreNotMatch
	(*RegionNotFound)(nil),     // 6: nokv.error.v1.RegionNotFound
	(*KeyNotInRegion)(nil),     // 7: nokv.error.v1.KeyNotInRegion
	(*legacy.RegionPeer)(nil),  // 8: nokv.meta.legacy.v1.RegionPeer
	(*legacy.RegionEpoch)(nil), // 9: nokv.meta.legacy.v1.RegionEpoch
	(*legacy.RegionMeta)(nil),  // 10: nokv.meta.legacy.v1.RegionMeta
}
var file_error_error_proto_depIdxs = []int32{
	1,  // 0: nokv.error.v1.RegionError.not_leader:type_name -> nokv.error.v1.NotLeader
	2,  // 1: nokv.error.v1.RegionError.epoch_not_match:type_name -> nokv.error.v1.EpochNotMatch
	3,  // 2: nokv.error.v1.RegionError.stale_command:type_name -> nokv.error.v1.StaleCommand
	4,  // 3: nokv.error.v1.RegionError.entry_too_large:type_name -> nokv.error.v1.RaftEntryTooLarge
	5,  // 4: nokv.error.v1.RegionError.store_not_match:type_name -> nokv.error.v1.StoreNotMatch
	6,  // 5: nokv.error.v1.RegionError.region_not_found:type_name -> nokv.error.v1.RegionNotFound
	7,  // 6: nokv.error.v1.RegionError.key_not_in_region:type_name -> nokv.error.v1.KeyNotInRegion
	8,  // 7: nokv.error.v1.NotLeader.leader:type_name -> nokv.meta.legacy.v1.RegionPeer
	9,  // 8: nokv.error.v1.EpochNotMatch.current_epoch:type_name -> nokv.meta.legacy.v1.RegionEpoch
	10, // 9: nokv.error.v1.EpochNotMatch.regions:type_name -> nokv.meta.legacy.v1.RegionMeta
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_error_error_proto_init() }
func file_error_error_proto_init() {
	if File_error_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_error_proto_rawDesc), len(file_error_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_error_proto_goTypes,
		DependencyIndexes: file_error_error_proto_depIdxs,
		MessageInfos:      file_error_error_proto_msgTypes,
	}.Build()
	File_error_error_proto = out.File
	file_error_error_proto_goTypes = nil
	file_error_error_proto_depIdxs = nil
}
