// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: kv/kv.proto

package kvrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreKV_Get_FullMethodName             = "/nokv.kv.v1.StoreKV/Get"
	StoreKV_BatchGet_FullMethodName        = "/nokv.kv.v1.StoreKV/BatchGet"
	StoreKV_Scan_FullMethodName            = "/nokv.kv.v1.StoreKV/Scan"
	StoreKV_Prewrite_FullMethodName        = "/nokv.kv.v1.StoreKV/Prewrite"
	StoreKV_Commit_FullMethodName          = "/nokv.kv.v1.StoreKV/Commit"
	StoreKV_BatchRollback_FullMethodName   = "/nokv.kv.v1.StoreKV/BatchRollback"
	StoreKV_ResolveLock_FullMethodName     = "/nokv.kv.v1.StoreKV/ResolveLock"
	StoreKV_CheckTxnStatus_FullMethodName  = "/nokv.kv.v1.StoreKV/CheckTxnStatus"
	StoreKV_TxnHeartBeat_FullMethodName    = "/nokv.kv.v1.StoreKV/TxnHeartBeat"
	StoreKV_TryAtomicMutate_FullMethodName = "/nokv.kv.v1.StoreKV/TryAtomicMutate"
	StoreKV_WatchApply_FullMethodName      = "/nokv.kv.v1.StoreKV/WatchApply"
)

// StoreKVClient is the client API for StoreKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreKVClient interface {
	Get(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error)
	BatchGet(ctx context.Context, in *KvBatchGetRequest, opts ...grpc.CallOption) (*KvBatchGetResponse, error)
	Scan(ctx context.Context, in *KvScanRequest, opts ...grpc.CallOption) (*KvScanResponse, error)
	Prewrite(ctx context.Context, in *KvPrewriteRequest, opts ...grpc.CallOption) (*KvPrewriteResponse, error)
	Commit(ctx context.Context, in *KvCommitRequest, opts ...grpc.CallOption) (*KvCommitResponse, error)
	BatchRollback(ctx context.Context, in *KvBatchRollbackRequest, opts ...grpc.CallOption) (*KvBatchRollbackResponse, error)
	ResolveLock(ctx context.Context, in *KvResolveLockRequest, opts ...grpc.CallOption) (*KvResolveLockResponse, error)
	CheckTxnStatus(ctx context.Context, in *KvCheckTxnStatusRequest, opts ...grpc.CallOption) (*KvCheckTxnStatusResponse, error)
	TxnHeartBeat(ctx context.Context, in *KvTxnHeartBeatRequest, opts ...grpc.CallOption) (*KvTxnHeartBeatResponse, error)
	TryAtomicMutate(ctx context.Context, in *KvTryAtomicMutateRequest, opts ...grpc.CallOption) (*KvTryAtomicMutateResponse, error)
	WatchApply(ctx context.Context, in *ApplyWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApplyWatchResponse], error)
}

type storeKVClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreKVClient(cc grpc.ClientConnInterface) StoreKVClient {
	return &storeKVClient{cc}
}

func (c *storeKVClient) Get(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvGetResponse)
	err := c.cc.Invoke(ctx, StoreKV_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) BatchGet(ctx context.Context, in *KvBatchGetRequest, opts ...grpc.CallOption) (*KvBatchGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBatchGetResponse)
	err := c.cc.Invoke(ctx, StoreKV_BatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) Scan(ctx context.Context, in *KvScanRequest, opts ...grpc.CallOption) (*KvScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvScanResponse)
	err := c.cc.Invoke(ctx, StoreKV_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) Prewrite(ctx context.Context, in *KvPrewriteRequest, opts ...grpc.CallOption) (*KvPrewriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvPrewriteResponse)
	err := c.cc.Invoke(ctx, StoreKV_Prewrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) Commit(ctx context.Context, in *KvCommitRequest, opts ...grpc.CallOption) (*KvCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvCommitResponse)
	err := c.cc.Invoke(ctx, StoreKV_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) BatchRollback(ctx context.Context, in *KvBatchRollbackRequest, opts ...grpc.CallOption) (*KvBatchRollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBatchRollbackResponse)
	err := c.cc.Invoke(ctx, StoreKV_BatchRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) ResolveLock(ctx context.Context, in *KvResolveLockRequest, opts ...grpc.CallOption) (*KvResolveLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResolveLockResponse)
	err := c.cc.Invoke(ctx, StoreKV_ResolveLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) CheckTxnStatus(ctx context.Context, in *KvCheckTxnStatusRequest, opts ...grpc.CallOption) (*KvCheckTxnStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvCheckTxnStatusResponse)
	err := c.cc.Invoke(ctx, StoreKV_CheckTxnStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) TxnHeartBeat(ctx context.Context, in *KvTxnHeartBeatRequest, opts ...grpc.CallOption) (*KvTxnHeartBeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvTxnHeartBeatResponse)
	err := c.cc.Invoke(ctx, StoreKV_TxnHeartBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) TryAtomicMutate(ctx context.Context, in *KvTryAtomicMutateRequest, opts ...grpc.CallOption) (*KvTryAtomicMutateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvTryAtomicMutateResponse)
	err := c.cc.Invoke(ctx, StoreKV_TryAtomicMutate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) WatchApply(ctx context.Context, in *ApplyWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ApplyWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoreKV_ServiceDesc.Streams[0], StoreKV_WatchApply_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApplyWatchRequest, ApplyWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreKV_WatchApplyClient = grpc.ServerStreamingClient[ApplyWatchResponse]

// StoreKVServer is the server API for StoreKV service.
// All implementations should embed UnimplementedStoreKVServer
// for forward compatibility.
type StoreKVServer interface {
	Get(context.Context, *KvGetRequest) (*KvGetResponse, error)
	BatchGet(context.Context, *KvBatchGetRequest) (*KvBatchGetResponse, error)
	Scan(context.Context, *KvScanRequest) (*KvScanResponse, error)
	Prewrite(context.Context, *KvPrewriteRequest) (*KvPrewriteResponse, error)
	Commit(context.Context, *KvCommitRequest) (*KvCommitResponse, error)
	BatchRollback(context.Context, *KvBatchRollbackRequest) (*KvBatchRollbackResponse, error)
	ResolveLock(context.Context, *KvResolveLockRequest) (*KvResolveLockResponse, error)
	CheckTxnStatus(context.Context, *KvCheckTxnStatusRequest) (*KvCheckTxnStatusResponse, error)
	TxnHeartBeat(context.Context, *KvTxnHeartBeatRequest) (*KvTxnHeartBeatResponse, error)
	TryAtomicMutate(context.Context, *KvTryAtomicMutateRequest) (*KvTryAtomicMutateResponse, error)
	WatchApply(*ApplyWatchRequest, grpc.ServerStreamingServer[ApplyWatchResponse]) error
}

// UnimplementedStoreKVServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreKVServer struct{}

func (UnimplementedStoreKVServer) Get(context.Context, *KvGetRequest) (*KvGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStoreKVServer) BatchGet(context.Context, *KvBatchGetRequest) (*KvBatchGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedStoreKVServer) Scan(context.Context, *KvScanRequest) (*KvScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedStoreKVServer) Prewrite(context.Context, *KvPrewriteRequest) (*KvPrewriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prewrite not implemented")
}
func (UnimplementedStoreKVServer) Commit(context.Context, *KvCommitRequest) (*KvCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedStoreKVServer) BatchRollback(context.Context, *KvBatchRollbackRequest) (*KvBatchRollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchRollback not implemented")
}
func (UnimplementedStoreKVServer) ResolveLock(context.Context, *KvResolveLockRequest) (*KvResolveLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveLock not implemented")
}
func (UnimplementedStoreKVServer) CheckTxnStatus(context.Context, *KvCheckTxnStatusRequest) (*KvCheckTxnStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTxnStatus not implemented")
}
func (UnimplementedStoreKVServer) TxnHeartBeat(context.Context, *KvTxnHeartBeatRequest) (*KvTxnHeartBeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TxnHeartBeat not implemented")
}
func (UnimplementedStoreKVServer) TryAtomicMutate(context.Context, *KvTryAtomicMutateRequest) (*KvTryAtomicMutateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TryAtomicMutate not implemented")
}
func (UnimplementedStoreKVServer) WatchApply(*ApplyWatchRequest, grpc.ServerStreamingServer[ApplyWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchApply not implemented")
}
func (UnimplementedStoreKVServer) testEmbeddedByValue() {}

// UnsafeStoreKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreKVServer will
// result in compilation errors.
type UnsafeStoreKVServer interface {
	mustEmbedUnimplementedStoreKVServer()
}

func RegisterStoreKVServer(s grpc.ServiceRegistrar, srv StoreKVServer) {
	// If the following call panics, it indicates UnimplementedStoreKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreKV_ServiceDesc, srv)
}

func _StoreKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).Get(ctx, req.(*KvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_BatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).BatchGet(ctx, req.(*KvBatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).Scan(ctx, req.(*KvScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_Prewrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvPrewriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).Prewrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_Prewrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).Prewrite(ctx, req.(*KvPrewriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).Commit(ctx, req.(*KvCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_BatchRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBatchRollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).BatchRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_BatchRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).BatchRollback(ctx, req.(*KvBatchRollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_ResolveLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvResolveLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).ResolveLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_ResolveLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).ResolveLock(ctx, req.(*KvResolveLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_CheckTxnStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvCheckTxnStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).CheckTxnStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_CheckTxnStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).CheckTxnStatus(ctx, req.(*KvCheckTxnStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_TxnHeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvTxnHeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).TxnHeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_TxnHeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).TxnHeartBeat(ctx, req.(*KvTxnHeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_TryAtomicMutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvTryAtomicMutateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).TryAtomicMutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreKV_TryAtomicMutate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).TryAtomicMutate(ctx, req.(*KvTryAtomicMutateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_WatchApply_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApplyWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreKVServer).WatchApply(m, &grpc.GenericServerStream[ApplyWatchRequest, ApplyWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreKV_WatchApplyServer = grpc.ServerStreamingServer[ApplyWatchResponse]

// StoreKV_ServiceDesc is the grpc.ServiceDesc for StoreKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nokv.kv.v1.StoreKV",
	HandlerType: (*StoreKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _StoreKV_Get_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _StoreKV_BatchGet_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _StoreKV_Scan_Handler,
		},
		{
			MethodName: "Prewrite",
			Handler:    _StoreKV_Prewrite_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _StoreKV_Commit_Handler,
		},
		{
			MethodName: "BatchRollback",
			Handler:    _StoreKV_BatchRollback_Handler,
		},
		{
			MethodName: "ResolveLock",
			Handler:    _StoreKV_ResolveLock_Handler,
		},
		{
			MethodName: "CheckTxnStatus",
			Handler:    _StoreKV_CheckTxnStatus_Handler,
		},
		{
			MethodName: "TxnHeartBeat",
			Handler:    _StoreKV_TxnHeartBeat_Handler,
		},
		{
			MethodName: "TryAtomicMutate",
			Handler:    _StoreKV_TryAtomicMutate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchApply",
			Handler:       _StoreKV_WatchApply_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kv/kv.proto",
}
