// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meta/recovery.proto

package metapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicaLocalState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	LocalPeerId   uint64                 `protobuf:"varint,2,opt,name=local_peer_id,json=localPeerId,proto3" json:"local_peer_id,omitempty"`
	State         RegionReplicaState     `protobuf:"varint,3,opt,name=state,proto3,enum=nokv.meta.v1.RegionReplicaState" json:"state,omitempty"`
	Descriptor_   *RegionDescriptor      `protobuf:"bytes,4,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	LastApplied   uint64                 `protobuf:"varint,5,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	LastTerm      uint64                 `protobuf:"varint,6,opt,name=last_term,json=lastTerm,proto3" json:"last_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaLocalState) Reset() {
	*x = ReplicaLocalState{}
	mi := &file_meta_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaLocalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaLocalState) ProtoMessage() {}

func (x *ReplicaLocalState) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaLocalState.ProtoReflect.Descriptor instead.
func (*ReplicaLocalState) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaLocalState) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *ReplicaLocalState) GetLocalPeerId() uint64 {
	if x != nil {
		return x.LocalPeerId
	}
	return 0
}

func (x *ReplicaLocalState) GetState() RegionReplicaState {
	if x != nil {
		return x.State
	}
	return RegionReplicaState_REGION_REPLICA_STATE_UNSPECIFIED
}

func (x *ReplicaLocalState) GetDescriptor_() *RegionDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *ReplicaLocalState) GetLastApplied() uint64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *ReplicaLocalState) GetLastTerm() uint64 {
	if x != nil {
		return x.LastTerm
	}
	return 0
}

type LocalRegionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,3,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Epoch         *RegionEpoch           `protobuf:"bytes,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Peers         []*RegionPeer          `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	State         RegionReplicaState     `protobuf:"varint,6,opt,name=state,proto3,enum=nokv.meta.v1.RegionReplicaState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalRegionMeta) Reset() {
	*x = LocalRegionMeta{}
	mi := &file_meta_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRegionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRegionMeta) ProtoMessage() {}

func (x *LocalRegionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRegionMeta.ProtoReflect.Descriptor instead.
func (*LocalRegionMeta) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *LocalRegionMeta) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *LocalRegionMeta) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *LocalRegionMeta) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *LocalRegionMeta) GetEpoch() *RegionEpoch {
	if x != nil {
		return x.Epoch
	}
	return nil
}

func (x *LocalRegionMeta) GetPeers() []*RegionPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *LocalRegionMeta) GetState() RegionReplicaState {
	if x != nil {
		return x.State
	}
	return RegionReplicaState_REGION_REPLICA_STATE_UNSPECIFIED
}

type ReplicaLocalCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*LocalRegionMeta     `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaLocalCatalog) Reset() {
	*x = ReplicaLocalCatalog{}
	mi := &file_meta_recovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaLocalCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaLocalCatalog) ProtoMessage() {}

func (x *ReplicaLocalCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaLocalCatalog.ProtoReflect.Descriptor instead.
func (*ReplicaLocalCatalog) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicaLocalCatalog) GetRegions() []*LocalRegionMeta {
	if x != nil {
		return x.Regions
	}
	return nil
}

type RaftProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Segment         uint32                 `protobuf:"varint,2,opt,name=segment,proto3" json:"segment,omitempty"`
	Offset          uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	AppliedIndex    uint64                 `protobuf:"varint,4,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	AppliedTerm     uint64                 `protobuf:"varint,5,opt,name=applied_term,json=appliedTerm,proto3" json:"applied_term,omitempty"`
	Committed       uint64                 `protobuf:"varint,6,opt,name=committed,proto3" json:"committed,omitempty"`
	SnapshotIndex   uint64                 `protobuf:"varint,7,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	SnapshotTerm    uint64                 `protobuf:"varint,8,opt,name=snapshot_term,json=snapshotTerm,proto3" json:"snapshot_term,omitempty"`
	TruncatedIndex  uint64                 `protobuf:"varint,9,opt,name=truncated_index,json=truncatedIndex,proto3" json:"truncated_index,omitempty"`
	TruncatedTerm   uint64                 `protobuf:"varint,10,opt,name=truncated_term,json=truncatedTerm,proto3" json:"truncated_term,omitempty"`
	SegmentIndex    uint64                 `protobuf:"varint,11,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"`
	TruncatedOffset uint64                 `protobuf:"varint,12,opt,name=truncated_offset,json=truncatedOffset,proto3" json:"truncated_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RaftProgress) Reset() {
	*x = RaftProgress{}
	mi := &file_meta_recovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftProgress) ProtoMessage() {}

func (x *RaftProgress) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftProgress.ProtoReflect.Descriptor instead.
func (*RaftProgress) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *RaftProgress) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RaftProgress) GetSegment() uint32 {
	if x != nil {
		return x.Segment
	}
	return 0
}

func (x *RaftProgress) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RaftProgress) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *RaftProgress) GetAppliedTerm() uint64 {
	if x != nil {
		return x.AppliedTerm
	}
	return 0
}

func (x *RaftProgress) GetCommitted() uint64 {
	if x != nil {
		return x.Committed
	}
	return 0
}

func (x *RaftProgress) GetSnapshotIndex() uint64 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

func (x *RaftProgress) GetSnapshotTerm() uint64 {
	if x != nil {
		return x.SnapshotTerm
	}
	return 0
}

func (x *RaftProgress) GetTruncatedIndex() uint64 {
	if x != nil {
		return x.TruncatedIndex
	}
	return 0
}

func (x *RaftProgress) GetTruncatedTerm() uint64 {
	if x != nil {
		return x.TruncatedTerm
	}
	return 0
}

func (x *RaftProgress) GetSegmentIndex() uint64 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *RaftProgress) GetTruncatedOffset() uint64 {
	if x != nil {
		return x.TruncatedOffset
	}
	return 0
}

type RaftProgressCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RaftProgress        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftProgressCatalog) Reset() {
	*x = RaftProgressCatalog{}
	mi := &file_meta_recovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftProgressCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftProgressCatalog) ProtoMessage() {}

func (x *RaftProgressCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftProgressCatalog.ProtoReflect.Descriptor instead.
func (*RaftProgressCatalog) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{4}
}

func (x *RaftProgressCatalog) GetEntries() []*RaftProgress {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PendingRootEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Event         *RootEvent             `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingRootEvent) Reset() {
	*x = PendingRootEvent{}
	mi := &file_meta_recovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRootEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRootEvent) ProtoMessage() {}

func (x *PendingRootEvent) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRootEvent.ProtoReflect.Descriptor instead.
func (*PendingRootEvent) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{5}
}

func (x *PendingRootEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PendingRootEvent) GetEvent() *RootEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PendingRootEventCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*PendingRootEvent    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingRootEventCatalog) Reset() {
	*x = PendingRootEventCatalog{}
	mi := &file_meta_recovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRootEventCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRootEventCatalog) ProtoMessage() {}

func (x *PendingRootEventCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRootEventCatalog.ProtoReflect.Descriptor instead.
func (*PendingRootEventCatalog) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{6}
}

func (x *PendingRootEventCatalog) GetEntries() []*PendingRootEvent {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PendingSchedulerOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType uint32                 `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	RegionId      uint64                 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	SourcePeerId  uint64                 `protobuf:"varint,3,opt,name=source_peer_id,json=sourcePeerId,proto3" json:"source_peer_id,omitempty"`
	TargetPeerId  uint64                 `protobuf:"varint,4,opt,name=target_peer_id,json=targetPeerId,proto3" json:"target_peer_id,omitempty"`
	Attempts      uint32                 `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingSchedulerOperation) Reset() {
	*x = PendingSchedulerOperation{}
	mi := &file_meta_recovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingSchedulerOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingSchedulerOperation) ProtoMessage() {}

func (x *PendingSchedulerOperation) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingSchedulerOperation.ProtoReflect.Descriptor instead.
func (*PendingSchedulerOperation) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{7}
}

func (x *PendingSchedulerOperation) GetOperationType() uint32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *PendingSchedulerOperation) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *PendingSchedulerOperation) GetSourcePeerId() uint64 {
	if x != nil {
		return x.SourcePeerId
	}
	return 0
}

func (x *PendingSchedulerOperation) GetTargetPeerId() uint64 {
	if x != nil {
		return x.TargetPeerId
	}
	return 0
}

func (x *PendingSchedulerOperation) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type PendingSchedulerOperationCatalog struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Entries       []*PendingSchedulerOperation `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingSchedulerOperationCatalog) Reset() {
	*x = PendingSchedulerOperationCatalog{}
	mi := &file_meta_recovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingSchedulerOperationCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingSchedulerOperationCatalog) ProtoMessage() {}

func (x *PendingSchedulerOperationCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingSchedulerOperationCatalog.ProtoReflect.Descriptor instead.
func (*PendingSchedulerOperationCatalog) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{8}
}

func (x *PendingSchedulerOperationCatalog) GetEntries() []*PendingSchedulerOperation {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BlockedRootEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Event         *RootEvent             `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	TransitionId  string                 `protobuf:"bytes,3,opt,name=transition_id,json=transitionId,proto3" json:"transition_id,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedRootEvent) Reset() {
	*x = BlockedRootEvent{}
	mi := &file_meta_recovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedRootEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedRootEvent) ProtoMessage() {}

func (x *BlockedRootEvent) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedRootEvent.ProtoReflect.Descriptor instead.
func (*BlockedRootEvent) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{9}
}

func (x *BlockedRootEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BlockedRootEvent) GetEvent() *RootEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BlockedRootEvent) GetTransitionId() string {
	if x != nil {
		return x.TransitionId
	}
	return ""
}

func (x *BlockedRootEvent) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type BlockedRootEventCatalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*BlockedRootEvent    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockedRootEventCatalog) Reset() {
	*x = BlockedRootEventCatalog{}
	mi := &file_meta_recovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockedRootEventCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedRootEventCatalog) ProtoMessage() {}

func (x *BlockedRootEventCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedRootEventCatalog.ProtoReflect.Descriptor instead.
func (*BlockedRootEventCatalog) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{10}
}

func (x *BlockedRootEventCatalog) GetEntries() []*BlockedRootEvent {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_meta_recovery_proto protoreflect.FileDescriptor

const file_meta_recovery_proto_rawDesc = "" +
	"\n" +
	"\x13meta/recovery.proto\x12\fnokv.meta.v1\x1a\x15meta/descriptor.proto\x1a\x11meta/region.proto\x1a\x0fmeta/root.proto\"\x8c\x02\n" +
	"\x11ReplicaLocalState\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\"\n" +
	"\rlocal_peer_id\x18\x02 \x01(\x04R\vlocalPeerId\x126\n" +
	"\x05state\x18\x03 \x01(\x0e2 .nokv.meta.v1.RegionReplicaStateR\x05state\x12>\n" +
	"\n" +
	"descriptor\x18\x04 \x01(\v2\x1e.nokv.meta.v1.RegionDescriptorR\n" +
	"descriptor\x12!\n" +
	"\flast_applied\x18\x05 \x01(\x04R\vlastApplied\x12\x1b\n" +
	"\tlast_term\x18\x06 \x01(\x04R\blastTerm\"\xfd\x01\n" +
	"\x0fLocalRegionMeta\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x1b\n" +
	"\tstart_key\x18\x02 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x03 \x01(\fR\x06endKey\x12/\n" +
	"\x05epoch\x18\x04 \x01(\v2\x19.nokv.meta.v1.RegionEpochR\x05epoch\x12.\n" +
	"\x05peers\x18\x05 \x03(\v2\x18.nokv.meta.v1.RegionPeerR\x05peers\x126\n" +
	"\x05state\x18\x06 \x01(\x0e2 .nokv.meta.v1.RegionReplicaStateR\x05state\"N\n" +
	"\x13ReplicaLocalCatalog\x127\n" +
	"\aregions\x18\x01 \x03(\v2\x1d.nokv.meta.v1.LocalRegionMetaR\aregions\"\xad\x03\n" +
	"\fRaftProgress\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x18\n" +
	"\asegment\x18\x02 \x01(\rR\asegment\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12#\n" +
	"\rapplied_index\x18\x04 \x01(\x04R\fappliedIndex\x12!\n" +
	"\fapplied_term\x18\x05 \x01(\x04R\vappliedTerm\x12\x1c\n" +
	"\tcommitted\x18\x06 \x01(\x04R\tcommitted\x12%\n" +
	"\x0esnapshot_index\x18\a \x01(\x04R\rsnapshotIndex\x12#\n" +
	"\rsnapshot_term\x18\b \x01(\x04R\fsnapshotTerm\x12'\n" +
	"\x0ftruncated_index\x18\t \x01(\x04R\x0etruncatedIndex\x12%\n" +
	"\x0etruncated_term\x18\n" +
	" \x01(\x04R\rtruncatedTerm\x12#\n" +
	"\rsegment_index\x18\v \x01(\x04R\fsegmentIndex\x12)\n" +
	"\x10truncated_offset\x18\f \x01(\x04R\x0ftruncatedOffset\"K\n" +
	"\x13RaftProgressCatalog\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.nokv.meta.v1.RaftProgressR\aentries\"]\n" +
	"\x10PendingRootEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12-\n" +
	"\x05event\x18\x02 \x01(\v2\x17.nokv.meta.v1.RootEventR\x05event\"S\n" +
	"\x17PendingRootEventCatalog\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.nokv.meta.v1.PendingRootEventR\aentries\"\xc7\x01\n" +
	"\x19PendingSchedulerOperation\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\rR\roperationType\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\x04R\bregionId\x12$\n" +
	"\x0esource_peer_id\x18\x03 \x01(\x04R\fsourcePeerId\x12$\n" +
	"\x0etarget_peer_id\x18\x04 \x01(\x04R\ftargetPeerId\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\rR\battempts\"e\n" +
	" PendingSchedulerOperationCatalog\x12A\n" +
	"\aentries\x18\x01 \x03(\v2'.nokv.meta.v1.PendingSchedulerOperationR\aentries\"\xa1\x01\n" +
	"\x10BlockedRootEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12-\n" +
	"\x05event\x18\x02 \x01(\v2\x17.nokv.meta.v1.RootEventR\x05event\x12#\n" +
	"\rtransition_id\x18\x03 \x01(\tR\ftransitionId\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"S\n" +
	"\x17BlockedRootEventCatalog\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.nokv.meta.v1.BlockedRootEventR\aentriesB,Z*github.com/feichai0017/NoKV/pb/meta;metapbb\x06proto3"

var (
	file_meta_recovery_proto_rawDescOnce sync.Once
	file_meta_recovery_proto_rawDescData []byte
)

func file_meta_recovery_proto_rawDescGZIP() []byte {
	file_meta_recovery_proto_rawDescOnce.Do(func() {
		file_meta_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_recovery_proto_rawDesc), len(file_meta_recovery_proto_rawDesc)))
	})
	return file_meta_recovery_proto_rawDescData
}

var file_meta_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_meta_recovery_proto_goTypes = []any{
	(*ReplicaLocalState)(nil),                // 0: nokv.meta.v1.ReplicaLocalState
	(*LocalRegionMeta)(nil),                  // 1: nokv.meta.v1.LocalRegionMeta
	(*ReplicaLocalCatalog)(nil),              // 2: nokv.meta.v1.ReplicaLocalCatalog
	(*RaftProgress)(nil),                     // 3: nokv.meta.v1.RaftProgress
	(*RaftProgressCatalog)(nil),              // 4: nokv.meta.v1.RaftProgressCatalog
	(*PendingRootEvent)(nil),                 // 5: nokv.meta.v1.PendingRootEvent
	(*PendingRootEventCatalog)(nil),          // 6: nokv.meta.v1.PendingRootEventCatalog
	(*PendingSchedulerOperation)(nil),        // 7: nokv.meta.v1.PendingSchedulerOperation
	(*PendingSchedulerOperationCatalog)(nil), // 8: nokv.meta.v1.PendingSchedulerOperationCatalog
	(*BlockedRootEvent)(nil),                 // 9: nokv.meta.v1.BlockedRootEvent
	(*BlockedRootEventCatalog)(nil),          // 10: nokv.meta.v1.BlockedRootEventCatalog
	(RegionReplicaState)(0),                  // 11: nokv.meta.v1.RegionReplicaState
	(*RegionDescriptor)(nil),                 // 12: nokv.meta.v1.RegionDescriptor
	(*RegionEpoch)(nil),                      // 13: nokv.meta.v1.RegionEpoch
	(*RegionPeer)(nil),                       // 14: nokv.meta.v1.RegionPeer
	(*RootEvent)(nil),                        // 15: nokv.meta.v1.RootEvent
}
var file_meta_recovery_proto_depIdxs = []int32{
	11, // 0: nokv.meta.v1.ReplicaLocalState.state:type_name -> nokv.meta.v1.RegionReplicaState
	12, // 1: nokv.meta.v1.ReplicaLocalState.descriptor:type_name -> nokv.meta.v1.RegionDescriptor
	13, // 2: nokv.meta.v1.LocalRegionMeta.epoch:type_name -> nokv.meta.v1.RegionEpoch
	14, // 3: nokv.meta.v1.LocalRegionMeta.peers:type_name -> nokv.meta.v1.RegionPeer
	11, // 4: nokv.meta.v1.LocalRegionMeta.state:type_name -> nokv.meta.v1.RegionReplicaState
	1,  // 5: nokv.meta.v1.ReplicaLocalCatalog.regions:type_name -> nokv.meta.v1.LocalRegionMeta
	3,  // 6: nokv.meta.v1.RaftProgressCatalog.entries:type_name -> nokv.meta.v1.RaftProgress
	15, // 7: nokv.meta.v1.PendingRootEvent.event:type_name -> nokv.meta.v1.RootEvent
	5,  // 8: nokv.meta.v1.PendingRootEventCatalog.entries:type_name -> nokv.meta.v1.PendingRootEvent
	7,  // 9: nokv.meta.v1.PendingSchedulerOperationCatalog.entries:type_name -> nokv.meta.v1.PendingSchedulerOperation
	15, // 10: nokv.meta.v1.BlockedRootEvent.event:type_name -> nokv.meta.v1.RootEvent
	9,  // 11: nokv.meta.v1.BlockedRootEventCatalog.entries:type_name -> nokv.meta.v1.BlockedRootEvent
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_meta_recovery_proto_init() }
func file_meta_recovery_proto_init() {
	if File_meta_recovery_proto != nil {
		return
	}
	file_meta_descriptor_proto_init()
	file_meta_region_proto_init()
	file_meta_root_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_recovery_proto_rawDesc), len(file_meta_recovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_recovery_proto_goTypes,
		DependencyIndexes: file_meta_recovery_proto_depIdxs,
		MessageInfos:      file_meta_recovery_proto_msgTypes,
	}.Build()
	File_meta_recovery_proto = out.File
	file_meta_recovery_proto_goTypes = nil
	file_meta_recovery_proto_depIdxs = nil
}
