// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meta/recovery.proto

package metapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicaLocalState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	LocalPeerId   uint64                 `protobuf:"varint,2,opt,name=local_peer_id,json=localPeerId,proto3" json:"local_peer_id,omitempty"`
	State         RegionReplicaState     `protobuf:"varint,3,opt,name=state,proto3,enum=nokv.meta.v1.RegionReplicaState" json:"state,omitempty"`
	Descriptor_   *RegionDescriptor      `protobuf:"bytes,4,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	LastApplied   uint64                 `protobuf:"varint,5,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	LastTerm      uint64                 `protobuf:"varint,6,opt,name=last_term,json=lastTerm,proto3" json:"last_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaLocalState) Reset() {
	*x = ReplicaLocalState{}
	mi := &file_meta_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaLocalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaLocalState) ProtoMessage() {}

func (x *ReplicaLocalState) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaLocalState.ProtoReflect.Descriptor instead.
func (*ReplicaLocalState) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaLocalState) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *ReplicaLocalState) GetLocalPeerId() uint64 {
	if x != nil {
		return x.LocalPeerId
	}
	return 0
}

func (x *ReplicaLocalState) GetState() RegionReplicaState {
	if x != nil {
		return x.State
	}
	return RegionReplicaState_REGION_REPLICA_STATE_UNSPECIFIED
}

func (x *ReplicaLocalState) GetDescriptor_() *RegionDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *ReplicaLocalState) GetLastApplied() uint64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *ReplicaLocalState) GetLastTerm() uint64 {
	if x != nil {
		return x.LastTerm
	}
	return 0
}

type RaftProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Segment         uint32                 `protobuf:"varint,2,opt,name=segment,proto3" json:"segment,omitempty"`
	Offset          uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	AppliedIndex    uint64                 `protobuf:"varint,4,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	AppliedTerm     uint64                 `protobuf:"varint,5,opt,name=applied_term,json=appliedTerm,proto3" json:"applied_term,omitempty"`
	Committed       uint64                 `protobuf:"varint,6,opt,name=committed,proto3" json:"committed,omitempty"`
	SnapshotIndex   uint64                 `protobuf:"varint,7,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	SnapshotTerm    uint64                 `protobuf:"varint,8,opt,name=snapshot_term,json=snapshotTerm,proto3" json:"snapshot_term,omitempty"`
	TruncatedIndex  uint64                 `protobuf:"varint,9,opt,name=truncated_index,json=truncatedIndex,proto3" json:"truncated_index,omitempty"`
	TruncatedTerm   uint64                 `protobuf:"varint,10,opt,name=truncated_term,json=truncatedTerm,proto3" json:"truncated_term,omitempty"`
	SegmentIndex    uint64                 `protobuf:"varint,11,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"`
	TruncatedOffset uint64                 `protobuf:"varint,12,opt,name=truncated_offset,json=truncatedOffset,proto3" json:"truncated_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RaftProgress) Reset() {
	*x = RaftProgress{}
	mi := &file_meta_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftProgress) ProtoMessage() {}

func (x *RaftProgress) ProtoReflect() protoreflect.Message {
	mi := &file_meta_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftProgress.ProtoReflect.Descriptor instead.
func (*RaftProgress) Descriptor() ([]byte, []int) {
	return file_meta_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *RaftProgress) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RaftProgress) GetSegment() uint32 {
	if x != nil {
		return x.Segment
	}
	return 0
}

func (x *RaftProgress) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RaftProgress) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *RaftProgress) GetAppliedTerm() uint64 {
	if x != nil {
		return x.AppliedTerm
	}
	return 0
}

func (x *RaftProgress) GetCommitted() uint64 {
	if x != nil {
		return x.Committed
	}
	return 0
}

func (x *RaftProgress) GetSnapshotIndex() uint64 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

func (x *RaftProgress) GetSnapshotTerm() uint64 {
	if x != nil {
		return x.SnapshotTerm
	}
	return 0
}

func (x *RaftProgress) GetTruncatedIndex() uint64 {
	if x != nil {
		return x.TruncatedIndex
	}
	return 0
}

func (x *RaftProgress) GetTruncatedTerm() uint64 {
	if x != nil {
		return x.TruncatedTerm
	}
	return 0
}

func (x *RaftProgress) GetSegmentIndex() uint64 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *RaftProgress) GetTruncatedOffset() uint64 {
	if x != nil {
		return x.TruncatedOffset
	}
	return 0
}

var File_meta_recovery_proto protoreflect.FileDescriptor

const file_meta_recovery_proto_rawDesc = "" +
	"\n" +
	"\x13meta/recovery.proto\x12\fnokv.meta.v1\x1a\x15meta/descriptor.proto\x1a\x11meta/region.proto\"\x8c\x02\n" +
	"\x11ReplicaLocalState\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\"\n" +
	"\rlocal_peer_id\x18\x02 \x01(\x04R\vlocalPeerId\x126\n" +
	"\x05state\x18\x03 \x01(\x0e2 .nokv.meta.v1.RegionReplicaStateR\x05state\x12>\n" +
	"\n" +
	"descriptor\x18\x04 \x01(\v2\x1e.nokv.meta.v1.RegionDescriptorR\n" +
	"descriptor\x12!\n" +
	"\flast_applied\x18\x05 \x01(\x04R\vlastApplied\x12\x1b\n" +
	"\tlast_term\x18\x06 \x01(\x04R\blastTerm\"\xad\x03\n" +
	"\fRaftProgress\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x18\n" +
	"\asegment\x18\x02 \x01(\rR\asegment\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12#\n" +
	"\rapplied_index\x18\x04 \x01(\x04R\fappliedIndex\x12!\n" +
	"\fapplied_term\x18\x05 \x01(\x04R\vappliedTerm\x12\x1c\n" +
	"\tcommitted\x18\x06 \x01(\x04R\tcommitted\x12%\n" +
	"\x0esnapshot_index\x18\a \x01(\x04R\rsnapshotIndex\x12#\n" +
	"\rsnapshot_term\x18\b \x01(\x04R\fsnapshotTerm\x12'\n" +
	"\x0ftruncated_index\x18\t \x01(\x04R\x0etruncatedIndex\x12%\n" +
	"\x0etruncated_term\x18\n" +
	" \x01(\x04R\rtruncatedTerm\x12#\n" +
	"\rsegment_index\x18\v \x01(\x04R\fsegmentIndex\x12)\n" +
	"\x10truncated_offset\x18\f \x01(\x04R\x0ftruncatedOffsetB,Z*github.com/feichai0017/NoKV/pb/meta;metapbb\x06proto3"

var (
	file_meta_recovery_proto_rawDescOnce sync.Once
	file_meta_recovery_proto_rawDescData []byte
)

func file_meta_recovery_proto_rawDescGZIP() []byte {
	file_meta_recovery_proto_rawDescOnce.Do(func() {
		file_meta_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_recovery_proto_rawDesc), len(file_meta_recovery_proto_rawDesc)))
	})
	return file_meta_recovery_proto_rawDescData
}

var file_meta_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meta_recovery_proto_goTypes = []any{
	(*ReplicaLocalState)(nil), // 0: nokv.meta.v1.ReplicaLocalState
	(*RaftProgress)(nil),      // 1: nokv.meta.v1.RaftProgress
	(RegionReplicaState)(0),   // 2: nokv.meta.v1.RegionReplicaState
	(*RegionDescriptor)(nil),  // 3: nokv.meta.v1.RegionDescriptor
}
var file_meta_recovery_proto_depIdxs = []int32{
	2, // 0: nokv.meta.v1.ReplicaLocalState.state:type_name -> nokv.meta.v1.RegionReplicaState
	3, // 1: nokv.meta.v1.ReplicaLocalState.descriptor:type_name -> nokv.meta.v1.RegionDescriptor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meta_recovery_proto_init() }
func file_meta_recovery_proto_init() {
	if File_meta_recovery_proto != nil {
		return
	}
	file_meta_descriptor_proto_init()
	file_meta_region_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_recovery_proto_rawDesc), len(file_meta_recovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_recovery_proto_goTypes,
		DependencyIndexes: file_meta_recovery_proto_depIdxs,
		MessageInfos:      file_meta_recovery_proto_msgTypes,
	}.Build()
	File_meta_recovery_proto = out.File
	file_meta_recovery_proto_goTypes = nil
	file_meta_recovery_proto_depIdxs = nil
}
