// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meta/region.proto

package metapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegionReplicaState int32

const (
	RegionReplicaState_REGION_REPLICA_STATE_UNSPECIFIED RegionReplicaState = 0
	RegionReplicaState_REGION_REPLICA_STATE_NEW         RegionReplicaState = 1
	RegionReplicaState_REGION_REPLICA_STATE_RUNNING     RegionReplicaState = 2
	RegionReplicaState_REGION_REPLICA_STATE_REMOVING    RegionReplicaState = 3
	RegionReplicaState_REGION_REPLICA_STATE_TOMBSTONE   RegionReplicaState = 4
)

// Enum value maps for RegionReplicaState.
var (
	RegionReplicaState_name = map[int32]string{
		0: "REGION_REPLICA_STATE_UNSPECIFIED",
		1: "REGION_REPLICA_STATE_NEW",
		2: "REGION_REPLICA_STATE_RUNNING",
		3: "REGION_REPLICA_STATE_REMOVING",
		4: "REGION_REPLICA_STATE_TOMBSTONE",
	}
	RegionReplicaState_value = map[string]int32{
		"REGION_REPLICA_STATE_UNSPECIFIED": 0,
		"REGION_REPLICA_STATE_NEW":         1,
		"REGION_REPLICA_STATE_RUNNING":     2,
		"REGION_REPLICA_STATE_REMOVING":    3,
		"REGION_REPLICA_STATE_TOMBSTONE":   4,
	}
)

func (x RegionReplicaState) Enum() *RegionReplicaState {
	p := new(RegionReplicaState)
	*p = x
	return p
}

func (x RegionReplicaState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionReplicaState) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_region_proto_enumTypes[0].Descriptor()
}

func (RegionReplicaState) Type() protoreflect.EnumType {
	return &file_meta_region_proto_enumTypes[0]
}

func (x RegionReplicaState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegionReplicaState.Descriptor instead.
func (RegionReplicaState) EnumDescriptor() ([]byte, []int) {
	return file_meta_region_proto_rawDescGZIP(), []int{0}
}

type RegionEpoch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ConfVersion   uint64                 `protobuf:"varint,2,opt,name=conf_version,json=confVersion,proto3" json:"conf_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionEpoch) Reset() {
	*x = RegionEpoch{}
	mi := &file_meta_region_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionEpoch) ProtoMessage() {}

func (x *RegionEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_meta_region_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionEpoch.ProtoReflect.Descriptor instead.
func (*RegionEpoch) Descriptor() ([]byte, []int) {
	return file_meta_region_proto_rawDescGZIP(), []int{0}
}

func (x *RegionEpoch) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RegionEpoch) GetConfVersion() uint64 {
	if x != nil {
		return x.ConfVersion
	}
	return 0
}

type RegionPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	PeerId        uint64                 `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionPeer) Reset() {
	*x = RegionPeer{}
	mi := &file_meta_region_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionPeer) ProtoMessage() {}

func (x *RegionPeer) ProtoReflect() protoreflect.Message {
	mi := &file_meta_region_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionPeer.ProtoReflect.Descriptor instead.
func (*RegionPeer) Descriptor() ([]byte, []int) {
	return file_meta_region_proto_rawDescGZIP(), []int{1}
}

func (x *RegionPeer) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *RegionPeer) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

var File_meta_region_proto protoreflect.FileDescriptor

const file_meta_region_proto_rawDesc = "" +
	"\n" +
	"\x11meta/region.proto\x12\fnokv.meta.v1\"J\n" +
	"\vRegionEpoch\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12!\n" +
	"\fconf_version\x18\x02 \x01(\x04R\vconfVersion\"@\n" +
	"\n" +
	"RegionPeer\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x04R\x06peerId*\xc1\x01\n" +
	"\x12RegionReplicaState\x12$\n" +
	" REGION_REPLICA_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REGION_REPLICA_STATE_NEW\x10\x01\x12 \n" +
	"\x1cREGION_REPLICA_STATE_RUNNING\x10\x02\x12!\n" +
	"\x1dREGION_REPLICA_STATE_REMOVING\x10\x03\x12\"\n" +
	"\x1eREGION_REPLICA_STATE_TOMBSTONE\x10\x04B,Z*github.com/feichai0017/NoKV/pb/meta;metapbb\x06proto3"

var (
	file_meta_region_proto_rawDescOnce sync.Once
	file_meta_region_proto_rawDescData []byte
)

func file_meta_region_proto_rawDescGZIP() []byte {
	file_meta_region_proto_rawDescOnce.Do(func() {
		file_meta_region_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_region_proto_rawDesc), len(file_meta_region_proto_rawDesc)))
	})
	return file_meta_region_proto_rawDescData
}

var file_meta_region_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_region_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meta_region_proto_goTypes = []any{
	(RegionReplicaState)(0), // 0: nokv.meta.v1.RegionReplicaState
	(*RegionEpoch)(nil),     // 1: nokv.meta.v1.RegionEpoch
	(*RegionPeer)(nil),      // 2: nokv.meta.v1.RegionPeer
}
var file_meta_region_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_region_proto_init() }
func file_meta_region_proto_init() {
	if File_meta_region_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_region_proto_rawDesc), len(file_meta_region_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_region_proto_goTypes,
		DependencyIndexes: file_meta_region_proto_depIdxs,
		EnumInfos:         file_meta_region_proto_enumTypes,
		MessageInfos:      file_meta_region_proto_msgTypes,
	}.Build()
	File_meta_region_proto = out.File
	file_meta_region_proto_goTypes = nil
	file_meta_region_proto_depIdxs = nil
}
