// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: meta/root.proto

package metapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataRoot_Snapshot_FullMethodName                = "/nokv.meta.v1.MetadataRoot/Snapshot"
	MetadataRoot_Append_FullMethodName                  = "/nokv.meta.v1.MetadataRoot/Append"
	MetadataRoot_FenceAllocator_FullMethodName          = "/nokv.meta.v1.MetadataRoot/FenceAllocator"
	MetadataRoot_Status_FullMethodName                  = "/nokv.meta.v1.MetadataRoot/Status"
	MetadataRoot_ApplyCoordinatorLease_FullMethodName   = "/nokv.meta.v1.MetadataRoot/ApplyCoordinatorLease"
	MetadataRoot_ApplyCoordinatorClosure_FullMethodName = "/nokv.meta.v1.MetadataRoot/ApplyCoordinatorClosure"
	MetadataRoot_ObserveCommitted_FullMethodName        = "/nokv.meta.v1.MetadataRoot/ObserveCommitted"
	MetadataRoot_ObserveTail_FullMethodName             = "/nokv.meta.v1.MetadataRoot/ObserveTail"
	MetadataRoot_WaitTail_FullMethodName                = "/nokv.meta.v1.MetadataRoot/WaitTail"
)

// MetadataRootClient is the client API for MetadataRoot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataRootClient interface {
	Snapshot(ctx context.Context, in *MetadataRootSnapshotRequest, opts ...grpc.CallOption) (*MetadataRootSnapshotResponse, error)
	Append(ctx context.Context, in *MetadataRootAppendRequest, opts ...grpc.CallOption) (*MetadataRootAppendResponse, error)
	FenceAllocator(ctx context.Context, in *MetadataRootFenceAllocatorRequest, opts ...grpc.CallOption) (*MetadataRootFenceAllocatorResponse, error)
	Status(ctx context.Context, in *MetadataRootStatusRequest, opts ...grpc.CallOption) (*MetadataRootStatusResponse, error)
	ApplyCoordinatorLease(ctx context.Context, in *MetadataRootApplyCoordinatorLeaseRequest, opts ...grpc.CallOption) (*MetadataRootApplyCoordinatorLeaseResponse, error)
	ApplyCoordinatorClosure(ctx context.Context, in *MetadataRootApplyCoordinatorClosureRequest, opts ...grpc.CallOption) (*MetadataRootApplyCoordinatorClosureResponse, error)
	ObserveCommitted(ctx context.Context, in *MetadataRootObserveCommittedRequest, opts ...grpc.CallOption) (*MetadataRootObserveCommittedResponse, error)
	ObserveTail(ctx context.Context, in *MetadataRootObserveTailRequest, opts ...grpc.CallOption) (*MetadataRootObserveTailResponse, error)
	WaitTail(ctx context.Context, in *MetadataRootWaitTailRequest, opts ...grpc.CallOption) (*MetadataRootWaitTailResponse, error)
}

type metadataRootClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataRootClient(cc grpc.ClientConnInterface) MetadataRootClient {
	return &metadataRootClient{cc}
}

func (c *metadataRootClient) Snapshot(ctx context.Context, in *MetadataRootSnapshotRequest, opts ...grpc.CallOption) (*MetadataRootSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootSnapshotResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataRootClient) Append(ctx context.Context, in *MetadataRootAppendRequest, opts ...grpc.CallOption) (*MetadataRootAppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootAppendResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataRootClient) FenceAllocator(ctx context.Context, in *MetadataRootFenceAllocatorRequest, opts ...grpc.CallOption) (*MetadataRootFenceAllocatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootFenceAllocatorResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_FenceAllocator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataRootClient) Status(ctx context.Context, in *MetadataRootStatusRequest, opts ...grpc.CallOption) (*MetadataRootStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootStatusResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataRootClient) ApplyCoordinatorLease(ctx context.Context, in *MetadataRootApplyCoordinatorLeaseRequest, opts ...grpc.CallOption) (*MetadataRootApplyCoordinatorLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootApplyCoordinatorLeaseResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_ApplyCoordinatorLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataRootClient) ApplyCoordinatorClosure(ctx context.Context, in *MetadataRootApplyCoordinatorClosureRequest, opts ...grpc.CallOption) (*MetadataRootApplyCoordinatorClosureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootApplyCoordinatorClosureResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_ApplyCoordinatorClosure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataRootClient) ObserveCommitted(ctx context.Context, in *MetadataRootObserveCommittedRequest, opts ...grpc.CallOption) (*MetadataRootObserveCommittedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootObserveCommittedResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_ObserveCommitted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataRootClient) ObserveTail(ctx context.Context, in *MetadataRootObserveTailRequest, opts ...grpc.CallOption) (*MetadataRootObserveTailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootObserveTailResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_ObserveTail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataRootClient) WaitTail(ctx context.Context, in *MetadataRootWaitTailRequest, opts ...grpc.CallOption) (*MetadataRootWaitTailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataRootWaitTailResponse)
	err := c.cc.Invoke(ctx, MetadataRoot_WaitTail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataRootServer is the server API for MetadataRoot service.
// All implementations should embed UnimplementedMetadataRootServer
// for forward compatibility.
type MetadataRootServer interface {
	Snapshot(context.Context, *MetadataRootSnapshotRequest) (*MetadataRootSnapshotResponse, error)
	Append(context.Context, *MetadataRootAppendRequest) (*MetadataRootAppendResponse, error)
	FenceAllocator(context.Context, *MetadataRootFenceAllocatorRequest) (*MetadataRootFenceAllocatorResponse, error)
	Status(context.Context, *MetadataRootStatusRequest) (*MetadataRootStatusResponse, error)
	ApplyCoordinatorLease(context.Context, *MetadataRootApplyCoordinatorLeaseRequest) (*MetadataRootApplyCoordinatorLeaseResponse, error)
	ApplyCoordinatorClosure(context.Context, *MetadataRootApplyCoordinatorClosureRequest) (*MetadataRootApplyCoordinatorClosureResponse, error)
	ObserveCommitted(context.Context, *MetadataRootObserveCommittedRequest) (*MetadataRootObserveCommittedResponse, error)
	ObserveTail(context.Context, *MetadataRootObserveTailRequest) (*MetadataRootObserveTailResponse, error)
	WaitTail(context.Context, *MetadataRootWaitTailRequest) (*MetadataRootWaitTailResponse, error)
}

// UnimplementedMetadataRootServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataRootServer struct{}

func (UnimplementedMetadataRootServer) Snapshot(context.Context, *MetadataRootSnapshotRequest) (*MetadataRootSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedMetadataRootServer) Append(context.Context, *MetadataRootAppendRequest) (*MetadataRootAppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedMetadataRootServer) FenceAllocator(context.Context, *MetadataRootFenceAllocatorRequest) (*MetadataRootFenceAllocatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FenceAllocator not implemented")
}
func (UnimplementedMetadataRootServer) Status(context.Context, *MetadataRootStatusRequest) (*MetadataRootStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMetadataRootServer) ApplyCoordinatorLease(context.Context, *MetadataRootApplyCoordinatorLeaseRequest) (*MetadataRootApplyCoordinatorLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCoordinatorLease not implemented")
}
func (UnimplementedMetadataRootServer) ApplyCoordinatorClosure(context.Context, *MetadataRootApplyCoordinatorClosureRequest) (*MetadataRootApplyCoordinatorClosureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCoordinatorClosure not implemented")
}
func (UnimplementedMetadataRootServer) ObserveCommitted(context.Context, *MetadataRootObserveCommittedRequest) (*MetadataRootObserveCommittedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObserveCommitted not implemented")
}
func (UnimplementedMetadataRootServer) ObserveTail(context.Context, *MetadataRootObserveTailRequest) (*MetadataRootObserveTailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObserveTail not implemented")
}
func (UnimplementedMetadataRootServer) WaitTail(context.Context, *MetadataRootWaitTailRequest) (*MetadataRootWaitTailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitTail not implemented")
}
func (UnimplementedMetadataRootServer) testEmbeddedByValue() {}

// UnsafeMetadataRootServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataRootServer will
// result in compilation errors.
type UnsafeMetadataRootServer interface {
	mustEmbedUnimplementedMetadataRootServer()
}

func RegisterMetadataRootServer(s grpc.ServiceRegistrar, srv MetadataRootServer) {
	// If the following call panics, it indicates UnimplementedMetadataRootServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataRoot_ServiceDesc, srv)
}

func _MetadataRoot_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).Snapshot(ctx, req.(*MetadataRootSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataRoot_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).Append(ctx, req.(*MetadataRootAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataRoot_FenceAllocator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootFenceAllocatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).FenceAllocator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_FenceAllocator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).FenceAllocator(ctx, req.(*MetadataRootFenceAllocatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataRoot_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).Status(ctx, req.(*MetadataRootStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataRoot_ApplyCoordinatorLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootApplyCoordinatorLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).ApplyCoordinatorLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_ApplyCoordinatorLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).ApplyCoordinatorLease(ctx, req.(*MetadataRootApplyCoordinatorLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataRoot_ApplyCoordinatorClosure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootApplyCoordinatorClosureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).ApplyCoordinatorClosure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_ApplyCoordinatorClosure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).ApplyCoordinatorClosure(ctx, req.(*MetadataRootApplyCoordinatorClosureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataRoot_ObserveCommitted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootObserveCommittedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).ObserveCommitted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_ObserveCommitted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).ObserveCommitted(ctx, req.(*MetadataRootObserveCommittedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataRoot_ObserveTail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootObserveTailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).ObserveTail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_ObserveTail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).ObserveTail(ctx, req.(*MetadataRootObserveTailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataRoot_WaitTail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRootWaitTailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataRootServer).WaitTail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataRoot_WaitTail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataRootServer).WaitTail(ctx, req.(*MetadataRootWaitTailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataRoot_ServiceDesc is the grpc.ServiceDesc for MetadataRoot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataRoot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nokv.meta.v1.MetadataRoot",
	HandlerType: (*MetadataRootServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Snapshot",
			Handler:    _MetadataRoot_Snapshot_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _MetadataRoot_Append_Handler,
		},
		{
			MethodName: "FenceAllocator",
			Handler:    _MetadataRoot_FenceAllocator_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _MetadataRoot_Status_Handler,
		},
		{
			MethodName: "ApplyCoordinatorLease",
			Handler:    _MetadataRoot_ApplyCoordinatorLease_Handler,
		},
		{
			MethodName: "ApplyCoordinatorClosure",
			Handler:    _MetadataRoot_ApplyCoordinatorClosure_Handler,
		},
		{
			MethodName: "ObserveCommitted",
			Handler:    _MetadataRoot_ObserveCommitted_Handler,
		},
		{
			MethodName: "ObserveTail",
			Handler:    _MetadataRoot_ObserveTail_Handler,
		},
		{
			MethodName: "WaitTail",
			Handler:    _MetadataRoot_WaitTail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meta/root.proto",
}
