// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: coordinator/coordinator.proto

package coordpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coordinator_StoreHeartbeat_FullMethodName   = "/nokv.coordinator.v1.Coordinator/StoreHeartbeat"
	Coordinator_RegionLiveness_FullMethodName   = "/nokv.coordinator.v1.Coordinator/RegionLiveness"
	Coordinator_PublishRootEvent_FullMethodName = "/nokv.coordinator.v1.Coordinator/PublishRootEvent"
	Coordinator_ListTransitions_FullMethodName  = "/nokv.coordinator.v1.Coordinator/ListTransitions"
	Coordinator_AssessRootEvent_FullMethodName  = "/nokv.coordinator.v1.Coordinator/AssessRootEvent"
	Coordinator_RemoveRegion_FullMethodName     = "/nokv.coordinator.v1.Coordinator/RemoveRegion"
	Coordinator_GetRegionByKey_FullMethodName   = "/nokv.coordinator.v1.Coordinator/GetRegionByKey"
	Coordinator_AllocID_FullMethodName          = "/nokv.coordinator.v1.Coordinator/AllocID"
	Coordinator_Tso_FullMethodName              = "/nokv.coordinator.v1.Coordinator/Tso"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorClient interface {
	StoreHeartbeat(ctx context.Context, in *StoreHeartbeatRequest, opts ...grpc.CallOption) (*StoreHeartbeatResponse, error)
	RegionLiveness(ctx context.Context, in *RegionLivenessRequest, opts ...grpc.CallOption) (*RegionLivenessResponse, error)
	PublishRootEvent(ctx context.Context, in *PublishRootEventRequest, opts ...grpc.CallOption) (*PublishRootEventResponse, error)
	ListTransitions(ctx context.Context, in *ListTransitionsRequest, opts ...grpc.CallOption) (*ListTransitionsResponse, error)
	AssessRootEvent(ctx context.Context, in *AssessRootEventRequest, opts ...grpc.CallOption) (*AssessRootEventResponse, error)
	RemoveRegion(ctx context.Context, in *RemoveRegionRequest, opts ...grpc.CallOption) (*RemoveRegionResponse, error)
	GetRegionByKey(ctx context.Context, in *GetRegionByKeyRequest, opts ...grpc.CallOption) (*GetRegionByKeyResponse, error)
	AllocID(ctx context.Context, in *AllocIDRequest, opts ...grpc.CallOption) (*AllocIDResponse, error)
	Tso(ctx context.Context, in *TsoRequest, opts ...grpc.CallOption) (*TsoResponse, error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) StoreHeartbeat(ctx context.Context, in *StoreHeartbeatRequest, opts ...grpc.CallOption) (*StoreHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreHeartbeatResponse)
	err := c.cc.Invoke(ctx, Coordinator_StoreHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) RegionLiveness(ctx context.Context, in *RegionLivenessRequest, opts ...grpc.CallOption) (*RegionLivenessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionLivenessResponse)
	err := c.cc.Invoke(ctx, Coordinator_RegionLiveness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PublishRootEvent(ctx context.Context, in *PublishRootEventRequest, opts ...grpc.CallOption) (*PublishRootEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishRootEventResponse)
	err := c.cc.Invoke(ctx, Coordinator_PublishRootEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ListTransitions(ctx context.Context, in *ListTransitionsRequest, opts ...grpc.CallOption) (*ListTransitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransitionsResponse)
	err := c.cc.Invoke(ctx, Coordinator_ListTransitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) AssessRootEvent(ctx context.Context, in *AssessRootEventRequest, opts ...grpc.CallOption) (*AssessRootEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessRootEventResponse)
	err := c.cc.Invoke(ctx, Coordinator_AssessRootEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) RemoveRegion(ctx context.Context, in *RemoveRegionRequest, opts ...grpc.CallOption) (*RemoveRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRegionResponse)
	err := c.cc.Invoke(ctx, Coordinator_RemoveRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetRegionByKey(ctx context.Context, in *GetRegionByKeyRequest, opts ...grpc.CallOption) (*GetRegionByKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegionByKeyResponse)
	err := c.cc.Invoke(ctx, Coordinator_GetRegionByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) AllocID(ctx context.Context, in *AllocIDRequest, opts ...grpc.CallOption) (*AllocIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocIDResponse)
	err := c.cc.Invoke(ctx, Coordinator_AllocID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) Tso(ctx context.Context, in *TsoRequest, opts ...grpc.CallOption) (*TsoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TsoResponse)
	err := c.cc.Invoke(ctx, Coordinator_Tso_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
// All implementations should embed UnimplementedCoordinatorServer
// for forward compatibility.
type CoordinatorServer interface {
	StoreHeartbeat(context.Context, *StoreHeartbeatRequest) (*StoreHeartbeatResponse, error)
	RegionLiveness(context.Context, *RegionLivenessRequest) (*RegionLivenessResponse, error)
	PublishRootEvent(context.Context, *PublishRootEventRequest) (*PublishRootEventResponse, error)
	ListTransitions(context.Context, *ListTransitionsRequest) (*ListTransitionsResponse, error)
	AssessRootEvent(context.Context, *AssessRootEventRequest) (*AssessRootEventResponse, error)
	RemoveRegion(context.Context, *RemoveRegionRequest) (*RemoveRegionResponse, error)
	GetRegionByKey(context.Context, *GetRegionByKeyRequest) (*GetRegionByKeyResponse, error)
	AllocID(context.Context, *AllocIDRequest) (*AllocIDResponse, error)
	Tso(context.Context, *TsoRequest) (*TsoResponse, error)
}

// UnimplementedCoordinatorServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServer struct{}

func (UnimplementedCoordinatorServer) StoreHeartbeat(context.Context, *StoreHeartbeatRequest) (*StoreHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreHeartbeat not implemented")
}
func (UnimplementedCoordinatorServer) RegionLiveness(context.Context, *RegionLivenessRequest) (*RegionLivenessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegionLiveness not implemented")
}
func (UnimplementedCoordinatorServer) PublishRootEvent(context.Context, *PublishRootEventRequest) (*PublishRootEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishRootEvent not implemented")
}
func (UnimplementedCoordinatorServer) ListTransitions(context.Context, *ListTransitionsRequest) (*ListTransitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransitions not implemented")
}
func (UnimplementedCoordinatorServer) AssessRootEvent(context.Context, *AssessRootEventRequest) (*AssessRootEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssessRootEvent not implemented")
}
func (UnimplementedCoordinatorServer) RemoveRegion(context.Context, *RemoveRegionRequest) (*RemoveRegionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRegion not implemented")
}
func (UnimplementedCoordinatorServer) GetRegionByKey(context.Context, *GetRegionByKeyRequest) (*GetRegionByKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegionByKey not implemented")
}
func (UnimplementedCoordinatorServer) AllocID(context.Context, *AllocIDRequest) (*AllocIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocID not implemented")
}
func (UnimplementedCoordinatorServer) Tso(context.Context, *TsoRequest) (*TsoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tso not implemented")
}
func (UnimplementedCoordinatorServer) testEmbeddedByValue() {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_StoreHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).StoreHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_StoreHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).StoreHeartbeat(ctx, req.(*StoreHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_RegionLiveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionLivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).RegionLiveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_RegionLiveness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).RegionLiveness(ctx, req.(*RegionLivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PublishRootEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRootEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PublishRootEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_PublishRootEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PublishRootEvent(ctx, req.(*PublishRootEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ListTransitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ListTransitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ListTransitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ListTransitions(ctx, req.(*ListTransitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_AssessRootEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessRootEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).AssessRootEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_AssessRootEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).AssessRootEvent(ctx, req.(*AssessRootEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_RemoveRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).RemoveRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_RemoveRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).RemoveRegion(ctx, req.(*RemoveRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetRegionByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegionByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetRegionByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_GetRegionByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetRegionByKey(ctx, req.(*GetRegionByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_AllocID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).AllocID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_AllocID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).AllocID(ctx, req.(*AllocIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_Tso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TsoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Tso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_Tso_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Tso(ctx, req.(*TsoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nokv.coordinator.v1.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreHeartbeat",
			Handler:    _Coordinator_StoreHeartbeat_Handler,
		},
		{
			MethodName: "RegionLiveness",
			Handler:    _Coordinator_RegionLiveness_Handler,
		},
		{
			MethodName: "PublishRootEvent",
			Handler:    _Coordinator_PublishRootEvent_Handler,
		},
		{
			MethodName: "ListTransitions",
			Handler:    _Coordinator_ListTransitions_Handler,
		},
		{
			MethodName: "AssessRootEvent",
			Handler:    _Coordinator_AssessRootEvent_Handler,
		},
		{
			MethodName: "RemoveRegion",
			Handler:    _Coordinator_RemoveRegion_Handler,
		},
		{
			MethodName: "GetRegionByKey",
			Handler:    _Coordinator_GetRegionByKey_Handler,
		},
		{
			MethodName: "AllocID",
			Handler:    _Coordinator_AllocID_Handler,
		},
		{
			MethodName: "Tso",
			Handler:    _Coordinator_Tso_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator/coordinator.proto",
}
