// Copyright 2024-2026 The NoKV Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by fsmeta-opgen; DO NOT EDIT.

package compile

import "github.com/feichai0017/NoKV/fsmeta/model"

func compileAOTDelta(delta SemanticDelta) (CompiledOp, error) {
	switch delta.Kind {
	case model.OperationCreate:
		return compileCreateCompiledOp(delta)
	case model.OperationUpdateInode:
		return compileUpdateInodeCompiledOp(delta)
	case model.OperationLookup:
		return compileLookupCompiledOp(delta)
	case model.OperationReadDir:
		return compileReadDirCompiledOp(delta)
	case model.OperationSnapshotSubtree:
		return compileSnapshotSubtreeCompiledOp(delta)
	case model.OperationRename:
		return compileRenameCompiledOp(delta)
	case model.OperationRenameReplace:
		return compileRenameReplaceCompiledOp(delta)
	case model.OperationRenameSubtree:
		return compileRenameSubtreeCompiledOp(delta)
	case model.OperationLink:
		return compileLinkCompiledOp(delta)
	case model.OperationUnlink:
		return compileUnlinkCompiledOp(delta)
	case model.OperationRemove:
		return compileRemoveCompiledOp(delta)
	case model.OperationRemoveDirectory:
		return compileRemoveDirectoryCompiledOp(delta)
	case model.OperationOpenWriteSession:
		return compileOpenWriteSessionCompiledOp(delta)
	case model.OperationHeartbeatSession:
		return compileHeartbeatWriteSessionCompiledOp(delta)
	case model.OperationCloseSession:
		return compileCloseWriteSessionCompiledOp(delta)
	case model.OperationExpireSessions:
		return compileExpireWriteSessionsCompiledOp(delta)
	default:
		return CompiledOp{}, model.ErrInvalidRequest
	}
}
