// Copyright 2024-2026 The NoKV Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by fsmeta-opgen; DO NOT EDIT.

package compile

import "github.com/feichai0017/NoKV/fsmeta"

func compileAOTDelta(delta SemanticDelta) (CompiledOp, error) {
	switch delta.Kind {
	case fsmeta.OperationCreate:
		return compileCreateCompiledOp(delta)
	case fsmeta.OperationUpdateInode:
		return compileUpdateInodeCompiledOp(delta)
	case fsmeta.OperationLookup:
		return compileLookupCompiledOp(delta)
	case fsmeta.OperationReadDir:
		return compileReadDirCompiledOp(delta)
	case fsmeta.OperationSnapshotSubtree:
		return compileSnapshotSubtreeCompiledOp(delta)
	case fsmeta.OperationRename:
		return compileRenameCompiledOp(delta)
	case fsmeta.OperationRenameSubtree:
		return compileRenameSubtreeCompiledOp(delta)
	case fsmeta.OperationLink:
		return compileLinkCompiledOp(delta)
	case fsmeta.OperationUnlink:
		return compileUnlinkCompiledOp(delta)
	case fsmeta.OperationRemove:
		return compileRemoveCompiledOp(delta)
	case fsmeta.OperationRemoveDirectory:
		return compileRemoveDirectoryCompiledOp(delta)
	case fsmeta.OperationOpenWriteSession:
		return compileOpenWriteSessionCompiledOp(delta)
	case fsmeta.OperationHeartbeatSession:
		return compileHeartbeatWriteSessionCompiledOp(delta)
	case fsmeta.OperationCloseSession:
		return compileCloseWriteSessionCompiledOp(delta)
	case fsmeta.OperationExpireSessions:
		return compileExpireWriteSessionsCompiledOp(delta)
	default:
		return CompiledOp{}, fsmeta.ErrInvalidRequest
	}
}
