// Copyright 2024-2026 The NoKV Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by fsmeta-opgen; DO NOT EDIT.

package compile

import (
	"github.com/feichai0017/NoKV/fsmeta/layout"
	"github.com/feichai0017/NoKV/fsmeta/model"
)

func CompileLookupReadProgram(req model.LookupRequest, mount model.MountIdentity) (ReadProgram, error) {
	plan, err := layout.PlanLookup(req, mount)
	if err != nil {
		return ReadProgram{}, err
	}
	ref := keyRef(KeyAccessRead, plan.PrimaryKey)
	return ReadProgram{Kind: ReadProgramLookup, Plan: plan, Authority: AuthorityPlan{Scope: scopeFor(mount, []model.InodeID{req.Parent}, nil), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(plan.PrimaryKey))}, Key: cloneBytes(plan.PrimaryKey)}, nil
}

func CompileGetAttrReadProgram(mount model.MountIdentity, inode model.InodeID) (ReadProgram, error) {
	key, err := layout.EncodeInodeKey(mount, inode)
	if err != nil {
		return ReadProgram{}, err
	}
	ref := keyRef(KeyAccessRead, key)
	return ReadProgram{Kind: ReadProgramGetAttr, Plan: layout.OperationPlan{Kind: model.OperationGetAttr, Mount: mount.MountID, PrimaryKey: cloneBytes(key), ReadKeys: [][]byte{cloneBytes(key)}, ReadPrefixes: emptyKeySet, MutateKeys: emptyKeySet}, Authority: AuthorityPlan{Scope: scopeFor(mount, nil, []model.InodeID{inode}), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(key))}, Key: cloneBytes(key)}, nil
}

func CompileReadDirPlusInodeKeys(mount model.MountIdentity, dentries []model.DentryRecord) ([][]byte, error) {
	keys := make([][]byte, len(dentries))
	for i, dentry := range dentries {
		key, err := layout.EncodeInodeKey(mount, dentry.Inode)
		if err != nil {
			return nil, err
		}
		keys[i] = key
	}
	return keys, nil
}

func CompileReadSessionProgram(mount model.MountIdentity, inode model.InodeID, session model.SessionID) (ReadProgram, error) {
	key, err := layout.EncodeSessionKey(mount, inode, session)
	if err != nil {
		return ReadProgram{}, err
	}
	ref := keyRef(KeyAccessRead, key)
	return ReadProgram{Kind: ReadProgramReadSession, Plan: layout.OperationPlan{Kind: model.OperationReadSession, Mount: mount.MountID, PrimaryKey: cloneBytes(key), ReadKeys: [][]byte{cloneBytes(key)}, ReadPrefixes: emptyKeySet, MutateKeys: emptyKeySet}, Authority: AuthorityPlan{Scope: scopeFor(mount, nil, []model.InodeID{inode}), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(key))}, Key: cloneBytes(key)}, nil
}

func CompileReadSessionOwnerProgram(mount model.MountIdentity, inode model.InodeID) (ReadProgram, error) {
	key, err := layout.EncodeInodeSessionKey(mount, inode)
	if err != nil {
		return ReadProgram{}, err
	}
	ref := keyRef(KeyAccessRead, key)
	return ReadProgram{Kind: ReadProgramReadSession, Plan: layout.OperationPlan{Kind: model.OperationReadSession, Mount: mount.MountID, PrimaryKey: cloneBytes(key), ReadKeys: [][]byte{cloneBytes(key)}, ReadPrefixes: emptyKeySet, MutateKeys: emptyKeySet}, Authority: AuthorityPlan{Scope: scopeFor(mount, nil, []model.InodeID{inode}), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(key))}, Key: cloneBytes(key)}, nil
}

func CompileReadSessionKeyProgram(mount model.MountIdentity, key []byte) (ReadProgram, error) {
	parts, ok := layout.InspectKey(key)
	if !ok || parts.Kind != layout.KeyKindSession || parts.MountKeyID != mount.MountKeyID || parts.Inode == 0 {
		return ReadProgram{}, model.ErrInvalidRequest
	}
	ref := keyRef(KeyAccessRead, key)
	return ReadProgram{Kind: ReadProgramReadSession, Plan: layout.OperationPlan{Kind: model.OperationReadSession, Mount: mount.MountID, PrimaryKey: cloneBytes(key), ReadKeys: [][]byte{cloneBytes(key)}, ReadPrefixes: emptyKeySet, MutateKeys: emptyKeySet}, Authority: AuthorityPlan{Scope: scopeFor(mount, nil, []model.InodeID{parts.Inode}), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, EstimatedBytes: uint64(len(key))}, Key: cloneBytes(key)}, nil
}

func CompileDirectoryReadPlan(req model.ReadDirRequest, mount model.MountIdentity, includeOverlay, overlayOnly bool) (DirectoryReadPlan, error) {
	plan, err := layout.PlanReadDir(req, mount)
	if err != nil {
		return DirectoryReadPlan{}, err
	}
	if len(plan.ReadPrefixes) != 1 {
		return DirectoryReadPlan{}, model.ErrInvalidRequest
	}
	if overlayOnly {
		includeOverlay = true
	}
	ref := keyRef(KeyAccessReadPrefix, plan.ReadPrefixes[0])
	source := DirectoryReadSourceBase
	if overlayOnly {
		source = DirectoryReadSourceOverlayOnly
	} else if includeOverlay {
		source = DirectoryReadSourceOverlay
	}
	return DirectoryReadPlan{Plan: plan, Authority: AuthorityPlan{Scope: scopeFor(mount, []model.InodeID{req.Parent}, nil), Required: true, Fence: FenceActiveAuthority}, Footprint: KeyFootprint{Reads: []KeyRef{ref}, ConflictKeys: []KeyRef{ref}, HasPrefixRead: true, EstimatedBytes: uint64(len(plan.ReadPrefixes[0]))}, Prefix: cloneBytes(plan.ReadPrefixes[0]), StartKey: cloneBytes(plan.StartKey), Limit: plan.Limit, IncludeOverlay: includeOverlay, OverlayOnly: overlayOnly, Source: source}, nil
}
