// Copyright 2024-2026 The NoKV Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by fsmeta-opgen; DO NOT EDIT.

package compile

import (
	"crypto/sha256"

	"github.com/feichai0017/NoKV/fsmeta/layout"
	"github.com/feichai0017/NoKV/fsmeta/model"
)

type SnapshotSubtreeProgram struct {
	Compiled CompiledOp
}

func CompileSnapshotSubtreeProgram(req model.SnapshotSubtreeRequest, mount model.MountIdentity) (SnapshotSubtreeProgram, error) {
	plan, err := layout.PlanSnapshotSubtree(req, mount)
	if err != nil {
		return SnapshotSubtreeProgram{}, err
	}
	plan = canonicalPlan(plan)
	predicates := []Predicate{
		{Kind: PredicatePrefixScan, Key: plan.ReadPrefixes[0]},
	}
	effects := []WriteEffect(nil)
	delta := SemanticDelta{Kind: plan.Kind, Plan: plan, Authority: scopeFor(mount, []model.InodeID{req.RootInode}, nil), ReadPredicates: predicates, WriteEffects: effects, Eligibility: EligibilitySlowPath, SlowReason: SlowReasonDurabilityBarrier, DurabilityBarrier: true}
	if !validateSnapshotSubtreeSemanticDelta(delta) {
		return SnapshotSubtreeProgram{}, model.ErrInvalidRequest
	}
	compiled, err := compileSnapshotSubtreeCompiledOp(delta)
	if err != nil {
		return SnapshotSubtreeProgram{}, err
	}
	return SnapshotSubtreeProgram{Compiled: compiled}, nil
}

func validateSnapshotSubtreeSemanticDelta(delta SemanticDelta) bool {
	if delta.Kind != model.OperationSnapshotSubtree {
		return false
	}
	switch {
	case delta.Eligibility == EligibilitySlowPath && delta.SlowReason == SlowReasonDurabilityBarrier:
	default:
		return false
	}
	if !delta.DurabilityBarrier {
		return false
	}
	if delta.WatchAtSeal {
		return false
	}
	if len(delta.Authority.Parents) == 0 || len(delta.Authority.Parents) > 1 {
		return false
	}
	if len(delta.Authority.Inodes) != 0 {
		return false
	}
	if delta.Authority.Broad {
		return false
	}
	if delta.Authority.AllowOpaqueKeys {
		return false
	}
	if len(delta.ReadPredicates) != 1 {
		return false
	}
	if delta.ReadPredicates[0].Kind != PredicatePrefixScan {
		return false
	}
	if !semanticKeyBindingMatches(delta, delta.ReadPredicates[0].Key, "read_prefix[0]") {
		return false
	}
	if len(delta.WriteEffects) != 0 {
		return false
	}
	if len(delta.RuntimeGuards) != 0 {
		return false
	}
	return true
}

func compileSnapshotSubtreeCompiledOp(delta SemanticDelta) (CompiledOp, error) {
	if delta.Kind != model.OperationSnapshotSubtree || len(delta.ReadPredicates) != 1 || len(delta.WriteEffects) != 0 {
		return CompiledOp{}, model.ErrInvalidRequest
	}
	digest := descriptorDigest(delta)
	durability := DurabilityNeedsPublishCheckpoint
	placement := PlacementPlan{MountKeyID: delta.Authority.MountKeyID, Buckets: delta.Authority.Buckets, SlowReason: delta.SlowReason}
	placement.SingleBucket = len(placement.Buckets) == 1
	if delta.Eligibility == EligibilityVisibleCommit && !delta.DurabilityBarrier && len(delta.WriteEffects) > 0 {
		var mount model.MountKeyID
		var fsmetaKeys bool
		var opaqueKeys bool
		buckets := make([]layout.AffinityBucket, 0, len(delta.WriteEffects))
		for _, effect := range delta.WriteEffects {
			switch effect.Kind {
			case EffectPut:
				if len(effect.Key) == 0 || effect.Value == nil {
					placement.RequiresMaterialize = true
					goto placementDone
				}
			case EffectDelete:
				if len(effect.Key) == 0 {
					placement.RequiresMaterialize = true
					goto placementDone
				}
			case EffectDerivedPut, EffectDerivedDelete:
				placement.RequiresMaterialize = true
				goto placementDone
			default:
				placement.SlowReason = SlowReasonDynamicWriteSet
				goto placementDone
			}
			parts, ok := layout.InspectKey(effect.Key)
			if !ok {
				if fsmetaKeys {
					placement.SlowReason = SlowReasonDynamicWriteSet
					goto placementDone
				}
				opaqueKeys = true
				continue
			}
			if opaqueKeys {
				placement.SlowReason = SlowReasonDynamicWriteSet
				goto placementDone
			}
			if !fsmetaKeys {
				mount = parts.MountKeyID
				fsmetaKeys = true
			} else if mount != parts.MountKeyID {
				placement.SlowReason = SlowReasonCrossBucket
				goto placementDone
			}
			buckets = append(buckets, parts.Bucket)
		}
		if fsmetaKeys {
			placement.MountKeyID = mount
			placement.Buckets = uniqueBuckets(buckets)
			placement.SingleBucket = len(placement.Buckets) == 1
			placement.CanSegment = true
			placement.Install = SegmentInstallCatalog
			placement.MergeKey = SegmentMergeKey{MountKeyID: mount, Install: placement.Install, Durability: durability, FormatVersion: segmentFormatVersion}
		} else if opaqueKeys {
			placement.CanSegment = true
			placement.Install = SegmentInstallSingleBucket
			placement.MergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, Install: placement.Install, Durability: durability, FormatVersion: segmentFormatVersion}
		}
	}
placementDone:
	footprint := KeyFootprint{Reads: make([]KeyRef, 0, len(delta.ReadPredicates)), Writes: make([]KeyRef, 0, len(delta.WriteEffects)), ConflictKeys: make([]KeyRef, 0, len(delta.ReadPredicates)+len(delta.WriteEffects))}
	for _, predicate := range delta.ReadPredicates {
		mode := KeyAccessRead
		if predicate.Kind == PredicatePrefixScan {
			mode = KeyAccessReadPrefix
			footprint.HasPrefixRead = true
		}
		ref := keyRef(mode, predicate.Key)
		footprint.Reads = append(footprint.Reads, ref)
		footprint.ConflictKeys = append(footprint.ConflictKeys, ref)
		footprint.EstimatedBytes += uint64(len(predicate.Key) + len(predicate.ExpectedValue))
		if ref.Opaque {
			footprint.HasOpaqueKeys = true
		}
	}
	for _, effect := range delta.WriteEffects {
		ref := keyRef(KeyAccessWrite, effect.Key)
		footprint.Writes = append(footprint.Writes, ref)
		footprint.ConflictKeys = append(footprint.ConflictKeys, ref)
		footprint.EstimatedBytes += uint64(len(effect.Key) + len(effect.Value))
		if ref.Opaque {
			footprint.HasOpaqueKeys = true
		}
	}
	predicates := make([]PredicateObligation, 0, len(delta.ReadPredicates))
	for _, predicate := range delta.ReadPredicates {
		obligation := PredicateObligation{Kind: predicate.Kind, Key: predicate.Key, HasExpectedValue: predicate.HasExpectedValue}
		if predicate.HasExpectedValue {
			obligation.ExpectHash = sha256.Sum256(predicate.ExpectedValue)
		}
		switch predicate.Kind {
		case PredicateExists:
			obligation.NeedValue = true
		case PredicateNotExists:
			obligation.NeedAbsent = true
		case PredicateObservedValue:
			obligation.NeedValue = true
		}
		predicates = append(predicates, obligation)
	}
	guards := make([]GuardObligation, 0, len(delta.RuntimeGuards))
	for _, guard := range delta.RuntimeGuards {
		guards = append(guards, GuardObligation{Guard: guard, Digest: GuardObligationDigest(guard)})
	}
	effects := make([]EffectPlan, 0, len(delta.WriteEffects))
	for i, effect := range delta.WriteEffects {
		plan := EffectPlan{ID: MutationID(i), Kind: effect.Kind, Key: effect.Key, Value: effect.Value, Concrete: effect.Kind == EffectPut || effect.Kind == EffectDelete}
		if len(effect.Value) > 0 {
			plan.ValueHash = sha256.Sum256(effect.Value)
		}
		if parts, ok := layout.InspectKey(effect.Key); ok {
			plan.MountKeyID = parts.MountKeyID
			plan.Bucket = parts.Bucket
			plan.RecordKind = parts.Kind
		} else if len(effect.Key) > 0 {
			plan.Opaque = true
		}
		switch effect.Kind {
		case EffectDerivedPut, EffectDerivedDelete:
			plan.Derivation = DerivationRuntimeValue
		}
		effects = append(effects, plan)
	}
	atomicity := AtomicityGroup{Members: make([]MutationID, 0, len(delta.WriteEffects)), Recovery: RecoveryReplayAllOrNothing, Digest: digest}
	for i := range delta.WriteEffects {
		atomicity.Members = append(atomicity.Members, MutationID(i))
	}
	atomicity.Splittable = len(atomicity.Members) <= 1
	segment := SegmentPlan{MergeKey: placement.MergeKey, Install: placement.Install, CanAppend: placement.CanSegment, RequiresMaterialize: placement.RequiresMaterialize, EstimatedPayloadBytes: footprint.EstimatedBytes, OperationCount: 1, MutationCount: uint32(len(effects))}
	switch {
	case placement.Install == SegmentInstallSingleBucket:
		segment.CanMaterialize = placement.CanSegment
		segment.MaterializeInstall = SegmentInstallSingleBucket
		segment.MaterializeMergeKey = placement.MergeKey
	case placement.Install == SegmentInstallCatalog && placement.SingleBucket && len(placement.Buckets) == 1:
		segment.CanMaterialize = placement.CanSegment
		segment.MaterializeInstall = SegmentInstallSingleBucket
		segment.MaterializeMergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, HasPrimaryBucket: true, PrimaryBucket: placement.Buckets[0], Install: SegmentInstallSingleBucket, Durability: placement.MergeKey.Durability, FormatVersion: placement.MergeKey.FormatVersion}
	case placement.Install == SegmentInstallCatalog && placement.CanSegment:
		// Multi-bucket catalog op: materialize is still safe because the
		// installer writes each entry as a direct MVCC mutation regardless
		// of bucket. MergeKey carries no PrimaryBucket so all multi-bucket
		// materialize ops batch together in one install. Local fsmeta runtimes
		// consume this path when their installer materializes segments;
		// distributed runtimes keep catalog install and never enter materialize
		// in SegmentPlanForInstall.
		segment.CanMaterialize = placement.CanSegment
		segment.MaterializeInstall = SegmentInstallSingleBucket
		segment.MaterializeMergeKey = SegmentMergeKey{MountKeyID: placement.MountKeyID, Install: SegmentInstallSingleBucket, Durability: placement.MergeKey.Durability, FormatVersion: placement.MergeKey.FormatVersion}
	}
	completion := CompletionPlan{}
	if delta.Eligibility == EligibilityVisibleCommit && len(effects) != 0 {
		kind := CompletionVisible
		if durability != DurabilityVisibleOnly {
			kind = CompletionDurable
		}
		completion = CompletionPlan{RetainCompletion: true, Kind: kind, MutationCount: uint32(len(effects)), DescriptorDigest: digest}
	}
	watch := []WatchProjection(nil)
	if len(delta.WriteEffects) > 0 {
		emitAt := WatchEmitVisible
		if delta.WatchAtSeal || delta.DurabilityBarrier {
			emitAt = WatchEmitSeal
		}
		watch = make([]WatchProjection, 0, len(delta.WriteEffects))
		for _, effect := range delta.WriteEffects {
			if len(effect.Key) == 0 {
				continue
			}
			parts, ok := layout.InspectKey(effect.Key)
			if !ok || parts.Kind != layout.KeyKindDentry {
				continue
			}
			projection := WatchProjection{EventKind: watchEventKind(delta, effect), Key: effect.Key, Parent: parts.Parent, Name: dentryName(effect.Key), EmitAt: emitAt}
			if len(effect.Value) > 0 {
				if dentry, err := layout.DecodeDentryValue(effect.Value); err == nil {
					projection.Inode = dentry.Inode
				}
			}
			watch = append(watch, projection)
		}
	}
	return CompiledOp{
		Delta:            delta,
		DescriptorDigest: digest,
		IntentDigest:     digest,
		ReplayDigest:     digest,
		Authority:        AuthorityPlan{Scope: delta.Authority, Required: delta.Eligibility == EligibilityVisibleCommit, Fence: fenceMode(delta)},
		Placement:        placement,
		Footprint:        footprint,
		Predicates:       predicates,
		Guards:           guards,
		Effects:          effects,
		Atomicity:        atomicity,
		Durability:       durability,
		Watch:            watch,
		Completion:       completion,
		Segment:          segment,
	}, nil
}
