# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from langgraph.checkpoint.nokv._proto import fsmeta_pb2 as fsmeta__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fsmeta_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FSMetadataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/Create',
                request_serializer=fsmeta__pb2.CreateRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.UpdateInode = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/UpdateInode',
                request_serializer=fsmeta__pb2.UpdateInodeRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.UpdateInodeResponse.FromString,
                _registered_method=True)
        self.Lookup = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/Lookup',
                request_serializer=fsmeta__pb2.LookupRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.LookupPlus = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/LookupPlus',
                request_serializer=fsmeta__pb2.LookupRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.LookupPlusResponse.FromString,
                _registered_method=True)
        self.BatchLookupPlus = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/BatchLookupPlus',
                request_serializer=fsmeta__pb2.BatchLookupPlusRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.BatchLookupPlusResponse.FromString,
                _registered_method=True)
        self.ReadDir = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/ReadDir',
                request_serializer=fsmeta__pb2.ReadDirRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.ReadDirResponse.FromString,
                _registered_method=True)
        self.ReadDirPlus = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/ReadDirPlus',
                request_serializer=fsmeta__pb2.ReadDirRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.ReadDirPlusResponse.FromString,
                _registered_method=True)
        self.WatchSubtree = channel.stream_stream(
                '/nokv.fsmeta.v1.FSMetadata/WatchSubtree',
                request_serializer=fsmeta__pb2.WatchAckOrSubscribe.SerializeToString,
                response_deserializer=fsmeta__pb2.WatchSubtreeResponse.FromString,
                _registered_method=True)
        self.GetReadVersion = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/GetReadVersion',
                request_serializer=fsmeta__pb2.GetReadVersionRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.GetReadVersionResponse.FromString,
                _registered_method=True)
        self.SnapshotSubtree = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/SnapshotSubtree',
                request_serializer=fsmeta__pb2.SnapshotSubtreeRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.SnapshotSubtreeResponse.FromString,
                _registered_method=True)
        self.RetireSnapshotSubtree = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/RetireSnapshotSubtree',
                request_serializer=fsmeta__pb2.RetireSnapshotSubtreeRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.RetireSnapshotSubtreeResponse.FromString,
                _registered_method=True)
        self.GetQuotaUsage = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/GetQuotaUsage',
                request_serializer=fsmeta__pb2.QuotaUsageRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.QuotaUsageResponse.FromString,
                _registered_method=True)
        self.Rename = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/Rename',
                request_serializer=fsmeta__pb2.RenameRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.RenameResponse.FromString,
                _registered_method=True)
        self.RenameSubtree = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/RenameSubtree',
                request_serializer=fsmeta__pb2.RenameSubtreeRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.RenameSubtreeResponse.FromString,
                _registered_method=True)
        self.Link = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/Link',
                request_serializer=fsmeta__pb2.LinkRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.LinkResponse.FromString,
                _registered_method=True)
        self.Unlink = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/Unlink',
                request_serializer=fsmeta__pb2.UnlinkRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.UnlinkResponse.FromString,
                _registered_method=True)
        self.OpenWriteSession = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/OpenWriteSession',
                request_serializer=fsmeta__pb2.OpenWriteSessionRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.OpenWriteSessionResponse.FromString,
                _registered_method=True)
        self.HeartbeatWriteSession = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/HeartbeatWriteSession',
                request_serializer=fsmeta__pb2.HeartbeatWriteSessionRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.HeartbeatWriteSessionResponse.FromString,
                _registered_method=True)
        self.CloseWriteSession = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/CloseWriteSession',
                request_serializer=fsmeta__pb2.CloseWriteSessionRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.CloseWriteSessionResponse.FromString,
                _registered_method=True)
        self.ExpireWriteSessions = channel.unary_unary(
                '/nokv.fsmeta.v1.FSMetadata/ExpireWriteSessions',
                request_serializer=fsmeta__pb2.ExpireWriteSessionsRequest.SerializeToString,
                response_deserializer=fsmeta__pb2.ExpireWriteSessionsResponse.FromString,
                _registered_method=True)


class FSMetadataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupPlus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchLookupPlus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDirPlus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSubtree(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotSubtree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetireSnapshotSubtree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuotaUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameSubtree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Link(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenWriteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatWriteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseWriteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpireWriteSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FSMetadataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=fsmeta__pb2.CreateRequest.FromString,
                    response_serializer=fsmeta__pb2.CreateResponse.SerializeToString,
            ),
            'UpdateInode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInode,
                    request_deserializer=fsmeta__pb2.UpdateInodeRequest.FromString,
                    response_serializer=fsmeta__pb2.UpdateInodeResponse.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=fsmeta__pb2.LookupRequest.FromString,
                    response_serializer=fsmeta__pb2.LookupResponse.SerializeToString,
            ),
            'LookupPlus': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupPlus,
                    request_deserializer=fsmeta__pb2.LookupRequest.FromString,
                    response_serializer=fsmeta__pb2.LookupPlusResponse.SerializeToString,
            ),
            'BatchLookupPlus': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchLookupPlus,
                    request_deserializer=fsmeta__pb2.BatchLookupPlusRequest.FromString,
                    response_serializer=fsmeta__pb2.BatchLookupPlusResponse.SerializeToString,
            ),
            'ReadDir': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDir,
                    request_deserializer=fsmeta__pb2.ReadDirRequest.FromString,
                    response_serializer=fsmeta__pb2.ReadDirResponse.SerializeToString,
            ),
            'ReadDirPlus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDirPlus,
                    request_deserializer=fsmeta__pb2.ReadDirRequest.FromString,
                    response_serializer=fsmeta__pb2.ReadDirPlusResponse.SerializeToString,
            ),
            'WatchSubtree': grpc.stream_stream_rpc_method_handler(
                    servicer.WatchSubtree,
                    request_deserializer=fsmeta__pb2.WatchAckOrSubscribe.FromString,
                    response_serializer=fsmeta__pb2.WatchSubtreeResponse.SerializeToString,
            ),
            'GetReadVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadVersion,
                    request_deserializer=fsmeta__pb2.GetReadVersionRequest.FromString,
                    response_serializer=fsmeta__pb2.GetReadVersionResponse.SerializeToString,
            ),
            'SnapshotSubtree': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotSubtree,
                    request_deserializer=fsmeta__pb2.SnapshotSubtreeRequest.FromString,
                    response_serializer=fsmeta__pb2.SnapshotSubtreeResponse.SerializeToString,
            ),
            'RetireSnapshotSubtree': grpc.unary_unary_rpc_method_handler(
                    servicer.RetireSnapshotSubtree,
                    request_deserializer=fsmeta__pb2.RetireSnapshotSubtreeRequest.FromString,
                    response_serializer=fsmeta__pb2.RetireSnapshotSubtreeResponse.SerializeToString,
            ),
            'GetQuotaUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuotaUsage,
                    request_deserializer=fsmeta__pb2.QuotaUsageRequest.FromString,
                    response_serializer=fsmeta__pb2.QuotaUsageResponse.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=fsmeta__pb2.RenameRequest.FromString,
                    response_serializer=fsmeta__pb2.RenameResponse.SerializeToString,
            ),
            'RenameSubtree': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameSubtree,
                    request_deserializer=fsmeta__pb2.RenameSubtreeRequest.FromString,
                    response_serializer=fsmeta__pb2.RenameSubtreeResponse.SerializeToString,
            ),
            'Link': grpc.unary_unary_rpc_method_handler(
                    servicer.Link,
                    request_deserializer=fsmeta__pb2.LinkRequest.FromString,
                    response_serializer=fsmeta__pb2.LinkResponse.SerializeToString,
            ),
            'Unlink': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlink,
                    request_deserializer=fsmeta__pb2.UnlinkRequest.FromString,
                    response_serializer=fsmeta__pb2.UnlinkResponse.SerializeToString,
            ),
            'OpenWriteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenWriteSession,
                    request_deserializer=fsmeta__pb2.OpenWriteSessionRequest.FromString,
                    response_serializer=fsmeta__pb2.OpenWriteSessionResponse.SerializeToString,
            ),
            'HeartbeatWriteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatWriteSession,
                    request_deserializer=fsmeta__pb2.HeartbeatWriteSessionRequest.FromString,
                    response_serializer=fsmeta__pb2.HeartbeatWriteSessionResponse.SerializeToString,
            ),
            'CloseWriteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseWriteSession,
                    request_deserializer=fsmeta__pb2.CloseWriteSessionRequest.FromString,
                    response_serializer=fsmeta__pb2.CloseWriteSessionResponse.SerializeToString,
            ),
            'ExpireWriteSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpireWriteSessions,
                    request_deserializer=fsmeta__pb2.ExpireWriteSessionsRequest.FromString,
                    response_serializer=fsmeta__pb2.ExpireWriteSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nokv.fsmeta.v1.FSMetadata', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nokv.fsmeta.v1.FSMetadata', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FSMetadata(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/Create',
            fsmeta__pb2.CreateRequest.SerializeToString,
            fsmeta__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/UpdateInode',
            fsmeta__pb2.UpdateInodeRequest.SerializeToString,
            fsmeta__pb2.UpdateInodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/Lookup',
            fsmeta__pb2.LookupRequest.SerializeToString,
            fsmeta__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupPlus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/LookupPlus',
            fsmeta__pb2.LookupRequest.SerializeToString,
            fsmeta__pb2.LookupPlusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchLookupPlus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/BatchLookupPlus',
            fsmeta__pb2.BatchLookupPlusRequest.SerializeToString,
            fsmeta__pb2.BatchLookupPlusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/ReadDir',
            fsmeta__pb2.ReadDirRequest.SerializeToString,
            fsmeta__pb2.ReadDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDirPlus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/ReadDirPlus',
            fsmeta__pb2.ReadDirRequest.SerializeToString,
            fsmeta__pb2.ReadDirPlusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSubtree(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nokv.fsmeta.v1.FSMetadata/WatchSubtree',
            fsmeta__pb2.WatchAckOrSubscribe.SerializeToString,
            fsmeta__pb2.WatchSubtreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReadVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/GetReadVersion',
            fsmeta__pb2.GetReadVersionRequest.SerializeToString,
            fsmeta__pb2.GetReadVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotSubtree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/SnapshotSubtree',
            fsmeta__pb2.SnapshotSubtreeRequest.SerializeToString,
            fsmeta__pb2.SnapshotSubtreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetireSnapshotSubtree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/RetireSnapshotSubtree',
            fsmeta__pb2.RetireSnapshotSubtreeRequest.SerializeToString,
            fsmeta__pb2.RetireSnapshotSubtreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuotaUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/GetQuotaUsage',
            fsmeta__pb2.QuotaUsageRequest.SerializeToString,
            fsmeta__pb2.QuotaUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/Rename',
            fsmeta__pb2.RenameRequest.SerializeToString,
            fsmeta__pb2.RenameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameSubtree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/RenameSubtree',
            fsmeta__pb2.RenameSubtreeRequest.SerializeToString,
            fsmeta__pb2.RenameSubtreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Link(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/Link',
            fsmeta__pb2.LinkRequest.SerializeToString,
            fsmeta__pb2.LinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unlink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/Unlink',
            fsmeta__pb2.UnlinkRequest.SerializeToString,
            fsmeta__pb2.UnlinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenWriteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/OpenWriteSession',
            fsmeta__pb2.OpenWriteSessionRequest.SerializeToString,
            fsmeta__pb2.OpenWriteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatWriteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/HeartbeatWriteSession',
            fsmeta__pb2.HeartbeatWriteSessionRequest.SerializeToString,
            fsmeta__pb2.HeartbeatWriteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseWriteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/CloseWriteSession',
            fsmeta__pb2.CloseWriteSessionRequest.SerializeToString,
            fsmeta__pb2.CloseWriteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpireWriteSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nokv.fsmeta.v1.FSMetadata/ExpireWriteSessions',
            fsmeta__pb2.ExpireWriteSessionsRequest.SerializeToString,
            fsmeta__pb2.ExpireWriteSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
