// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: adminpb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftAdmin_AddPeer_FullMethodName                    = "/pb.RaftAdmin/AddPeer"
	RaftAdmin_RemovePeer_FullMethodName                 = "/pb.RaftAdmin/RemovePeer"
	RaftAdmin_TransferLeader_FullMethodName             = "/pb.RaftAdmin/TransferLeader"
	RaftAdmin_ExportRegionSnapshot_FullMethodName       = "/pb.RaftAdmin/ExportRegionSnapshot"
	RaftAdmin_ExportRegionSnapshotStream_FullMethodName = "/pb.RaftAdmin/ExportRegionSnapshotStream"
	RaftAdmin_ImportRegionSnapshot_FullMethodName       = "/pb.RaftAdmin/ImportRegionSnapshot"
	RaftAdmin_ImportRegionSnapshotStream_FullMethodName = "/pb.RaftAdmin/ImportRegionSnapshotStream"
	RaftAdmin_RegionRuntimeStatus_FullMethodName        = "/pb.RaftAdmin/RegionRuntimeStatus"
)

// RaftAdminClient is the client API for RaftAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftAdminClient interface {
	AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error)
	RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error)
	TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error)
	ExportRegionSnapshot(ctx context.Context, in *ExportRegionSnapshotRequest, opts ...grpc.CallOption) (*ExportRegionSnapshotResponse, error)
	ExportRegionSnapshotStream(ctx context.Context, in *ExportRegionSnapshotStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportRegionSnapshotStreamResponse], error)
	ImportRegionSnapshot(ctx context.Context, in *ImportRegionSnapshotRequest, opts ...grpc.CallOption) (*ImportRegionSnapshotResponse, error)
	ImportRegionSnapshotStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportRegionSnapshotStreamRequest, ImportRegionSnapshotResponse], error)
	RegionRuntimeStatus(ctx context.Context, in *RegionRuntimeStatusRequest, opts ...grpc.CallOption) (*RegionRuntimeStatusResponse, error)
}

type raftAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftAdminClient(cc grpc.ClientConnInterface) RaftAdminClient {
	return &raftAdminClient{cc}
}

func (c *raftAdminClient) AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPeerResponse)
	err := c.cc.Invoke(ctx, RaftAdmin_AddPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftAdminClient) RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePeerResponse)
	err := c.cc.Invoke(ctx, RaftAdmin_RemovePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftAdminClient) TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferLeaderResponse)
	err := c.cc.Invoke(ctx, RaftAdmin_TransferLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftAdminClient) ExportRegionSnapshot(ctx context.Context, in *ExportRegionSnapshotRequest, opts ...grpc.CallOption) (*ExportRegionSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRegionSnapshotResponse)
	err := c.cc.Invoke(ctx, RaftAdmin_ExportRegionSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftAdminClient) ExportRegionSnapshotStream(ctx context.Context, in *ExportRegionSnapshotStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportRegionSnapshotStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftAdmin_ServiceDesc.Streams[0], RaftAdmin_ExportRegionSnapshotStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportRegionSnapshotStreamRequest, ExportRegionSnapshotStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftAdmin_ExportRegionSnapshotStreamClient = grpc.ServerStreamingClient[ExportRegionSnapshotStreamResponse]

func (c *raftAdminClient) ImportRegionSnapshot(ctx context.Context, in *ImportRegionSnapshotRequest, opts ...grpc.CallOption) (*ImportRegionSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportRegionSnapshotResponse)
	err := c.cc.Invoke(ctx, RaftAdmin_ImportRegionSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftAdminClient) ImportRegionSnapshotStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportRegionSnapshotStreamRequest, ImportRegionSnapshotResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftAdmin_ServiceDesc.Streams[1], RaftAdmin_ImportRegionSnapshotStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportRegionSnapshotStreamRequest, ImportRegionSnapshotResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftAdmin_ImportRegionSnapshotStreamClient = grpc.ClientStreamingClient[ImportRegionSnapshotStreamRequest, ImportRegionSnapshotResponse]

func (c *raftAdminClient) RegionRuntimeStatus(ctx context.Context, in *RegionRuntimeStatusRequest, opts ...grpc.CallOption) (*RegionRuntimeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionRuntimeStatusResponse)
	err := c.cc.Invoke(ctx, RaftAdmin_RegionRuntimeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftAdminServer is the server API for RaftAdmin service.
// All implementations should embed UnimplementedRaftAdminServer
// for forward compatibility.
type RaftAdminServer interface {
	AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error)
	RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error)
	TransferLeader(context.Context, *TransferLeaderRequest) (*TransferLeaderResponse, error)
	ExportRegionSnapshot(context.Context, *ExportRegionSnapshotRequest) (*ExportRegionSnapshotResponse, error)
	ExportRegionSnapshotStream(*ExportRegionSnapshotStreamRequest, grpc.ServerStreamingServer[ExportRegionSnapshotStreamResponse]) error
	ImportRegionSnapshot(context.Context, *ImportRegionSnapshotRequest) (*ImportRegionSnapshotResponse, error)
	ImportRegionSnapshotStream(grpc.ClientStreamingServer[ImportRegionSnapshotStreamRequest, ImportRegionSnapshotResponse]) error
	RegionRuntimeStatus(context.Context, *RegionRuntimeStatusRequest) (*RegionRuntimeStatusResponse, error)
}

// UnimplementedRaftAdminServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftAdminServer struct{}

func (UnimplementedRaftAdminServer) AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPeer not implemented")
}
func (UnimplementedRaftAdminServer) RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePeer not implemented")
}
func (UnimplementedRaftAdminServer) TransferLeader(context.Context, *TransferLeaderRequest) (*TransferLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferLeader not implemented")
}
func (UnimplementedRaftAdminServer) ExportRegionSnapshot(context.Context, *ExportRegionSnapshotRequest) (*ExportRegionSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportRegionSnapshot not implemented")
}
func (UnimplementedRaftAdminServer) ExportRegionSnapshotStream(*ExportRegionSnapshotStreamRequest, grpc.ServerStreamingServer[ExportRegionSnapshotStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ExportRegionSnapshotStream not implemented")
}
func (UnimplementedRaftAdminServer) ImportRegionSnapshot(context.Context, *ImportRegionSnapshotRequest) (*ImportRegionSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportRegionSnapshot not implemented")
}
func (UnimplementedRaftAdminServer) ImportRegionSnapshotStream(grpc.ClientStreamingServer[ImportRegionSnapshotStreamRequest, ImportRegionSnapshotResponse]) error {
	return status.Error(codes.Unimplemented, "method ImportRegionSnapshotStream not implemented")
}
func (UnimplementedRaftAdminServer) RegionRuntimeStatus(context.Context, *RegionRuntimeStatusRequest) (*RegionRuntimeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegionRuntimeStatus not implemented")
}
func (UnimplementedRaftAdminServer) testEmbeddedByValue() {}

// UnsafeRaftAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftAdminServer will
// result in compilation errors.
type UnsafeRaftAdminServer interface {
	mustEmbedUnimplementedRaftAdminServer()
}

func RegisterRaftAdminServer(s grpc.ServiceRegistrar, srv RaftAdminServer) {
	// If the following call panics, it indicates UnimplementedRaftAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftAdmin_ServiceDesc, srv)
}

func _RaftAdmin_AddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftAdminServer).AddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftAdmin_AddPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftAdminServer).AddPeer(ctx, req.(*AddPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftAdmin_RemovePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftAdminServer).RemovePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftAdmin_RemovePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftAdminServer).RemovePeer(ctx, req.(*RemovePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftAdmin_TransferLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftAdminServer).TransferLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftAdmin_TransferLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftAdminServer).TransferLeader(ctx, req.(*TransferLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftAdmin_ExportRegionSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRegionSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftAdminServer).ExportRegionSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftAdmin_ExportRegionSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftAdminServer).ExportRegionSnapshot(ctx, req.(*ExportRegionSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftAdmin_ExportRegionSnapshotStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRegionSnapshotStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaftAdminServer).ExportRegionSnapshotStream(m, &grpc.GenericServerStream[ExportRegionSnapshotStreamRequest, ExportRegionSnapshotStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftAdmin_ExportRegionSnapshotStreamServer = grpc.ServerStreamingServer[ExportRegionSnapshotStreamResponse]

func _RaftAdmin_ImportRegionSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRegionSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftAdminServer).ImportRegionSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftAdmin_ImportRegionSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftAdminServer).ImportRegionSnapshot(ctx, req.(*ImportRegionSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftAdmin_ImportRegionSnapshotStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftAdminServer).ImportRegionSnapshotStream(&grpc.GenericServerStream[ImportRegionSnapshotStreamRequest, ImportRegionSnapshotResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftAdmin_ImportRegionSnapshotStreamServer = grpc.ClientStreamingServer[ImportRegionSnapshotStreamRequest, ImportRegionSnapshotResponse]

func _RaftAdmin_RegionRuntimeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionRuntimeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftAdminServer).RegionRuntimeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftAdmin_RegionRuntimeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftAdminServer).RegionRuntimeStatus(ctx, req.(*RegionRuntimeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftAdmin_ServiceDesc is the grpc.ServiceDesc for RaftAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RaftAdmin",
	HandlerType: (*RaftAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPeer",
			Handler:    _RaftAdmin_AddPeer_Handler,
		},
		{
			MethodName: "RemovePeer",
			Handler:    _RaftAdmin_RemovePeer_Handler,
		},
		{
			MethodName: "TransferLeader",
			Handler:    _RaftAdmin_TransferLeader_Handler,
		},
		{
			MethodName: "ExportRegionSnapshot",
			Handler:    _RaftAdmin_ExportRegionSnapshot_Handler,
		},
		{
			MethodName: "ImportRegionSnapshot",
			Handler:    _RaftAdmin_ImportRegionSnapshot_Handler,
		},
		{
			MethodName: "RegionRuntimeStatus",
			Handler:    _RaftAdmin_RegionRuntimeStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportRegionSnapshotStream",
			Handler:       _RaftAdmin_ExportRegionSnapshotStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImportRegionSnapshotStream",
			Handler:       _RaftAdmin_ImportRegionSnapshotStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "adminpb.proto",
}
