// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: adminpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegionSnapshotFormat int32

const (
	RegionSnapshotFormat_REGION_SNAPSHOT_FORMAT_LOGICAL RegionSnapshotFormat = 0
	RegionSnapshotFormat_REGION_SNAPSHOT_FORMAT_SST     RegionSnapshotFormat = 1
)

// Enum value maps for RegionSnapshotFormat.
var (
	RegionSnapshotFormat_name = map[int32]string{
		0: "REGION_SNAPSHOT_FORMAT_LOGICAL",
		1: "REGION_SNAPSHOT_FORMAT_SST",
	}
	RegionSnapshotFormat_value = map[string]int32{
		"REGION_SNAPSHOT_FORMAT_LOGICAL": 0,
		"REGION_SNAPSHOT_FORMAT_SST":     1,
	}
)

func (x RegionSnapshotFormat) Enum() *RegionSnapshotFormat {
	p := new(RegionSnapshotFormat)
	*p = x
	return p
}

func (x RegionSnapshotFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionSnapshotFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_adminpb_proto_enumTypes[0].Descriptor()
}

func (RegionSnapshotFormat) Type() protoreflect.EnumType {
	return &file_adminpb_proto_enumTypes[0]
}

func (x RegionSnapshotFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegionSnapshotFormat.Descriptor instead.
func (RegionSnapshotFormat) EnumDescriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{0}
}

type AddPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	PeerId        uint64                 `protobuf:"varint,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerRequest) Reset() {
	*x = AddPeerRequest{}
	mi := &file_adminpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerRequest) ProtoMessage() {}

func (x *AddPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerRequest.ProtoReflect.Descriptor instead.
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{0}
}

func (x *AddPeerRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *AddPeerRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *AddPeerRequest) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type AddPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *RegionMeta            `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerResponse) Reset() {
	*x = AddPeerResponse{}
	mi := &file_adminpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerResponse) ProtoMessage() {}

func (x *AddPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerResponse.ProtoReflect.Descriptor instead.
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{1}
}

func (x *AddPeerResponse) GetRegion() *RegionMeta {
	if x != nil {
		return x.Region
	}
	return nil
}

type RemovePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	PeerId        uint64                 `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_adminpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{2}
}

func (x *RemovePeerRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RemovePeerRequest) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type RemovePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *RegionMeta            `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_adminpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{3}
}

func (x *RemovePeerResponse) GetRegion() *RegionMeta {
	if x != nil {
		return x.Region
	}
	return nil
}

type TransferLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	PeerId        uint64                 `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeaderRequest) Reset() {
	*x = TransferLeaderRequest{}
	mi := &file_adminpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeaderRequest) ProtoMessage() {}

func (x *TransferLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeaderRequest.ProtoReflect.Descriptor instead.
func (*TransferLeaderRequest) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{4}
}

func (x *TransferLeaderRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *TransferLeaderRequest) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type TransferLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *RegionMeta            `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeaderResponse) Reset() {
	*x = TransferLeaderResponse{}
	mi := &file_adminpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeaderResponse) ProtoMessage() {}

func (x *TransferLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeaderResponse.ProtoReflect.Descriptor instead.
func (*TransferLeaderResponse) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{5}
}

func (x *TransferLeaderResponse) GetRegion() *RegionMeta {
	if x != nil {
		return x.Region
	}
	return nil
}

type ExportRegionSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Format        RegionSnapshotFormat   `protobuf:"varint,2,opt,name=format,proto3,enum=pb.RegionSnapshotFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRegionSnapshotRequest) Reset() {
	*x = ExportRegionSnapshotRequest{}
	mi := &file_adminpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRegionSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRegionSnapshotRequest) ProtoMessage() {}

func (x *ExportRegionSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRegionSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ExportRegionSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{6}
}

func (x *ExportRegionSnapshotRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *ExportRegionSnapshotRequest) GetFormat() RegionSnapshotFormat {
	if x != nil {
		return x.Format
	}
	return RegionSnapshotFormat_REGION_SNAPSHOT_FORMAT_LOGICAL
}

type ExportRegionSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      []byte                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Region        *RegionMeta            `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Format        RegionSnapshotFormat   `protobuf:"varint,3,opt,name=format,proto3,enum=pb.RegionSnapshotFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRegionSnapshotResponse) Reset() {
	*x = ExportRegionSnapshotResponse{}
	mi := &file_adminpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRegionSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRegionSnapshotResponse) ProtoMessage() {}

func (x *ExportRegionSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRegionSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ExportRegionSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{7}
}

func (x *ExportRegionSnapshotResponse) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ExportRegionSnapshotResponse) GetRegion() *RegionMeta {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *ExportRegionSnapshotResponse) GetFormat() RegionSnapshotFormat {
	if x != nil {
		return x.Format
	}
	return RegionSnapshotFormat_REGION_SNAPSHOT_FORMAT_LOGICAL
}

type InstallRegionSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      []byte                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Format        RegionSnapshotFormat   `protobuf:"varint,2,opt,name=format,proto3,enum=pb.RegionSnapshotFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRegionSnapshotRequest) Reset() {
	*x = InstallRegionSnapshotRequest{}
	mi := &file_adminpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRegionSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRegionSnapshotRequest) ProtoMessage() {}

func (x *InstallRegionSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRegionSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallRegionSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{8}
}

func (x *InstallRegionSnapshotRequest) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *InstallRegionSnapshotRequest) GetFormat() RegionSnapshotFormat {
	if x != nil {
		return x.Format
	}
	return RegionSnapshotFormat_REGION_SNAPSHOT_FORMAT_LOGICAL
}

type InstallRegionSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *RegionMeta            `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRegionSnapshotResponse) Reset() {
	*x = InstallRegionSnapshotResponse{}
	mi := &file_adminpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRegionSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRegionSnapshotResponse) ProtoMessage() {}

func (x *InstallRegionSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRegionSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallRegionSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{9}
}

func (x *InstallRegionSnapshotResponse) GetRegion() *RegionMeta {
	if x != nil {
		return x.Region
	}
	return nil
}

type RegionRuntimeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionRuntimeStatusRequest) Reset() {
	*x = RegionRuntimeStatusRequest{}
	mi := &file_adminpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionRuntimeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRuntimeStatusRequest) ProtoMessage() {}

func (x *RegionRuntimeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRuntimeStatusRequest.ProtoReflect.Descriptor instead.
func (*RegionRuntimeStatusRequest) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{10}
}

func (x *RegionRuntimeStatusRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type RegionRuntimeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Known         bool                   `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"`
	Hosted        bool                   `protobuf:"varint,2,opt,name=hosted,proto3" json:"hosted,omitempty"`
	LocalPeerId   uint64                 `protobuf:"varint,3,opt,name=local_peer_id,json=localPeerId,proto3" json:"local_peer_id,omitempty"`
	LeaderPeerId  uint64                 `protobuf:"varint,4,opt,name=leader_peer_id,json=leaderPeerId,proto3" json:"leader_peer_id,omitempty"`
	Leader        bool                   `protobuf:"varint,5,opt,name=leader,proto3" json:"leader,omitempty"`
	Region        *RegionMeta            `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	AppliedIndex  uint64                 `protobuf:"varint,7,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	AppliedTerm   uint64                 `protobuf:"varint,8,opt,name=applied_term,json=appliedTerm,proto3" json:"applied_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionRuntimeStatusResponse) Reset() {
	*x = RegionRuntimeStatusResponse{}
	mi := &file_adminpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionRuntimeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRuntimeStatusResponse) ProtoMessage() {}

func (x *RegionRuntimeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRuntimeStatusResponse.ProtoReflect.Descriptor instead.
func (*RegionRuntimeStatusResponse) Descriptor() ([]byte, []int) {
	return file_adminpb_proto_rawDescGZIP(), []int{11}
}

func (x *RegionRuntimeStatusResponse) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *RegionRuntimeStatusResponse) GetHosted() bool {
	if x != nil {
		return x.Hosted
	}
	return false
}

func (x *RegionRuntimeStatusResponse) GetLocalPeerId() uint64 {
	if x != nil {
		return x.LocalPeerId
	}
	return 0
}

func (x *RegionRuntimeStatusResponse) GetLeaderPeerId() uint64 {
	if x != nil {
		return x.LeaderPeerId
	}
	return 0
}

func (x *RegionRuntimeStatusResponse) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *RegionRuntimeStatusResponse) GetRegion() *RegionMeta {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *RegionRuntimeStatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *RegionRuntimeStatusResponse) GetAppliedTerm() uint64 {
	if x != nil {
		return x.AppliedTerm
	}
	return 0
}

var File_adminpb_proto protoreflect.FileDescriptor

const file_adminpb_proto_rawDesc = "" +
	"\n" +
	"\radminpb.proto\x12\x02pb\x1a\fmetapb.proto\"a\n" +
	"\x0eAddPeerRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\x04R\x06peerId\"9\n" +
	"\x0fAddPeerResponse\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.pb.RegionMetaR\x06region\"I\n" +
	"\x11RemovePeerRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x04R\x06peerId\"<\n" +
	"\x12RemovePeerResponse\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.pb.RegionMetaR\x06region\"M\n" +
	"\x15TransferLeaderRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\x04R\x06peerId\"@\n" +
	"\x16TransferLeaderResponse\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.pb.RegionMetaR\x06region\"l\n" +
	"\x1bExportRegionSnapshotRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x120\n" +
	"\x06format\x18\x02 \x01(\x0e2\x18.pb.RegionSnapshotFormatR\x06format\"\x94\x01\n" +
	"\x1cExportRegionSnapshotResponse\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\fR\bsnapshot\x12&\n" +
	"\x06region\x18\x02 \x01(\v2\x0e.pb.RegionMetaR\x06region\x120\n" +
	"\x06format\x18\x03 \x01(\x0e2\x18.pb.RegionSnapshotFormatR\x06format\"l\n" +
	"\x1cInstallRegionSnapshotRequest\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\fR\bsnapshot\x120\n" +
	"\x06format\x18\x02 \x01(\x0e2\x18.pb.RegionSnapshotFormatR\x06format\"G\n" +
	"\x1dInstallRegionSnapshotResponse\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.pb.RegionMetaR\x06region\"9\n" +
	"\x1aRegionRuntimeStatusRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"\x9d\x02\n" +
	"\x1bRegionRuntimeStatusResponse\x12\x14\n" +
	"\x05known\x18\x01 \x01(\bR\x05known\x12\x16\n" +
	"\x06hosted\x18\x02 \x01(\bR\x06hosted\x12\"\n" +
	"\rlocal_peer_id\x18\x03 \x01(\x04R\vlocalPeerId\x12$\n" +
	"\x0eleader_peer_id\x18\x04 \x01(\x04R\fleaderPeerId\x12\x16\n" +
	"\x06leader\x18\x05 \x01(\bR\x06leader\x12&\n" +
	"\x06region\x18\x06 \x01(\v2\x0e.pb.RegionMetaR\x06region\x12#\n" +
	"\rapplied_index\x18\a \x01(\x04R\fappliedIndex\x12!\n" +
	"\fapplied_term\x18\b \x01(\x04R\vappliedTerm*Z\n" +
	"\x14RegionSnapshotFormat\x12\"\n" +
	"\x1eREGION_SNAPSHOT_FORMAT_LOGICAL\x10\x00\x12\x1e\n" +
	"\x1aREGION_SNAPSHOT_FORMAT_SST\x10\x012\xd6\x03\n" +
	"\tRaftAdmin\x122\n" +
	"\aAddPeer\x12\x12.pb.AddPeerRequest\x1a\x13.pb.AddPeerResponse\x12;\n" +
	"\n" +
	"RemovePeer\x12\x15.pb.RemovePeerRequest\x1a\x16.pb.RemovePeerResponse\x12G\n" +
	"\x0eTransferLeader\x12\x19.pb.TransferLeaderRequest\x1a\x1a.pb.TransferLeaderResponse\x12Y\n" +
	"\x14ExportRegionSnapshot\x12\x1f.pb.ExportRegionSnapshotRequest\x1a .pb.ExportRegionSnapshotResponse\x12\\\n" +
	"\x15InstallRegionSnapshot\x12 .pb.InstallRegionSnapshotRequest\x1a!.pb.InstallRegionSnapshotResponse\x12V\n" +
	"\x13RegionRuntimeStatus\x12\x1e.pb.RegionRuntimeStatusRequest\x1a\x1f.pb.RegionRuntimeStatusResponseB Z\x1egithub.com/feichai0017/NoKV/pbb\x06proto3"

var (
	file_adminpb_proto_rawDescOnce sync.Once
	file_adminpb_proto_rawDescData []byte
)

func file_adminpb_proto_rawDescGZIP() []byte {
	file_adminpb_proto_rawDescOnce.Do(func() {
		file_adminpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adminpb_proto_rawDesc), len(file_adminpb_proto_rawDesc)))
	})
	return file_adminpb_proto_rawDescData
}

var file_adminpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_adminpb_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_adminpb_proto_goTypes = []any{
	(RegionSnapshotFormat)(0),             // 0: pb.RegionSnapshotFormat
	(*AddPeerRequest)(nil),                // 1: pb.AddPeerRequest
	(*AddPeerResponse)(nil),               // 2: pb.AddPeerResponse
	(*RemovePeerRequest)(nil),             // 3: pb.RemovePeerRequest
	(*RemovePeerResponse)(nil),            // 4: pb.RemovePeerResponse
	(*TransferLeaderRequest)(nil),         // 5: pb.TransferLeaderRequest
	(*TransferLeaderResponse)(nil),        // 6: pb.TransferLeaderResponse
	(*ExportRegionSnapshotRequest)(nil),   // 7: pb.ExportRegionSnapshotRequest
	(*ExportRegionSnapshotResponse)(nil),  // 8: pb.ExportRegionSnapshotResponse
	(*InstallRegionSnapshotRequest)(nil),  // 9: pb.InstallRegionSnapshotRequest
	(*InstallRegionSnapshotResponse)(nil), // 10: pb.InstallRegionSnapshotResponse
	(*RegionRuntimeStatusRequest)(nil),    // 11: pb.RegionRuntimeStatusRequest
	(*RegionRuntimeStatusResponse)(nil),   // 12: pb.RegionRuntimeStatusResponse
	(*RegionMeta)(nil),                    // 13: pb.RegionMeta
}
var file_adminpb_proto_depIdxs = []int32{
	13, // 0: pb.AddPeerResponse.region:type_name -> pb.RegionMeta
	13, // 1: pb.RemovePeerResponse.region:type_name -> pb.RegionMeta
	13, // 2: pb.TransferLeaderResponse.region:type_name -> pb.RegionMeta
	0,  // 3: pb.ExportRegionSnapshotRequest.format:type_name -> pb.RegionSnapshotFormat
	13, // 4: pb.ExportRegionSnapshotResponse.region:type_name -> pb.RegionMeta
	0,  // 5: pb.ExportRegionSnapshotResponse.format:type_name -> pb.RegionSnapshotFormat
	0,  // 6: pb.InstallRegionSnapshotRequest.format:type_name -> pb.RegionSnapshotFormat
	13, // 7: pb.InstallRegionSnapshotResponse.region:type_name -> pb.RegionMeta
	13, // 8: pb.RegionRuntimeStatusResponse.region:type_name -> pb.RegionMeta
	1,  // 9: pb.RaftAdmin.AddPeer:input_type -> pb.AddPeerRequest
	3,  // 10: pb.RaftAdmin.RemovePeer:input_type -> pb.RemovePeerRequest
	5,  // 11: pb.RaftAdmin.TransferLeader:input_type -> pb.TransferLeaderRequest
	7,  // 12: pb.RaftAdmin.ExportRegionSnapshot:input_type -> pb.ExportRegionSnapshotRequest
	9,  // 13: pb.RaftAdmin.InstallRegionSnapshot:input_type -> pb.InstallRegionSnapshotRequest
	11, // 14: pb.RaftAdmin.RegionRuntimeStatus:input_type -> pb.RegionRuntimeStatusRequest
	2,  // 15: pb.RaftAdmin.AddPeer:output_type -> pb.AddPeerResponse
	4,  // 16: pb.RaftAdmin.RemovePeer:output_type -> pb.RemovePeerResponse
	6,  // 17: pb.RaftAdmin.TransferLeader:output_type -> pb.TransferLeaderResponse
	8,  // 18: pb.RaftAdmin.ExportRegionSnapshot:output_type -> pb.ExportRegionSnapshotResponse
	10, // 19: pb.RaftAdmin.InstallRegionSnapshot:output_type -> pb.InstallRegionSnapshotResponse
	12, // 20: pb.RaftAdmin.RegionRuntimeStatus:output_type -> pb.RegionRuntimeStatusResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_adminpb_proto_init() }
func file_adminpb_proto_init() {
	if File_adminpb_proto != nil {
		return
	}
	file_metapb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adminpb_proto_rawDesc), len(file_adminpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adminpb_proto_goTypes,
		DependencyIndexes: file_adminpb_proto_depIdxs,
		EnumInfos:         file_adminpb_proto_enumTypes,
		MessageInfos:      file_adminpb_proto_msgTypes,
	}.Build()
	File_adminpb_proto = out.File
	file_adminpb_proto_goTypes = nil
	file_adminpb_proto_depIdxs = nil
}
