// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: kvrpcpb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoKV_KvGet_FullMethodName            = "/pb.NoKV/KvGet"
	NoKV_KvBatchGet_FullMethodName       = "/pb.NoKV/KvBatchGet"
	NoKV_KvScan_FullMethodName           = "/pb.NoKV/KvScan"
	NoKV_KvPrewrite_FullMethodName       = "/pb.NoKV/KvPrewrite"
	NoKV_KvCommit_FullMethodName         = "/pb.NoKV/KvCommit"
	NoKV_KvBatchRollback_FullMethodName  = "/pb.NoKV/KvBatchRollback"
	NoKV_KvResolveLock_FullMethodName    = "/pb.NoKV/KvResolveLock"
	NoKV_KvCheckTxnStatus_FullMethodName = "/pb.NoKV/KvCheckTxnStatus"
)

// NoKVClient is the client API for NoKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoKVClient interface {
	KvGet(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error)
	KvBatchGet(ctx context.Context, in *KvBatchGetRequest, opts ...grpc.CallOption) (*KvBatchGetResponse, error)
	KvScan(ctx context.Context, in *KvScanRequest, opts ...grpc.CallOption) (*KvScanResponse, error)
	KvPrewrite(ctx context.Context, in *KvPrewriteRequest, opts ...grpc.CallOption) (*KvPrewriteResponse, error)
	KvCommit(ctx context.Context, in *KvCommitRequest, opts ...grpc.CallOption) (*KvCommitResponse, error)
	KvBatchRollback(ctx context.Context, in *KvBatchRollbackRequest, opts ...grpc.CallOption) (*KvBatchRollbackResponse, error)
	KvResolveLock(ctx context.Context, in *KvResolveLockRequest, opts ...grpc.CallOption) (*KvResolveLockResponse, error)
	KvCheckTxnStatus(ctx context.Context, in *KvCheckTxnStatusRequest, opts ...grpc.CallOption) (*KvCheckTxnStatusResponse, error)
}

type noKVClient struct {
	cc grpc.ClientConnInterface
}

func NewNoKVClient(cc grpc.ClientConnInterface) NoKVClient {
	return &noKVClient{cc}
}

func (c *noKVClient) KvGet(ctx context.Context, in *KvGetRequest, opts ...grpc.CallOption) (*KvGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvGetResponse)
	err := c.cc.Invoke(ctx, NoKV_KvGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noKVClient) KvBatchGet(ctx context.Context, in *KvBatchGetRequest, opts ...grpc.CallOption) (*KvBatchGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBatchGetResponse)
	err := c.cc.Invoke(ctx, NoKV_KvBatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noKVClient) KvScan(ctx context.Context, in *KvScanRequest, opts ...grpc.CallOption) (*KvScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvScanResponse)
	err := c.cc.Invoke(ctx, NoKV_KvScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noKVClient) KvPrewrite(ctx context.Context, in *KvPrewriteRequest, opts ...grpc.CallOption) (*KvPrewriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvPrewriteResponse)
	err := c.cc.Invoke(ctx, NoKV_KvPrewrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noKVClient) KvCommit(ctx context.Context, in *KvCommitRequest, opts ...grpc.CallOption) (*KvCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvCommitResponse)
	err := c.cc.Invoke(ctx, NoKV_KvCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noKVClient) KvBatchRollback(ctx context.Context, in *KvBatchRollbackRequest, opts ...grpc.CallOption) (*KvBatchRollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvBatchRollbackResponse)
	err := c.cc.Invoke(ctx, NoKV_KvBatchRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noKVClient) KvResolveLock(ctx context.Context, in *KvResolveLockRequest, opts ...grpc.CallOption) (*KvResolveLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResolveLockResponse)
	err := c.cc.Invoke(ctx, NoKV_KvResolveLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noKVClient) KvCheckTxnStatus(ctx context.Context, in *KvCheckTxnStatusRequest, opts ...grpc.CallOption) (*KvCheckTxnStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvCheckTxnStatusResponse)
	err := c.cc.Invoke(ctx, NoKV_KvCheckTxnStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoKVServer is the server API for NoKV service.
// All implementations should embed UnimplementedNoKVServer
// for forward compatibility.
type NoKVServer interface {
	KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error)
	KvBatchGet(context.Context, *KvBatchGetRequest) (*KvBatchGetResponse, error)
	KvScan(context.Context, *KvScanRequest) (*KvScanResponse, error)
	KvPrewrite(context.Context, *KvPrewriteRequest) (*KvPrewriteResponse, error)
	KvCommit(context.Context, *KvCommitRequest) (*KvCommitResponse, error)
	KvBatchRollback(context.Context, *KvBatchRollbackRequest) (*KvBatchRollbackResponse, error)
	KvResolveLock(context.Context, *KvResolveLockRequest) (*KvResolveLockResponse, error)
	KvCheckTxnStatus(context.Context, *KvCheckTxnStatusRequest) (*KvCheckTxnStatusResponse, error)
}

// UnimplementedNoKVServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoKVServer struct{}

func (UnimplementedNoKVServer) KvGet(context.Context, *KvGetRequest) (*KvGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvGet not implemented")
}
func (UnimplementedNoKVServer) KvBatchGet(context.Context, *KvBatchGetRequest) (*KvBatchGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvBatchGet not implemented")
}
func (UnimplementedNoKVServer) KvScan(context.Context, *KvScanRequest) (*KvScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvScan not implemented")
}
func (UnimplementedNoKVServer) KvPrewrite(context.Context, *KvPrewriteRequest) (*KvPrewriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvPrewrite not implemented")
}
func (UnimplementedNoKVServer) KvCommit(context.Context, *KvCommitRequest) (*KvCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvCommit not implemented")
}
func (UnimplementedNoKVServer) KvBatchRollback(context.Context, *KvBatchRollbackRequest) (*KvBatchRollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvBatchRollback not implemented")
}
func (UnimplementedNoKVServer) KvResolveLock(context.Context, *KvResolveLockRequest) (*KvResolveLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvResolveLock not implemented")
}
func (UnimplementedNoKVServer) KvCheckTxnStatus(context.Context, *KvCheckTxnStatusRequest) (*KvCheckTxnStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvCheckTxnStatus not implemented")
}
func (UnimplementedNoKVServer) testEmbeddedByValue() {}

// UnsafeNoKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoKVServer will
// result in compilation errors.
type UnsafeNoKVServer interface {
	mustEmbedUnimplementedNoKVServer()
}

func RegisterNoKVServer(s grpc.ServiceRegistrar, srv NoKVServer) {
	// If the following call panics, it indicates UnimplementedNoKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoKV_ServiceDesc, srv)
}

func _NoKV_KvGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoKVServer).KvGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoKV_KvGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoKVServer).KvGet(ctx, req.(*KvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoKV_KvBatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoKVServer).KvBatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoKV_KvBatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoKVServer).KvBatchGet(ctx, req.(*KvBatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoKV_KvScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoKVServer).KvScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoKV_KvScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoKVServer).KvScan(ctx, req.(*KvScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoKV_KvPrewrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvPrewriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoKVServer).KvPrewrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoKV_KvPrewrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoKVServer).KvPrewrite(ctx, req.(*KvPrewriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoKV_KvCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoKVServer).KvCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoKV_KvCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoKVServer).KvCommit(ctx, req.(*KvCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoKV_KvBatchRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvBatchRollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoKVServer).KvBatchRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoKV_KvBatchRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoKVServer).KvBatchRollback(ctx, req.(*KvBatchRollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoKV_KvResolveLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvResolveLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoKVServer).KvResolveLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoKV_KvResolveLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoKVServer).KvResolveLock(ctx, req.(*KvResolveLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoKV_KvCheckTxnStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvCheckTxnStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoKVServer).KvCheckTxnStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoKV_KvCheckTxnStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoKVServer).KvCheckTxnStatus(ctx, req.(*KvCheckTxnStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoKV_ServiceDesc is the grpc.ServiceDesc for NoKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NoKV",
	HandlerType: (*NoKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KvGet",
			Handler:    _NoKV_KvGet_Handler,
		},
		{
			MethodName: "KvBatchGet",
			Handler:    _NoKV_KvBatchGet_Handler,
		},
		{
			MethodName: "KvScan",
			Handler:    _NoKV_KvScan_Handler,
		},
		{
			MethodName: "KvPrewrite",
			Handler:    _NoKV_KvPrewrite_Handler,
		},
		{
			MethodName: "KvCommit",
			Handler:    _NoKV_KvCommit_Handler,
		},
		{
			MethodName: "KvBatchRollback",
			Handler:    _NoKV_KvBatchRollback_Handler,
		},
		{
			MethodName: "KvResolveLock",
			Handler:    _NoKV_KvResolveLock_Handler,
		},
		{
			MethodName: "KvCheckTxnStatus",
			Handler:    _NoKV_KvCheckTxnStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvrpcpb.proto",
}
