// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pdpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedulerOperationType int32

const (
	SchedulerOperationType_SCHEDULER_OPERATION_TYPE_NONE            SchedulerOperationType = 0
	SchedulerOperationType_SCHEDULER_OPERATION_TYPE_LEADER_TRANSFER SchedulerOperationType = 1
)

// Enum value maps for SchedulerOperationType.
var (
	SchedulerOperationType_name = map[int32]string{
		0: "SCHEDULER_OPERATION_TYPE_NONE",
		1: "SCHEDULER_OPERATION_TYPE_LEADER_TRANSFER",
	}
	SchedulerOperationType_value = map[string]int32{
		"SCHEDULER_OPERATION_TYPE_NONE":            0,
		"SCHEDULER_OPERATION_TYPE_LEADER_TRANSFER": 1,
	}
)

func (x SchedulerOperationType) Enum() *SchedulerOperationType {
	p := new(SchedulerOperationType)
	*p = x
	return p
}

func (x SchedulerOperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulerOperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pdpb_proto_enumTypes[0].Descriptor()
}

func (SchedulerOperationType) Type() protoreflect.EnumType {
	return &file_pdpb_proto_enumTypes[0]
}

func (x SchedulerOperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulerOperationType.Descriptor instead.
func (SchedulerOperationType) EnumDescriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{0}
}

type StoreHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	RegionNum     uint64                 `protobuf:"varint,2,opt,name=region_num,json=regionNum,proto3" json:"region_num,omitempty"`
	LeaderNum     uint64                 `protobuf:"varint,3,opt,name=leader_num,json=leaderNum,proto3" json:"leader_num,omitempty"`
	Capacity      uint64                 `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Available     uint64                 `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHeartbeatRequest) Reset() {
	*x = StoreHeartbeatRequest{}
	mi := &file_pdpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHeartbeatRequest) ProtoMessage() {}

func (x *StoreHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StoreHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{0}
}

func (x *StoreHeartbeatRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *StoreHeartbeatRequest) GetRegionNum() uint64 {
	if x != nil {
		return x.RegionNum
	}
	return 0
}

func (x *StoreHeartbeatRequest) GetLeaderNum() uint64 {
	if x != nil {
		return x.LeaderNum
	}
	return 0
}

func (x *StoreHeartbeatRequest) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StoreHeartbeatRequest) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type SchedulerOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SchedulerOperationType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.SchedulerOperationType" json:"type,omitempty"`
	RegionId      uint64                 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	SourcePeerId  uint64                 `protobuf:"varint,3,opt,name=source_peer_id,json=sourcePeerId,proto3" json:"source_peer_id,omitempty"`
	TargetPeerId  uint64                 `protobuf:"varint,4,opt,name=target_peer_id,json=targetPeerId,proto3" json:"target_peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerOperation) Reset() {
	*x = SchedulerOperation{}
	mi := &file_pdpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerOperation) ProtoMessage() {}

func (x *SchedulerOperation) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerOperation.ProtoReflect.Descriptor instead.
func (*SchedulerOperation) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulerOperation) GetType() SchedulerOperationType {
	if x != nil {
		return x.Type
	}
	return SchedulerOperationType_SCHEDULER_OPERATION_TYPE_NONE
}

func (x *SchedulerOperation) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *SchedulerOperation) GetSourcePeerId() uint64 {
	if x != nil {
		return x.SourcePeerId
	}
	return 0
}

func (x *SchedulerOperation) GetTargetPeerId() uint64 {
	if x != nil {
		return x.TargetPeerId
	}
	return 0
}

type StoreHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Operations    []*SchedulerOperation  `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreHeartbeatResponse) Reset() {
	*x = StoreHeartbeatResponse{}
	mi := &file_pdpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHeartbeatResponse) ProtoMessage() {}

func (x *StoreHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StoreHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{2}
}

func (x *StoreHeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StoreHeartbeatResponse) GetOperations() []*SchedulerOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type RegionHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *RegionMeta            `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionHeartbeatRequest) Reset() {
	*x = RegionHeartbeatRequest{}
	mi := &file_pdpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionHeartbeatRequest) ProtoMessage() {}

func (x *RegionHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*RegionHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{3}
}

func (x *RegionHeartbeatRequest) GetRegion() *RegionMeta {
	if x != nil {
		return x.Region
	}
	return nil
}

type RegionHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionHeartbeatResponse) Reset() {
	*x = RegionHeartbeatResponse{}
	mi := &file_pdpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionHeartbeatResponse) ProtoMessage() {}

func (x *RegionHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*RegionHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{4}
}

func (x *RegionHeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RemoveRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRegionRequest) Reset() {
	*x = RemoveRegionRequest{}
	mi := &file_pdpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRegionRequest) ProtoMessage() {}

func (x *RemoveRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRegionRequest.ProtoReflect.Descriptor instead.
func (*RemoveRegionRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveRegionRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type RemoveRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRegionResponse) Reset() {
	*x = RemoveRegionResponse{}
	mi := &file_pdpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRegionResponse) ProtoMessage() {}

func (x *RemoveRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRegionResponse.ProtoReflect.Descriptor instead.
func (*RemoveRegionResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveRegionResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type GetRegionByKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionByKeyRequest) Reset() {
	*x = GetRegionByKeyRequest{}
	mi := &file_pdpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionByKeyRequest) ProtoMessage() {}

func (x *GetRegionByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionByKeyRequest.ProtoReflect.Descriptor instead.
func (*GetRegionByKeyRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{7}
}

func (x *GetRegionByKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetRegionByKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *RegionMeta            `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	NotFound      bool                   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionByKeyResponse) Reset() {
	*x = GetRegionByKeyResponse{}
	mi := &file_pdpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionByKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionByKeyResponse) ProtoMessage() {}

func (x *GetRegionByKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionByKeyResponse.ProtoReflect.Descriptor instead.
func (*GetRegionByKeyResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{8}
}

func (x *GetRegionByKeyResponse) GetRegion() *RegionMeta {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *GetRegionByKeyResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

type AllocIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocIDRequest) Reset() {
	*x = AllocIDRequest{}
	mi := &file_pdpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIDRequest) ProtoMessage() {}

func (x *AllocIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIDRequest.ProtoReflect.Descriptor instead.
func (*AllocIDRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{9}
}

func (x *AllocIDRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AllocIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstId       uint64                 `protobuf:"varint,1,opt,name=first_id,json=firstId,proto3" json:"first_id,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocIDResponse) Reset() {
	*x = AllocIDResponse{}
	mi := &file_pdpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIDResponse) ProtoMessage() {}

func (x *AllocIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIDResponse.ProtoReflect.Descriptor instead.
func (*AllocIDResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{10}
}

func (x *AllocIDResponse) GetFirstId() uint64 {
	if x != nil {
		return x.FirstId
	}
	return 0
}

func (x *AllocIDResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TsoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TsoRequest) Reset() {
	*x = TsoRequest{}
	mi := &file_pdpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsoRequest) ProtoMessage() {}

func (x *TsoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsoRequest.ProtoReflect.Descriptor instead.
func (*TsoRequest) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{11}
}

func (x *TsoRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TsoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TsoResponse) Reset() {
	*x = TsoResponse{}
	mi := &file_pdpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsoResponse) ProtoMessage() {}

func (x *TsoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsoResponse.ProtoReflect.Descriptor instead.
func (*TsoResponse) Descriptor() ([]byte, []int) {
	return file_pdpb_proto_rawDescGZIP(), []int{12}
}

func (x *TsoResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TsoResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_pdpb_proto protoreflect.FileDescriptor

const file_pdpb_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pdpb.proto\x12\x02pb\x1a\fmetapb.proto\"\xaa\x01\n" +
	"\x15StoreHeartbeatRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12\x1d\n" +
	"\n" +
	"region_num\x18\x02 \x01(\x04R\tregionNum\x12\x1d\n" +
	"\n" +
	"leader_num\x18\x03 \x01(\x04R\tleaderNum\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x04R\bcapacity\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\x04R\tavailable\"\xad\x01\n" +
	"\x12SchedulerOperation\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.pb.SchedulerOperationTypeR\x04type\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\x04R\bregionId\x12$\n" +
	"\x0esource_peer_id\x18\x03 \x01(\x04R\fsourcePeerId\x12$\n" +
	"\x0etarget_peer_id\x18\x04 \x01(\x04R\ftargetPeerId\"l\n" +
	"\x16StoreHeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x126\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x16.pb.SchedulerOperationR\n" +
	"operations\"@\n" +
	"\x16RegionHeartbeatRequest\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.pb.RegionMetaR\x06region\"5\n" +
	"\x17RegionHeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"2\n" +
	"\x13RemoveRegionRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"0\n" +
	"\x14RemoveRegionResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\")\n" +
	"\x15GetRegionByKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"]\n" +
	"\x16GetRegionByKeyResponse\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.pb.RegionMetaR\x06region\x12\x1b\n" +
	"\tnot_found\x18\x02 \x01(\bR\bnotFound\"&\n" +
	"\x0eAllocIDRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"B\n" +
	"\x0fAllocIDResponse\x12\x19\n" +
	"\bfirst_id\x18\x01 \x01(\x04R\afirstId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"\"\n" +
	"\n" +
	"TsoRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"A\n" +
	"\vTsoResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count*i\n" +
	"\x16SchedulerOperationType\x12!\n" +
	"\x1dSCHEDULER_OPERATION_TYPE_NONE\x10\x00\x12,\n" +
	"(SCHEDULER_OPERATION_TYPE_LEADER_TRANSFER\x10\x012\x81\x03\n" +
	"\x02PD\x12G\n" +
	"\x0eStoreHeartbeat\x12\x19.pb.StoreHeartbeatRequest\x1a\x1a.pb.StoreHeartbeatResponse\x12J\n" +
	"\x0fRegionHeartbeat\x12\x1a.pb.RegionHeartbeatRequest\x1a\x1b.pb.RegionHeartbeatResponse\x12A\n" +
	"\fRemoveRegion\x12\x17.pb.RemoveRegionRequest\x1a\x18.pb.RemoveRegionResponse\x12G\n" +
	"\x0eGetRegionByKey\x12\x19.pb.GetRegionByKeyRequest\x1a\x1a.pb.GetRegionByKeyResponse\x122\n" +
	"\aAllocID\x12\x12.pb.AllocIDRequest\x1a\x13.pb.AllocIDResponse\x12&\n" +
	"\x03Tso\x12\x0e.pb.TsoRequest\x1a\x0f.pb.TsoResponseB Z\x1egithub.com/feichai0017/NoKV/pbb\x06proto3"

var (
	file_pdpb_proto_rawDescOnce sync.Once
	file_pdpb_proto_rawDescData []byte
)

func file_pdpb_proto_rawDescGZIP() []byte {
	file_pdpb_proto_rawDescOnce.Do(func() {
		file_pdpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pdpb_proto_rawDesc), len(file_pdpb_proto_rawDesc)))
	})
	return file_pdpb_proto_rawDescData
}

var file_pdpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pdpb_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pdpb_proto_goTypes = []any{
	(SchedulerOperationType)(0),     // 0: pb.SchedulerOperationType
	(*StoreHeartbeatRequest)(nil),   // 1: pb.StoreHeartbeatRequest
	(*SchedulerOperation)(nil),      // 2: pb.SchedulerOperation
	(*StoreHeartbeatResponse)(nil),  // 3: pb.StoreHeartbeatResponse
	(*RegionHeartbeatRequest)(nil),  // 4: pb.RegionHeartbeatRequest
	(*RegionHeartbeatResponse)(nil), // 5: pb.RegionHeartbeatResponse
	(*RemoveRegionRequest)(nil),     // 6: pb.RemoveRegionRequest
	(*RemoveRegionResponse)(nil),    // 7: pb.RemoveRegionResponse
	(*GetRegionByKeyRequest)(nil),   // 8: pb.GetRegionByKeyRequest
	(*GetRegionByKeyResponse)(nil),  // 9: pb.GetRegionByKeyResponse
	(*AllocIDRequest)(nil),          // 10: pb.AllocIDRequest
	(*AllocIDResponse)(nil),         // 11: pb.AllocIDResponse
	(*TsoRequest)(nil),              // 12: pb.TsoRequest
	(*TsoResponse)(nil),             // 13: pb.TsoResponse
	(*RegionMeta)(nil),              // 14: pb.RegionMeta
}
var file_pdpb_proto_depIdxs = []int32{
	0,  // 0: pb.SchedulerOperation.type:type_name -> pb.SchedulerOperationType
	2,  // 1: pb.StoreHeartbeatResponse.operations:type_name -> pb.SchedulerOperation
	14, // 2: pb.RegionHeartbeatRequest.region:type_name -> pb.RegionMeta
	14, // 3: pb.GetRegionByKeyResponse.region:type_name -> pb.RegionMeta
	1,  // 4: pb.PD.StoreHeartbeat:input_type -> pb.StoreHeartbeatRequest
	4,  // 5: pb.PD.RegionHeartbeat:input_type -> pb.RegionHeartbeatRequest
	6,  // 6: pb.PD.RemoveRegion:input_type -> pb.RemoveRegionRequest
	8,  // 7: pb.PD.GetRegionByKey:input_type -> pb.GetRegionByKeyRequest
	10, // 8: pb.PD.AllocID:input_type -> pb.AllocIDRequest
	12, // 9: pb.PD.Tso:input_type -> pb.TsoRequest
	3,  // 10: pb.PD.StoreHeartbeat:output_type -> pb.StoreHeartbeatResponse
	5,  // 11: pb.PD.RegionHeartbeat:output_type -> pb.RegionHeartbeatResponse
	7,  // 12: pb.PD.RemoveRegion:output_type -> pb.RemoveRegionResponse
	9,  // 13: pb.PD.GetRegionByKey:output_type -> pb.GetRegionByKeyResponse
	11, // 14: pb.PD.AllocID:output_type -> pb.AllocIDResponse
	13, // 15: pb.PD.Tso:output_type -> pb.TsoResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pdpb_proto_init() }
func file_pdpb_proto_init() {
	if File_pdpb_proto != nil {
		return
	}
	file_metapb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pdpb_proto_rawDesc), len(file_pdpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pdpb_proto_goTypes,
		DependencyIndexes: file_pdpb_proto_depIdxs,
		EnumInfos:         file_pdpb_proto_enumTypes,
		MessageInfos:      file_pdpb_proto_msgTypes,
	}.Build()
	File_pdpb_proto = out.File
	file_pdpb_proto_goTypes = nil
	file_pdpb_proto_depIdxs = nil
}
