// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: raftcmdpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdType int32

const (
	CmdType_CMD_INVALID          CmdType = 0
	CmdType_CMD_GET              CmdType = 1
	CmdType_CMD_SCAN             CmdType = 2
	CmdType_CMD_PREWRITE         CmdType = 3
	CmdType_CMD_COMMIT           CmdType = 4
	CmdType_CMD_BATCH_ROLLBACK   CmdType = 5
	CmdType_CMD_RESOLVE_LOCK     CmdType = 6
	CmdType_CMD_CHECK_TXN_STATUS CmdType = 7
)

// Enum value maps for CmdType.
var (
	CmdType_name = map[int32]string{
		0: "CMD_INVALID",
		1: "CMD_GET",
		2: "CMD_SCAN",
		3: "CMD_PREWRITE",
		4: "CMD_COMMIT",
		5: "CMD_BATCH_ROLLBACK",
		6: "CMD_RESOLVE_LOCK",
		7: "CMD_CHECK_TXN_STATUS",
	}
	CmdType_value = map[string]int32{
		"CMD_INVALID":          0,
		"CMD_GET":              1,
		"CMD_SCAN":             2,
		"CMD_PREWRITE":         3,
		"CMD_COMMIT":           4,
		"CMD_BATCH_ROLLBACK":   5,
		"CMD_RESOLVE_LOCK":     6,
		"CMD_CHECK_TXN_STATUS": 7,
	}
)

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}

func (x CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_raftcmdpb_proto_enumTypes[0].Descriptor()
}

func (CmdType) Type() protoreflect.EnumType {
	return &file_raftcmdpb_proto_enumTypes[0]
}

func (x CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdType.Descriptor instead.
func (CmdType) EnumDescriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{0}
}

type AdminCommand_Type int32

const (
	AdminCommand_UNKNOWN AdminCommand_Type = 0
	AdminCommand_SPLIT   AdminCommand_Type = 1
	AdminCommand_MERGE   AdminCommand_Type = 2
)

// Enum value maps for AdminCommand_Type.
var (
	AdminCommand_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "SPLIT",
		2: "MERGE",
	}
	AdminCommand_Type_value = map[string]int32{
		"UNKNOWN": 0,
		"SPLIT":   1,
		"MERGE":   2,
	}
)

func (x AdminCommand_Type) Enum() *AdminCommand_Type {
	p := new(AdminCommand_Type)
	*p = x
	return p
}

func (x AdminCommand_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminCommand_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_raftcmdpb_proto_enumTypes[1].Descriptor()
}

func (AdminCommand_Type) Type() protoreflect.EnumType {
	return &file_raftcmdpb_proto_enumTypes[1]
}

func (x AdminCommand_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminCommand_Type.Descriptor instead.
func (AdminCommand_Type) EnumDescriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{2, 0}
}

type SplitCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ParentRegionId uint64                 `protobuf:"varint,1,opt,name=parent_region_id,json=parentRegionId,proto3" json:"parent_region_id,omitempty"`
	SplitKey       []byte                 `protobuf:"bytes,2,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	Child          *RegionMeta            `protobuf:"bytes,3,opt,name=child,proto3" json:"child,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SplitCommand) Reset() {
	*x = SplitCommand{}
	mi := &file_raftcmdpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitCommand) ProtoMessage() {}

func (x *SplitCommand) ProtoReflect() protoreflect.Message {
	mi := &file_raftcmdpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitCommand.ProtoReflect.Descriptor instead.
func (*SplitCommand) Descriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{0}
}

func (x *SplitCommand) GetParentRegionId() uint64 {
	if x != nil {
		return x.ParentRegionId
	}
	return 0
}

func (x *SplitCommand) GetSplitKey() []byte {
	if x != nil {
		return x.SplitKey
	}
	return nil
}

func (x *SplitCommand) GetChild() *RegionMeta {
	if x != nil {
		return x.Child
	}
	return nil
}

type MergeCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetRegionId uint64                 `protobuf:"varint,1,opt,name=target_region_id,json=targetRegionId,proto3" json:"target_region_id,omitempty"`
	SourceRegionId uint64                 `protobuf:"varint,2,opt,name=source_region_id,json=sourceRegionId,proto3" json:"source_region_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MergeCommand) Reset() {
	*x = MergeCommand{}
	mi := &file_raftcmdpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeCommand) ProtoMessage() {}

func (x *MergeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_raftcmdpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeCommand.ProtoReflect.Descriptor instead.
func (*MergeCommand) Descriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{1}
}

func (x *MergeCommand) GetTargetRegionId() uint64 {
	if x != nil {
		return x.TargetRegionId
	}
	return 0
}

func (x *MergeCommand) GetSourceRegionId() uint64 {
	if x != nil {
		return x.SourceRegionId
	}
	return 0
}

type AdminCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AdminCommand_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=pb.AdminCommand_Type" json:"type,omitempty"`
	Split         *SplitCommand          `protobuf:"bytes,2,opt,name=split,proto3" json:"split,omitempty"`
	Merge         *MergeCommand          `protobuf:"bytes,3,opt,name=merge,proto3" json:"merge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCommand) Reset() {
	*x = AdminCommand{}
	mi := &file_raftcmdpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCommand) ProtoMessage() {}

func (x *AdminCommand) ProtoReflect() protoreflect.Message {
	mi := &file_raftcmdpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCommand.ProtoReflect.Descriptor instead.
func (*AdminCommand) Descriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{2}
}

func (x *AdminCommand) GetType() AdminCommand_Type {
	if x != nil {
		return x.Type
	}
	return AdminCommand_UNKNOWN
}

func (x *AdminCommand) GetSplit() *SplitCommand {
	if x != nil {
		return x.Split
	}
	return nil
}

func (x *AdminCommand) GetMerge() *MergeCommand {
	if x != nil {
		return x.Merge
	}
	return nil
}

type CmdHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	RegionEpoch   *RegionEpoch           `protobuf:"bytes,2,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	PeerId        uint64                 `protobuf:"varint,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ReadQuorum    bool                   `protobuf:"varint,4,opt,name=read_quorum,json=readQuorum,proto3" json:"read_quorum,omitempty"`
	RequestId     uint64                 `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdHeader) Reset() {
	*x = CmdHeader{}
	mi := &file_raftcmdpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdHeader) ProtoMessage() {}

func (x *CmdHeader) ProtoReflect() protoreflect.Message {
	mi := &file_raftcmdpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdHeader.ProtoReflect.Descriptor instead.
func (*CmdHeader) Descriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{3}
}

func (x *CmdHeader) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *CmdHeader) GetRegionEpoch() *RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *CmdHeader) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *CmdHeader) GetReadQuorum() bool {
	if x != nil {
		return x.ReadQuorum
	}
	return false
}

func (x *CmdHeader) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type Request struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	CmdType CmdType                `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=pb.CmdType" json:"cmd_type,omitempty"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Request_Get
	//	*Request_Scan
	//	*Request_Prewrite
	//	*Request_Commit
	//	*Request_BatchRollback
	//	*Request_ResolveLock
	//	*Request_CheckTxnStatus
	Cmd           isRequest_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_raftcmdpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_raftcmdpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetCmdType() CmdType {
	if x != nil {
		return x.CmdType
	}
	return CmdType_CMD_INVALID
}

func (x *Request) GetCmd() isRequest_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Request) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Request_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Request) GetScan() *ScanRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Request_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

func (x *Request) GetPrewrite() *PrewriteRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Request_Prewrite); ok {
			return x.Prewrite
		}
	}
	return nil
}

func (x *Request) GetCommit() *CommitRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Request_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Request) GetBatchRollback() *BatchRollbackRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Request_BatchRollback); ok {
			return x.BatchRollback
		}
	}
	return nil
}

func (x *Request) GetResolveLock() *ResolveLockRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Request_ResolveLock); ok {
			return x.ResolveLock
		}
	}
	return nil
}

func (x *Request) GetCheckTxnStatus() *CheckTxnStatusRequest {
	if x != nil {
		if x, ok := x.Cmd.(*Request_CheckTxnStatus); ok {
			return x.CheckTxnStatus
		}
	}
	return nil
}

type isRequest_Cmd interface {
	isRequest_Cmd()
}

type Request_Get struct {
	Get *GetRequest `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type Request_Scan struct {
	Scan *ScanRequest `protobuf:"bytes,3,opt,name=scan,proto3,oneof"`
}

type Request_Prewrite struct {
	Prewrite *PrewriteRequest `protobuf:"bytes,4,opt,name=prewrite,proto3,oneof"`
}

type Request_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,5,opt,name=commit,proto3,oneof"`
}

type Request_BatchRollback struct {
	BatchRollback *BatchRollbackRequest `protobuf:"bytes,6,opt,name=batch_rollback,json=batchRollback,proto3,oneof"`
}

type Request_ResolveLock struct {
	ResolveLock *ResolveLockRequest `protobuf:"bytes,7,opt,name=resolve_lock,json=resolveLock,proto3,oneof"`
}

type Request_CheckTxnStatus struct {
	CheckTxnStatus *CheckTxnStatusRequest `protobuf:"bytes,8,opt,name=check_txn_status,json=checkTxnStatus,proto3,oneof"`
}

func (*Request_Get) isRequest_Cmd() {}

func (*Request_Scan) isRequest_Cmd() {}

func (*Request_Prewrite) isRequest_Cmd() {}

func (*Request_Commit) isRequest_Cmd() {}

func (*Request_BatchRollback) isRequest_Cmd() {}

func (*Request_ResolveLock) isRequest_Cmd() {}

func (*Request_CheckTxnStatus) isRequest_Cmd() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Response_Get
	//	*Response_Scan
	//	*Response_Prewrite
	//	*Response_Commit
	//	*Response_BatchRollback
	//	*Response_ResolveLock
	//	*Response_CheckTxnStatus
	Cmd           isResponse_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_raftcmdpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_raftcmdpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetCmd() isResponse_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Response) GetGet() *GetResponse {
	if x != nil {
		if x, ok := x.Cmd.(*Response_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Response) GetScan() *ScanResponse {
	if x != nil {
		if x, ok := x.Cmd.(*Response_Scan); ok {
			return x.Scan
		}
	}
	return nil
}

func (x *Response) GetPrewrite() *PrewriteResponse {
	if x != nil {
		if x, ok := x.Cmd.(*Response_Prewrite); ok {
			return x.Prewrite
		}
	}
	return nil
}

func (x *Response) GetCommit() *CommitResponse {
	if x != nil {
		if x, ok := x.Cmd.(*Response_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *Response) GetBatchRollback() *BatchRollbackResponse {
	if x != nil {
		if x, ok := x.Cmd.(*Response_BatchRollback); ok {
			return x.BatchRollback
		}
	}
	return nil
}

func (x *Response) GetResolveLock() *ResolveLockResponse {
	if x != nil {
		if x, ok := x.Cmd.(*Response_ResolveLock); ok {
			return x.ResolveLock
		}
	}
	return nil
}

func (x *Response) GetCheckTxnStatus() *CheckTxnStatusResponse {
	if x != nil {
		if x, ok := x.Cmd.(*Response_CheckTxnStatus); ok {
			return x.CheckTxnStatus
		}
	}
	return nil
}

type isResponse_Cmd interface {
	isResponse_Cmd()
}

type Response_Get struct {
	Get *GetResponse `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type Response_Scan struct {
	Scan *ScanResponse `protobuf:"bytes,2,opt,name=scan,proto3,oneof"`
}

type Response_Prewrite struct {
	Prewrite *PrewriteResponse `protobuf:"bytes,3,opt,name=prewrite,proto3,oneof"`
}

type Response_Commit struct {
	Commit *CommitResponse `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

type Response_BatchRollback struct {
	BatchRollback *BatchRollbackResponse `protobuf:"bytes,5,opt,name=batch_rollback,json=batchRollback,proto3,oneof"`
}

type Response_ResolveLock struct {
	ResolveLock *ResolveLockResponse `protobuf:"bytes,6,opt,name=resolve_lock,json=resolveLock,proto3,oneof"`
}

type Response_CheckTxnStatus struct {
	CheckTxnStatus *CheckTxnStatusResponse `protobuf:"bytes,7,opt,name=check_txn_status,json=checkTxnStatus,proto3,oneof"`
}

func (*Response_Get) isResponse_Cmd() {}

func (*Response_Scan) isResponse_Cmd() {}

func (*Response_Prewrite) isResponse_Cmd() {}

func (*Response_Commit) isResponse_Cmd() {}

func (*Response_BatchRollback) isResponse_Cmd() {}

func (*Response_ResolveLock) isResponse_Cmd() {}

func (*Response_CheckTxnStatus) isResponse_Cmd() {}

type RaftCmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *CmdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Requests      []*Request             `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCmdRequest) Reset() {
	*x = RaftCmdRequest{}
	mi := &file_raftcmdpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCmdRequest) ProtoMessage() {}

func (x *RaftCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftcmdpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCmdRequest.ProtoReflect.Descriptor instead.
func (*RaftCmdRequest) Descriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{6}
}

func (x *RaftCmdRequest) GetHeader() *CmdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RaftCmdRequest) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type RaftCmdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *CmdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Responses     []*Response            `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	RegionError   *RegionError           `protobuf:"bytes,3,opt,name=region_error,json=regionError,proto3" json:"region_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCmdResponse) Reset() {
	*x = RaftCmdResponse{}
	mi := &file_raftcmdpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCmdResponse) ProtoMessage() {}

func (x *RaftCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftcmdpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCmdResponse.ProtoReflect.Descriptor instead.
func (*RaftCmdResponse) Descriptor() ([]byte, []int) {
	return file_raftcmdpb_proto_rawDescGZIP(), []int{7}
}

func (x *RaftCmdResponse) GetHeader() *CmdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RaftCmdResponse) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *RaftCmdResponse) GetRegionError() *RegionError {
	if x != nil {
		return x.RegionError
	}
	return nil
}

var File_raftcmdpb_proto protoreflect.FileDescriptor

const file_raftcmdpb_proto_rawDesc = "" +
	"\n" +
	"\x0fraftcmdpb.proto\x12\x02pb\x1a\rkvrpcpb.proto\x1a\fmetapb.proto\"{\n" +
	"\fSplitCommand\x12(\n" +
	"\x10parent_region_id\x18\x01 \x01(\x04R\x0eparentRegionId\x12\x1b\n" +
	"\tsplit_key\x18\x02 \x01(\fR\bsplitKey\x12$\n" +
	"\x05child\x18\x03 \x01(\v2\x0e.pb.RegionMetaR\x05child\"b\n" +
	"\fMergeCommand\x12(\n" +
	"\x10target_region_id\x18\x01 \x01(\x04R\x0etargetRegionId\x12(\n" +
	"\x10source_region_id\x18\x02 \x01(\x04R\x0esourceRegionId\"\xb4\x01\n" +
	"\fAdminCommand\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.pb.AdminCommand.TypeR\x04type\x12&\n" +
	"\x05split\x18\x02 \x01(\v2\x10.pb.SplitCommandR\x05split\x12&\n" +
	"\x05merge\x18\x03 \x01(\v2\x10.pb.MergeCommandR\x05merge\")\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05SPLIT\x10\x01\x12\t\n" +
	"\x05MERGE\x10\x02\"\xb5\x01\n" +
	"\tCmdHeader\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x122\n" +
	"\fregion_epoch\x18\x02 \x01(\v2\x0f.pb.RegionEpochR\vregionEpoch\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\x04R\x06peerId\x12\x1f\n" +
	"\vread_quorum\x18\x04 \x01(\bR\n" +
	"readQuorum\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x04R\trequestId\"\xaa\x03\n" +
	"\aRequest\x12&\n" +
	"\bcmd_type\x18\x01 \x01(\x0e2\v.pb.CmdTypeR\acmdType\x12\"\n" +
	"\x03get\x18\x02 \x01(\v2\x0e.pb.GetRequestH\x00R\x03get\x12%\n" +
	"\x04scan\x18\x03 \x01(\v2\x0f.pb.ScanRequestH\x00R\x04scan\x121\n" +
	"\bprewrite\x18\x04 \x01(\v2\x13.pb.PrewriteRequestH\x00R\bprewrite\x12+\n" +
	"\x06commit\x18\x05 \x01(\v2\x11.pb.CommitRequestH\x00R\x06commit\x12A\n" +
	"\x0ebatch_rollback\x18\x06 \x01(\v2\x18.pb.BatchRollbackRequestH\x00R\rbatchRollback\x12;\n" +
	"\fresolve_lock\x18\a \x01(\v2\x16.pb.ResolveLockRequestH\x00R\vresolveLock\x12E\n" +
	"\x10check_txn_status\x18\b \x01(\v2\x19.pb.CheckTxnStatusRequestH\x00R\x0echeckTxnStatusB\x05\n" +
	"\x03cmd\"\x8a\x03\n" +
	"\bResponse\x12#\n" +
	"\x03get\x18\x01 \x01(\v2\x0f.pb.GetResponseH\x00R\x03get\x12&\n" +
	"\x04scan\x18\x02 \x01(\v2\x10.pb.ScanResponseH\x00R\x04scan\x122\n" +
	"\bprewrite\x18\x03 \x01(\v2\x14.pb.PrewriteResponseH\x00R\bprewrite\x12,\n" +
	"\x06commit\x18\x04 \x01(\v2\x12.pb.CommitResponseH\x00R\x06commit\x12B\n" +
	"\x0ebatch_rollback\x18\x05 \x01(\v2\x19.pb.BatchRollbackResponseH\x00R\rbatchRollback\x12<\n" +
	"\fresolve_lock\x18\x06 \x01(\v2\x17.pb.ResolveLockResponseH\x00R\vresolveLock\x12F\n" +
	"\x10check_txn_status\x18\a \x01(\v2\x1a.pb.CheckTxnStatusResponseH\x00R\x0echeckTxnStatusB\x05\n" +
	"\x03cmd\"`\n" +
	"\x0eRaftCmdRequest\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\r.pb.CmdHeaderR\x06header\x12'\n" +
	"\brequests\x18\x02 \x03(\v2\v.pb.RequestR\brequests\"\x98\x01\n" +
	"\x0fRaftCmdResponse\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\r.pb.CmdHeaderR\x06header\x12*\n" +
	"\tresponses\x18\x02 \x03(\v2\f.pb.ResponseR\tresponses\x122\n" +
	"\fregion_error\x18\x03 \x01(\v2\x0f.pb.RegionErrorR\vregionError*\x9f\x01\n" +
	"\aCmdType\x12\x0f\n" +
	"\vCMD_INVALID\x10\x00\x12\v\n" +
	"\aCMD_GET\x10\x01\x12\f\n" +
	"\bCMD_SCAN\x10\x02\x12\x10\n" +
	"\fCMD_PREWRITE\x10\x03\x12\x0e\n" +
	"\n" +
	"CMD_COMMIT\x10\x04\x12\x16\n" +
	"\x12CMD_BATCH_ROLLBACK\x10\x05\x12\x14\n" +
	"\x10CMD_RESOLVE_LOCK\x10\x06\x12\x18\n" +
	"\x14CMD_CHECK_TXN_STATUS\x10\aB Z\x1egithub.com/feichai0017/NoKV/pbb\x06proto3"

var (
	file_raftcmdpb_proto_rawDescOnce sync.Once
	file_raftcmdpb_proto_rawDescData []byte
)

func file_raftcmdpb_proto_rawDescGZIP() []byte {
	file_raftcmdpb_proto_rawDescOnce.Do(func() {
		file_raftcmdpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftcmdpb_proto_rawDesc), len(file_raftcmdpb_proto_rawDesc)))
	})
	return file_raftcmdpb_proto_rawDescData
}

var file_raftcmdpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_raftcmdpb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_raftcmdpb_proto_goTypes = []any{
	(CmdType)(0),                   // 0: pb.CmdType
	(AdminCommand_Type)(0),         // 1: pb.AdminCommand.Type
	(*SplitCommand)(nil),           // 2: pb.SplitCommand
	(*MergeCommand)(nil),           // 3: pb.MergeCommand
	(*AdminCommand)(nil),           // 4: pb.AdminCommand
	(*CmdHeader)(nil),              // 5: pb.CmdHeader
	(*Request)(nil),                // 6: pb.Request
	(*Response)(nil),               // 7: pb.Response
	(*RaftCmdRequest)(nil),         // 8: pb.RaftCmdRequest
	(*RaftCmdResponse)(nil),        // 9: pb.RaftCmdResponse
	(*RegionMeta)(nil),             // 10: pb.RegionMeta
	(*RegionEpoch)(nil),            // 11: pb.RegionEpoch
	(*GetRequest)(nil),             // 12: pb.GetRequest
	(*ScanRequest)(nil),            // 13: pb.ScanRequest
	(*PrewriteRequest)(nil),        // 14: pb.PrewriteRequest
	(*CommitRequest)(nil),          // 15: pb.CommitRequest
	(*BatchRollbackRequest)(nil),   // 16: pb.BatchRollbackRequest
	(*ResolveLockRequest)(nil),     // 17: pb.ResolveLockRequest
	(*CheckTxnStatusRequest)(nil),  // 18: pb.CheckTxnStatusRequest
	(*GetResponse)(nil),            // 19: pb.GetResponse
	(*ScanResponse)(nil),           // 20: pb.ScanResponse
	(*PrewriteResponse)(nil),       // 21: pb.PrewriteResponse
	(*CommitResponse)(nil),         // 22: pb.CommitResponse
	(*BatchRollbackResponse)(nil),  // 23: pb.BatchRollbackResponse
	(*ResolveLockResponse)(nil),    // 24: pb.ResolveLockResponse
	(*CheckTxnStatusResponse)(nil), // 25: pb.CheckTxnStatusResponse
	(*RegionError)(nil),            // 26: pb.RegionError
}
var file_raftcmdpb_proto_depIdxs = []int32{
	10, // 0: pb.SplitCommand.child:type_name -> pb.RegionMeta
	1,  // 1: pb.AdminCommand.type:type_name -> pb.AdminCommand.Type
	2,  // 2: pb.AdminCommand.split:type_name -> pb.SplitCommand
	3,  // 3: pb.AdminCommand.merge:type_name -> pb.MergeCommand
	11, // 4: pb.CmdHeader.region_epoch:type_name -> pb.RegionEpoch
	0,  // 5: pb.Request.cmd_type:type_name -> pb.CmdType
	12, // 6: pb.Request.get:type_name -> pb.GetRequest
	13, // 7: pb.Request.scan:type_name -> pb.ScanRequest
	14, // 8: pb.Request.prewrite:type_name -> pb.PrewriteRequest
	15, // 9: pb.Request.commit:type_name -> pb.CommitRequest
	16, // 10: pb.Request.batch_rollback:type_name -> pb.BatchRollbackRequest
	17, // 11: pb.Request.resolve_lock:type_name -> pb.ResolveLockRequest
	18, // 12: pb.Request.check_txn_status:type_name -> pb.CheckTxnStatusRequest
	19, // 13: pb.Response.get:type_name -> pb.GetResponse
	20, // 14: pb.Response.scan:type_name -> pb.ScanResponse
	21, // 15: pb.Response.prewrite:type_name -> pb.PrewriteResponse
	22, // 16: pb.Response.commit:type_name -> pb.CommitResponse
	23, // 17: pb.Response.batch_rollback:type_name -> pb.BatchRollbackResponse
	24, // 18: pb.Response.resolve_lock:type_name -> pb.ResolveLockResponse
	25, // 19: pb.Response.check_txn_status:type_name -> pb.CheckTxnStatusResponse
	5,  // 20: pb.RaftCmdRequest.header:type_name -> pb.CmdHeader
	6,  // 21: pb.RaftCmdRequest.requests:type_name -> pb.Request
	5,  // 22: pb.RaftCmdResponse.header:type_name -> pb.CmdHeader
	7,  // 23: pb.RaftCmdResponse.responses:type_name -> pb.Response
	26, // 24: pb.RaftCmdResponse.region_error:type_name -> pb.RegionError
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_raftcmdpb_proto_init() }
func file_raftcmdpb_proto_init() {
	if File_raftcmdpb_proto != nil {
		return
	}
	file_kvrpcpb_proto_init()
	file_metapb_proto_init()
	file_raftcmdpb_proto_msgTypes[4].OneofWrappers = []any{
		(*Request_Get)(nil),
		(*Request_Scan)(nil),
		(*Request_Prewrite)(nil),
		(*Request_Commit)(nil),
		(*Request_BatchRollback)(nil),
		(*Request_ResolveLock)(nil),
		(*Request_CheckTxnStatus)(nil),
	}
	file_raftcmdpb_proto_msgTypes[5].OneofWrappers = []any{
		(*Response_Get)(nil),
		(*Response_Scan)(nil),
		(*Response_Prewrite)(nil),
		(*Response_Commit)(nil),
		(*Response_BatchRollback)(nil),
		(*Response_ResolveLock)(nil),
		(*Response_CheckTxnStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftcmdpb_proto_rawDesc), len(file_raftcmdpb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raftcmdpb_proto_goTypes,
		DependencyIndexes: file_raftcmdpb_proto_depIdxs,
		EnumInfos:         file_raftcmdpb_proto_enumTypes,
		MessageInfos:      file_raftcmdpb_proto_msgTypes,
	}.Build()
	File_raftcmdpb_proto = out.File
	file_raftcmdpb_proto_goTypes = nil
	file_raftcmdpb_proto_depIdxs = nil
}
