// Use scripts/gen.sh to generate .pb.go files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: storagepb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManifestChange_Operation int32

const (
	ManifestChange_CREATE ManifestChange_Operation = 0
	ManifestChange_DELETE ManifestChange_Operation = 1
)

// Enum value maps for ManifestChange_Operation.
var (
	ManifestChange_Operation_name = map[int32]string{
		0: "CREATE",
		1: "DELETE",
	}
	ManifestChange_Operation_value = map[string]int32{
		"CREATE": 0,
		"DELETE": 1,
	}
)

func (x ManifestChange_Operation) Enum() *ManifestChange_Operation {
	p := new(ManifestChange_Operation)
	*p = x
	return p
}

func (x ManifestChange_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManifestChange_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_storagepb_proto_enumTypes[0].Descriptor()
}

func (ManifestChange_Operation) Type() protoreflect.EnumType {
	return &file_storagepb_proto_enumTypes[0]
}

func (x ManifestChange_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManifestChange_Operation.Descriptor instead.
func (ManifestChange_Operation) EnumDescriptor() ([]byte, []int) {
	return file_storagepb_proto_rawDescGZIP(), []int{1, 0}
}

// ManifestChangeSet groups manifest edits that should be applied atomically.
type ManifestChangeSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A set of changes that are applied atomically.
	Changes       []*ManifestChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestChangeSet) Reset() {
	*x = ManifestChangeSet{}
	mi := &file_storagepb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestChangeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestChangeSet) ProtoMessage() {}

func (x *ManifestChangeSet) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestChangeSet.ProtoReflect.Descriptor instead.
func (*ManifestChangeSet) Descriptor() ([]byte, []int) {
	return file_storagepb_proto_rawDescGZIP(), []int{0}
}

func (x *ManifestChangeSet) GetChanges() []*ManifestChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

// ManifestChange describes one manifest delta generated by compaction/flush.
type ManifestChange struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            uint64                   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Op            ManifestChange_Operation `protobuf:"varint,2,opt,name=Op,proto3,enum=pb.ManifestChange_Operation" json:"Op,omitempty"`
	Level         uint32                   `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`      // Only used for CREATE
	Checksum      []byte                   `protobuf:"bytes,4,opt,name=Checksum,proto3" json:"Checksum,omitempty"` // Only used for CREATE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestChange) Reset() {
	*x = ManifestChange{}
	mi := &file_storagepb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestChange) ProtoMessage() {}

func (x *ManifestChange) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestChange.ProtoReflect.Descriptor instead.
func (*ManifestChange) Descriptor() ([]byte, []int) {
	return file_storagepb_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestChange) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ManifestChange) GetOp() ManifestChange_Operation {
	if x != nil {
		return x.Op
	}
	return ManifestChange_CREATE
}

func (x *ManifestChange) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ManifestChange) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// TableIndex is the protobuf-encoded SSTable index block payload.
type TableIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offsets       []*BlockOffset         `protobuf:"bytes,1,rep,name=offsets,proto3" json:"offsets,omitempty"`
	BloomFilter   []byte                 `protobuf:"bytes,2,opt,name=bloomFilter,proto3" json:"bloomFilter,omitempty"`
	MaxVersion    uint64                 `protobuf:"varint,3,opt,name=maxVersion,proto3" json:"maxVersion,omitempty"`
	KeyCount      uint32                 `protobuf:"varint,4,opt,name=keyCount,proto3" json:"keyCount,omitempty"`
	StaleDataSize uint32                 `protobuf:"varint,5,opt,name=staleDataSize,proto3" json:"staleDataSize,omitempty"`
	ValueSize     uint64                 `protobuf:"varint,6,opt,name=valueSize,proto3" json:"valueSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableIndex) Reset() {
	*x = TableIndex{}
	mi := &file_storagepb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableIndex) ProtoMessage() {}

func (x *TableIndex) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableIndex.ProtoReflect.Descriptor instead.
func (*TableIndex) Descriptor() ([]byte, []int) {
	return file_storagepb_proto_rawDescGZIP(), []int{2}
}

func (x *TableIndex) GetOffsets() []*BlockOffset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

func (x *TableIndex) GetBloomFilter() []byte {
	if x != nil {
		return x.BloomFilter
	}
	return nil
}

func (x *TableIndex) GetMaxVersion() uint64 {
	if x != nil {
		return x.MaxVersion
	}
	return 0
}

func (x *TableIndex) GetKeyCount() uint32 {
	if x != nil {
		return x.KeyCount
	}
	return 0
}

func (x *TableIndex) GetStaleDataSize() uint32 {
	if x != nil {
		return x.StaleDataSize
	}
	return 0
}

func (x *TableIndex) GetValueSize() uint64 {
	if x != nil {
		return x.ValueSize
	}
	return 0
}

// BlockOffset points to a single data block inside one SSTable file.
type BlockOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Len           uint32                 `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockOffset) Reset() {
	*x = BlockOffset{}
	mi := &file_storagepb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockOffset) ProtoMessage() {}

func (x *BlockOffset) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockOffset.ProtoReflect.Descriptor instead.
func (*BlockOffset) Descriptor() ([]byte, []int) {
	return file_storagepb_proto_rawDescGZIP(), []int{3}
}

func (x *BlockOffset) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BlockOffset) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlockOffset) GetLen() uint32 {
	if x != nil {
		return x.Len
	}
	return 0
}

var File_storagepb_proto protoreflect.FileDescriptor

const file_storagepb_proto_rawDesc = "" +
	"\n" +
	"\x0fstoragepb.proto\x12\x02pb\"A\n" +
	"\x11ManifestChangeSet\x12,\n" +
	"\achanges\x18\x01 \x03(\v2\x12.pb.ManifestChangeR\achanges\"\xa5\x01\n" +
	"\x0eManifestChange\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12,\n" +
	"\x02Op\x18\x02 \x01(\x0e2\x1c.pb.ManifestChange.OperationR\x02Op\x12\x14\n" +
	"\x05Level\x18\x03 \x01(\rR\x05Level\x12\x1a\n" +
	"\bChecksum\x18\x04 \x01(\fR\bChecksum\"#\n" +
	"\tOperation\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\"\xd9\x01\n" +
	"\n" +
	"TableIndex\x12)\n" +
	"\aoffsets\x18\x01 \x03(\v2\x0f.pb.BlockOffsetR\aoffsets\x12 \n" +
	"\vbloomFilter\x18\x02 \x01(\fR\vbloomFilter\x12\x1e\n" +
	"\n" +
	"maxVersion\x18\x03 \x01(\x04R\n" +
	"maxVersion\x12\x1a\n" +
	"\bkeyCount\x18\x04 \x01(\rR\bkeyCount\x12$\n" +
	"\rstaleDataSize\x18\x05 \x01(\rR\rstaleDataSize\x12\x1c\n" +
	"\tvalueSize\x18\x06 \x01(\x04R\tvalueSize\"I\n" +
	"\vBlockOffset\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x10\n" +
	"\x03len\x18\x03 \x01(\rR\x03lenB Z\x1egithub.com/feichai0017/NoKV/pbb\x06proto3"

var (
	file_storagepb_proto_rawDescOnce sync.Once
	file_storagepb_proto_rawDescData []byte
)

func file_storagepb_proto_rawDescGZIP() []byte {
	file_storagepb_proto_rawDescOnce.Do(func() {
		file_storagepb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storagepb_proto_rawDesc), len(file_storagepb_proto_rawDesc)))
	})
	return file_storagepb_proto_rawDescData
}

var file_storagepb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storagepb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storagepb_proto_goTypes = []any{
	(ManifestChange_Operation)(0), // 0: pb.ManifestChange.Operation
	(*ManifestChangeSet)(nil),     // 1: pb.ManifestChangeSet
	(*ManifestChange)(nil),        // 2: pb.ManifestChange
	(*TableIndex)(nil),            // 3: pb.TableIndex
	(*BlockOffset)(nil),           // 4: pb.BlockOffset
}
var file_storagepb_proto_depIdxs = []int32{
	2, // 0: pb.ManifestChangeSet.changes:type_name -> pb.ManifestChange
	0, // 1: pb.ManifestChange.Op:type_name -> pb.ManifestChange.Operation
	4, // 2: pb.TableIndex.offsets:type_name -> pb.BlockOffset
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_storagepb_proto_init() }
func file_storagepb_proto_init() {
	if File_storagepb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storagepb_proto_rawDesc), len(file_storagepb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storagepb_proto_goTypes,
		DependencyIndexes: file_storagepb_proto_depIdxs,
		EnumInfos:         file_storagepb_proto_enumTypes,
		MessageInfos:      file_storagepb_proto_msgTypes,
	}.Build()
	File_storagepb_proto = out.File
	file_storagepb_proto_goTypes = nil
	file_storagepb_proto_depIdxs = nil
}
